### DISCUSSION TITLE
Give us your feedback/impressions of 2.4 Beta 1 + Known Issues!

### DISCUSSION THREAD

**Discussion by TOoSmOotH** [Security-Onion-Solutions/securityonion#10063] [2.4]
Hopefully everyone is enjoying Beta 1! I wanted to start a thread to solicit feedback from the community on what you like or don't like so far. I also want to have a place where we can record known issues as they are identified by all of you. Below is a running list so far and I am sure will grow as more and more folks test things.

Known issues discovered so far from the community:

- Zeek is not honoring the lb_procs setting and only running in standalone mode. FIXED in B2
- Currently you cannot add or remove Zeek policies due to an issue with the UI. FIXED in B2
- Suricata annotations need updated.
- Adding new hostgroup in SOC -> firewall -> Custom firewall group will fault SOC configuration interface with error 502. @palichx 
- so-index-list is not working properly. @palichx 
- SOC is only showing data for users with superuser privs.
- Zeek BPF needs to be validated. @palichx 

Again thanks for helping us test! We are really excited about this release!

**Comment by palichx** [comment]
Hi,
New configuration interface is so good!
**issues**:
1) Adding new hostgroup in SOC -> firewall -> Custom firewall group will fault SOC configuration interface with error 502.
there are extra characters **`'`** in salt config 
![image](https://user-images.githubusercontent.com/80513304/228755047-8a498b42-2ad9-4b27-8b88-d65bd2be62cf.png)
2) so-index-list stopped with error:
![image](https://user-images.githubusercontent.com/80513304/228755573-8951148a-bcdc-4859-b01b-09bc57552f2b.png)
missing a space in script :)

**Ideas**:
IOC importer functionality in soc interface. 
1) Push ip/domain into zeek intel.dat;
2) Retrohunt queue feature based on elastalert rules. 
For example need check history logs for ip "1.1.1.1" from 2023-03-27 to 2023-03-30. Generating elastalert rule:
  
```
alert:
- "modules.so.playbook-es.PlaybookESAlerter"

elasticsearch_host: "192.168.100.238:9200"
play_title: "Example Elasalert rule"
play_id: "Example Elasalert rule"
event.module: "playbook"
event.dataset: "alert"
event.severity: 1
rule.category: ""
sigma_level: "low"

filter:
- query:
    query_string:
            query: (event.dataset:"conn" AND  (source.ip: 1.1.1.1 OR destination.ip: 1.1.1.1)) OR  (event.dataset:"dns" AND (dns.query.name: 1.1.1.1  OR dns.answers.name: 1.1.1.1)) OR (event.dataset:"http" AND http.proxied: 1.1.1.1)  OR (event.dataset:"smtp" AND smtp.path: 1.1.1.1) OR (event.dataset:"ssl" AND ssl.server_name: 1.1.1.1) 
index: '*:so-zeek*'
name: Example Elasalert rule - b366ef9a1bhost
priority: 4
realert:
  minutes: 60
type: any
```
and run this rule for past days
```
docker exec -it so-elastalert elastalert-test-rule /opt/elastalert/rules/playbook/example.yaml --config /opt/elastalert/config.yaml --start 2023-03-27T00:00:00 --end 2023-03-28T00:00:00
docker exec -it so-elastalert elastalert-test-rule /opt/elastalert/rules/playbook/example.yaml --config /opt/elastalert/config.yaml --start 2023-03-28T00:00:00 --end 2023-03-29T00:00:00
docker exec -it so-elastalert elastalert-test-rule /opt/elastalert/rules/playbook/example.yaml --config /opt/elastalert/config.yaml --start 2023-03-28T00:00:00 --end 2023-03-30T00:00:00
etc

```
