### DISCUSSION TITLE
Enable automatic GeoIP update in elastic

### DISCUSSION THREAD

**Discussion by xde012** [Security-Onion-Solutions/securityonion#10518] [Unsupported Versions] [answered]
hello,
I'm trying to update my geoip database in elastic and I can't get it, I see very little information regarding the subject of Salt and Elastic. 
We have enabled access to the following URLs: geoip.elastic.co and storage.googleapis.com

Within Security Onion I have several but I don't see clearly which file I should modify or add the "true" parameter to enable the automatic download.

I have the following assumptions, can someone tell me where it is exactly?

/opt/so/saltstack/local/pillar/global.sls

/opt/so/saltstack/local/pillar/elasticsearch/ (I don't have any files here)

/opt/so/saltstack/local/salt/elasticsearch/ (Here I have files and folders but everything related to key users and user roles)

The only place I have found the configuration is in /opt/so/conf/elasticsearch/elasticsearch.yml

But by changing the setting to "true" and restarting elastic this setting is cleared, so I understand it is required to be done via Saltstack.

Security Onion: 2.3.181
Elastic: 8.4.3

Thank you.

**Comment by argwfm** [comment, marked as answer]
Had success here adding everything below `config:` to `/opt/so/saltstack/local/pillar/global.sls`
```
elasticsearch:
  true_cluster: False
  replicas: 0
  discovery_nodes: 1
  hot_warm_enabled: False
  cluster_routing_allocation_disk.threshold_enabled: true
  cluster_routing_allocation_disk_watermark_low: '95%'
  cluster_routing_allocation_disk_watermark_high: '98%'
  cluster_routing_allocation_disk_watermark_flood_stage: '98%'
  config:
    ingest:
      geoip:
        downloader:
          enabled: true
```
