### DISCUSSION TITLE
Is there a way to re-ingest old (compressed) zeek logs?

### DISCUSSION THREAD

**Discussion by sanctanox** [Security-Onion-Solutions/securityonion#10709] [Unsupported Versions]
I deleted some indexes named "so-zeek-<YYYY.MM.DD>" that I would like to have back.  The days that I want to re-ingest are in folders such as:  /nsm/zeek/logs/2023-06-06/*.log.gz

Is there any way to re-ingest those easily?

If I were to decompress the zeek logs for a given day to another folder and add that location to the paths statement in /opt/so/conf/filebeat/etc/filebeat.yml

Would that work?  So for example to get the "weird" logs back for a given day:

```
- type: filestream
  id: zeek-weird
  paths:
    - /nsm/zeek/logs/current/weird.log
    - /nsm/zeek/logs/re-ingest/weird.log  <==adding this line
  fields:
      module: zeek
      dataset: weird
      category: network
  processors:
  - drop_fields:
      fields: ["source", "prospector", "input", "offset", "beat"]

  fields_under_root: true
  clean_removed: true
  close_removed: false
```

Is there an easier way?

Thanks!
