### DISCUSSION TITLE
where to add xpack.reporting.csv.maxSizeBytes:  in 2.4.30

### DISCUSSION THREAD

**Discussion by pastorlibre** [Security-Onion-Solutions/securityonion#11910] [Unsupported Versions]
I am struggling to find the right place to add xpack.reporting.csv.maxSizeBytes:  to increase the export. I don't see a kibana.yml in the /opt/so/saltstack/default/salt/kibana/etc

**Comment by robbiemarshall** [comment]
You'll need to add that in via the GUI.  You should be able to add it to the Advanced section under Kibana.  So go to the SOC GUI and click on Configuration, then at the top of the page click on Options to turn on advanced configuration.  Now go to Kibana > Config > Advanced and then add in the yaml.  It should look something like this:

```
kibana:
  config:
    xpack:
      reporting:
        csv:
          maxSizeBytes: 20480000 (change this to your desired size)
```
