### DISCUSSION TITLE
Question on supressing alerts

### DISCUSSION THREAD

**Discussion by killmasta93** [Security-Onion-Solutions/securityonion#12378] [Unsupported Versions] [answered]
Hi
Currently i was wondering what the correct way to suppress from a source IP 

i was reading https://docs.securityonion.net/en/2.4/managing-alerts.html#disable-the-alert

as they say suppress but from a specific ID and i want to suppress all from a certain IP 

would it be like this but not sure if thats correct

```
  - suppress:
      gen_id: 1
      track: by_src
      ip: 10.10.3.0/24
```

**Comment by robbiemarshall** [comment]
It would be easier to utilize a Suricata BPF to filter out that IP.  https://docs.securityonion.net/en/2.4/bpf.html

**Comment by killmasta93** [comment]
hi @robbiemarshall  i was reading a bit on the doc you sent me would be something like this?
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/38104486-a44c-431c-be3a-95d22ce7b771)

out of curiosity if i would want to also suppress the alert ET POLICY Cleartext WordPress Login
which has rule UUID 2012843 

would it be something like this 

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/2b05f839-000e-4129-96a8-f6958bbab5df)

**Comment by robbiemarshall** [comment]
In the first picture, you'd want to put that in suricata instead of pcap.  In the second pic, that looks correct.

**Reply by killmasta93** [reply]
hi @robbiemarshall thanks for the reply, in the second picture i added the supress but i keep seeing it 
ex added these two

```
2012843:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
2034771:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24

```

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/8aede34f-37a1-4cc4-9182-df3dba7385ad)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/8127ff31-e589-4138-a207-5169a67e2628)

**Reply by izidood** [reply]
If you want to suppress a suricata rule, its done in:
> suricata
>> threshholding
SIDS.

as i understand, in the sids (disable, enable, modify) section, its only the ID of the rule you put in line pr. line.

**Reply by killmasta93** [reply]
@gitgoodgod thanks for the reply, im trying to add the ID of the rule but im getting this issue 
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/ca79c63d-b969-4580-a0d6-184c50a8e987)

**Reply by izidood** [reply, marked as answer]
when i read my message again i see its a bit missunderstanding.

So this is right. you just put it in the wrong place.
```yaml
2012843:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
2034771:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
      
```
The above needs to go into:
> -> suricata
>> -> thresholding
>>> SIDS
```yaml
2012843:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
2034771:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
      
```

If you want to disable a rule completly, you can simply add the rule.uuid in:

> -> sids
>> -> disabled
2034771

**Reply by killmasta93** [reply]
thank you so much

**Reply by izidood** [reply]
you're welcome m8.

**Reply by killmasta93** [reply]
hi @gitgoodgod  quick question if i want to ignore an ip completely that i currently have that ip using greenbone to scan which creates alerts i assume i would add it on bpf was reading the docs and was wondering if this is correct? 
dont want 85.xx.xx.xx to be neither in the pcap or suricata or zeek

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/44ccb4e6-04dc-4862-b882-9f62cc8f5adf)

**Reply by izidood** [reply]
pretty sure if you ignore the ip in zeek bpf, it won't even bother about the traffic from that ip specific, maybe that's the easiest way ?

Edit:
you might also need to do it Suricata I guess.

but try it out and see if they disappear.

**Reply by killmasta93** [reply]
thanks for the reply, i also added it those 3 but its correct to put not host and the IP? like in the photo?

**Reply by izidood** [reply]
yea it will ignore both in and outgoing traffic.

**Reply by killmasta93** [reply]
so my openvas started to scan and it appear again :( 
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/3a0376ea-c5ef-48a8-a177-774545b64041)

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/0fbe1f05-45fb-4dac-a882-cd1773a3dd00)

**Reply by izidood** [reply]
These alerts that are generated, do they have flowbits in them, i think you can see it in the rule.rule of the alert.
if so, you might want to make suppress on the alerts, thats what iv've done, might be another way. but heres an example anyway.

> -> **suricata**
>> -> **thresholding**
>>> -> **sids**
>>>>
```yaml
2030068: #The Alert Name what ever it might be
  - suppress:
      gen_id: 1
      track: by_src
      ip: x.x.x.x.x
```
If you have more ip's you can simply add an comma and a new ip. or do a whole cidr.

**Reply by killmasta93** [reply]
thanks for the reply, currently in the log it shows 
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/13953629/6b83def7-391a-44c1-8a9b-de2951818583)

but the question is that openVAS triggers a lot of alert names normally i would this if i want to suppress just one alert

**Reply by izidood** [reply]
hmm, i dont know if you can omit the ID so it would look like:
```yaml
suppress:
  - gen_id: 1
    track: by_either
    ip: x.x.x.x
```

**Reply by killmasta93** [reply]
hi @gitgoodgod thanks for the reply, so this would omit the IP completely?

**Reply by izidood** [reply]
try it out, it doesn't give me any errors. you can always remove it again. let me know if it works for you ?

**Reply by killmasta93** [reply]
hey @gitgoodgod thanks so much for the reply, so this is what i got so far in  my SIDs config
as its currently working the suppress for the internal IPs, but for the 85.xx.xx cant seem suppress that ip


```

2012843:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
2034771:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24
2012888:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.3.0/24
2034812:
  - suppress:
      gen_id: 1
      track: by_src
      ip: 192.168.7.0/24,192.168.21.0/24
suppress:
  - gen_id: 1
    track: by_either
    ip: 85.10.xx.xx
```
