### DISCUSSION TITLE
Custom Play for apache.error message field does not match any data

### DISCUSSION THREAD

**Discussion by joachim-zauner-epcom** [Security-Onion-Solutions/securityonion#12393] [2.4]
### Version

2.4.40

### Installation Method

Security Onion ISO image

### Description

other (please provide detail below)

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Meets minimum requirements

### CPU

4

### RAM

16GB

### Storage for /

75

### Storage for /nsm

200

### Network Traffic Collection

tap

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

Hi everyone!

I want a simple play that alerts me every time when the string "ValidateDataException" occures in the error log message field.

My Sigma:

```
title: PHP Parameter ValidateDataException
description: Whenever a get or post parameter in website project is not in a valid format an php exception called  ValidateDataException is thrown
status: experimental
author: Joachim Zauner, epcom
tags:
- attack.discovery
logsource:
  category: webserver
  service: apache
  definition: 'Requirements: Must be able to collect the error log files'
detection:
  selection:
    message|contains: ValidateDataException
  condition: selection
falsepositives:
- unknown
level: low
```

This converts to a yaml file with the "eql" filter
```
- eql: >
   any where message : "*ValidateDataException*"
```

However, the Problem is that no data is found.
If i search through the Hunt Interface for this text i get results.

I tried to search for the date with Kibana dev console without any hits with
```
GET /.ds-logs*/_eql/search
{
  "query": """
    any where message : "*ValidateDataException*"
  """
}
```

and with like:
```
GET /.ds-logs*/_eql/search
{
  "query": """
    any where message like "*ValidateDataException*"
  """
}
```

**BUT if i do** 
```
GET /.ds-logs-*/_search
{
  "query": {
    "match_phrase": {
      "message": "ValidateDataException"
    }
  }
}
```
**i get the hits!**

How can i modify my play so i can find the data with the specified substring in the message field?

Thank you, best regards
Joachim

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.

**Comment by reyesj2** [comment]
What about using keywords condition? 
```
detection:
    keywords:
        - 'ValdateDataException'
    condition: keywords
```
