### DISCUSSION TITLE
Set up ElastAlert without Playbook

### DISCUSSION THREAD

**Discussion by davidjud** [Security-Onion-Solutions/securityonion#12486] [2.4]
### Version

2.4.40

### Installation Method

Security Onion ISO image

### Description

upgrading

### Installation Type

Standalone

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

4

### RAM

20

### Storage for /

200

### Storage for /nsm

100

### Network Traffic Collection

span port

### Network Traffic Speeds

1Gbps to 10Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

Hi everyone,

I am currently trying to configure ElastAlert to send a email, whenever there is a alert with the catagory high or medium. But as I was looking up how to do so, I got quite confused because of the SO-Playbook. I don't want to create a Playbook, but just want elastAlert to send emails whenever a speceific alert is shown in the normal Alert section of the SOC.
Is there any possibily to configure SO that way or is it necessary for elastAlert to have a Playbook?

Thanks in advance! 

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.

**Comment by cm-ops** [comment]
You could try and run https://docs.securityonion.net/en/2.4/elastalert.html#so-elastalert-create to create just the Elastalert rule.

**Comment by DebianGuru** [comment]
How about making a file /opt/so/rules/elastalert/email-alert.yaml and modify the bottom 3 lines to suite your environment and possibly add  '- "medium" ' uner the blacklist: key? This worked for me in 2.3 before I needed a more elegant solution.
```
name: email-alert
type: blacklist
es_host: securityonion
es_port: 9200
index: "*:so-*"

compare_key:
- "event.severity_label"
blacklist:
- "high"

realert:
  minutes: 0

alert:

realert:
  minutes: 0

alert:
- "email"
email:
- "recipient@domain.local"
smtp_host: "mail.domain.local"
smtp_port: 25
from_addr: "elastalert@domain.local"
```
