### DISCUSSION TITLE
Option to enable/disable components in CLI rather than SOC?

### DISCUSSION THREAD

**Discussion by ghost** [Security-Onion-Solutions/securityonion#12589] [2.4] [answered]
### Version

2.4.50

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

N/A

### RAM

N/A

### Storage for /

N/A

### Storage for /nsm

N/A

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

No, one or more services are failed (please provide detail below)

### Salt Status

Yes, there are salt failures (please provide detail below)

### Logs

Yes, there are additional clues in /opt/so/log/ (please provide detail below)

### Detail

Hi there. I've disabled Kratos within the Security Onion Console which seems to have broken the SOC. Nginx 500 errors are present when attempting to load the SOC in a browser, and 3 errors which seem to be related to Kratos can be seen when running so-soc-restart: 

----------
          ID: sync_es_users
    Function: cmd.run
        Name: so-user sync
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     http: wait_for_kratos
     Started: 21:02:36.281922
    Duration: 0.003 ms
     Changes:
----------
          ID: socusersroles
    Function: file.exists
        Name: /opt/so/conf/soc/soc_users_roles
      Result: False
     Comment: One or more requisite failed: manager.sync_es_users.sync_es_users
     Started: 21:02:36.866157
    Duration: 0.003 ms
     Changes:
----------
          ID: so-soc
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: soc.config.socusersroles
     Started: 21:02:37.712594
    Duration: 0.004 ms
     Changes:

I'm attempting to run SO in a distributed deployment using an external SIEM provider, so I do not need a lot of the components that are enabled by default both in the manager and sensors. Example: Elasticsearch, Logstash, Kibana. My mistake of disabling Kratos (having not understood what it was beforehand) seems to have cost me access to the SOC. My questions follow:

- Are there methods to enable or disable components in the manager's terminal rather than SOC if we've lost access? 
- If so, how can I enable Kratos once more and is the process the same for other components?

Thank you!

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.

**Comment by petiepooo** [comment]
Look for a file in /opt/so/saltstack/local/pillar/minions/ with a .sls extension and a kratos: section in it.  I don't have access to my lab now so I can't say exactly, but there's an enabled: section, I think, that would have been set to False by the SOC GUI.  You'll want to change that to True.

**Comment by ghost** [comment]
Hi petiepoo, thanks for the assist. I found two files in this directory:
* `adv_<name_of_manager>_manager.sls`: Empty file
* `<name_of_manager>_manager.sls`: File does contain enabled states but I only see unrelated components

```
elastic_fleet_package_registry:
    enabled: true
elasticfleet:
    config:
        server:
            endpoints_enrollment: redacted
            es_token: redacted
            grid_enrollment_general: redacted
            grid_enrollment_heavy: redacted
    enabled: true
elasticsearch:
    esheap: 12149m
host:
    mainint: redacted
    mainip: redacted
idstools:
    enabled: true
logstash:
    config:
        pipeline_x_workers: 8
    settings:
        lsheap: 1000m
mysql:
    enabled: true
nginx:
    enabled: true
registry:
    enabled: true
sensoroni:
    config:
        analyze:
            enabled: true
        node_description: ""
    enabled: true
soc:
    enabled: true
```
Are items removed from this file if they are considered disabled? If so, maybe I just need to add:
```
kratos:
    enabled: true
```
Apologies if I'm overlooking any crucial documentation here but the 2.4 docs only seem to mention the SOC is the way to manage items. I seem to remember older versions giving the file paths for salt files and info on how to manage them. Understood if it's not supported in 2.4 but I've locked myself out of a multi-node cluster where the sensors still need to be reviewed and accepted in the SOC. The only paths forward that I can see are either finding a way to re-enable Kratos in a salt file somewhere or reinstall the manager and all sensors (unless sensors can join a new manager after installation and configuration?).
