### DISCUSSION TITLE
Hung on command during update

### DISCUSSION THREAD

**Discussion by DrOnionMaster** [Security-Onion-Solutions/securityonion#12783] [Unsupported Versions]
Hey all,

I am running into an issue where I am getting hung on a command after running `soup`

The command I keep getting hung on is:

`[INFO    ] Executing command '/usr/sbin/so-influxdb-manage' in directory '/root'`

When I run this command independently from the update script it works fine, but it keeps hanging in the update.

Not sure if there is a fix for this, if not I'd like to edit the soup commands so that it skips this command during the update. The problem is I have no idea where this command is called / where the update script is located.

I'm confused why it even needs to run this command as the usage is:

Supported Operations:
  dashboardpath  Returns the URL path for a dashboard, requires: <name-of-dashboard>
  export         Exports all templates to stdout
  setup          Loads all templates and creates all required buckets
  userlist       Lists users
  useradd        Adds a new user, requires: <email>
  userdel        Removes an existing user, requires: <email>
  userenable     Enables a user, requires: <email>
  userdisable    Disables a user, requires: <email>
  userpass       Updates a user's password, requires: <email>
  userpromote    Promotes a user to admin: <email>
  userdemote     Demotes a user from admin: <email>

If these are all the functions, then why does it need to run during soup??

**Comment by DrOnionMaster** [comment]
Another update:

I've tried editing the script within the 'so-influxdb-manage' file to contain only:
`#!/bin/bash`
`exit 0`

And then tried running soup again hoping it would exit the command and continue with the script, however this did not work and I am still hung on the command.

**Comment by DrOnionMaster** [comment]
Update: I was able to get through the update.

The problem I've found is within the call to `salt \* state.highstate`



 ID: influxdb-setup
    Function: cmd.run
        Name: /usr/sbin/so-influxdb-manage setup &>> /opt/so/log/influxdb/setup.log
      Result: False
     Comment: Command "/usr/sbin/so-influxdb-manage setup &>> /opt/so/log/influxdb/setup.log" run
     Started: 19:38:12.399766
    Duration: 302493.461 ms
     Changes:
              ----------
              pid:
                  83801
              retcode:
                  1
              stderr:
              stdout:
          ID: metrics_link_file
    Function: cmd.run
        Name: so-influxdb-manage dashboardpath "Security Onion Performance" > /opt/so/saltstack/local/salt/influxdb/metrics_link.txt
      Result: False
     Comment: Command "so-influxdb-manage dashboardpath "Security Onion Performance" > /opt/so/saltstack/local/salt/influxdb/metrics_link.txt" run
     Started: 19:43:15.145821
    Duration: 301277.019 ms
     Changes:
              ----------
              pid:
                  103999
              retcode:
                  1
              stderr:
                  Thu Apr 11 19:43:15 UTC 2024 | so-influxdb-manage | Server does not appear to be running or fully initialized - will try again in 10 seconds (1 / 30)

**Reply by DrOnionMaster** [reply]
I am also getting the following error in influxdb.log

"http: TLS handshake error from 127.0.0.1:49378: EOF" log_id=0o5f0DvW000 service=http"

**Reply by cm-ops** [reply]
If you run `sudo so-checkin` does it complete or still hang?

**Reply by DrOnionMaster** [reply]
If we stay rolled back, everything is fine. If we update, then we still get hung.

**Reply by cm-ops** [reply]
I have those errors in my influxdb log and I don't see any issues with the service. How long have you let the command sit in that state? 

```
influxdb-setup:
  cmd.run:
    - name: /usr/sbin/so-influxdb-manage setup &>> /opt/so/log/influxdb/setup.log
    - require:
      - file: influxdbbucketsconf
      - file: influxdb_curl_config
      - docker_container: so-influxdb

metrics_link_file:
  cmd.run:
    - name: so-influxdb-manage dashboardpath "Security Onion Performance" > /opt/so/saltstack/local/salt/influxdb/metrics_link.txt
    - require:
      - docker_container: so-influxdb
```
That seems to be where you are getting stuck, if you get to that state, check to see if the container is running.
