### DISCUSSION TITLE
Please check my YAML rules to suppress Suricata alerts

### DISCUSSION THREAD

**Discussion by Green-Pool** [Security-Onion-Solutions/securityonion#12872] [2.4] [answered]
### Version

2.4.60

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Standalone

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

12

### RAM

64GB

### Storage for /

200GB

### Storage for /nsm

2TB

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

Yes, there are additional clues in /opt/so/log/ (please provide detail below)

### Detail

Additional information:
- Host server: Dell R630, 1x E5-2699v3 18C/36T 2.3GHz 128GB Ram
- Host operating system: Linux Mint with Oracle Virtual Box as VM Host
- VM1: SO Standalone.  12 cores.  64GB RAM (58% in use).  200GB hard disk for SO and 2TB for data storage
- VM2. SO Intrusion Detection Honeypot. 2 cores.  2GB RAM (54% in use).  100GB disk space
- VM3. SO Forward sensor.  4 cores. 12GB RAM (48% in use).  200GB disk space
- Endpoints: Five desktops with endpoint agents (mix of Windows and Linux)

/opt/so/log/suricata/ 
1 rule files processes. 36850 rules successfully loaded.  0 rules failed.
_**Threshold config parsed: 0 rules(s) found**_

My installation is intended as a self-paced learning exercise.  Installed on my home network with 43 client devices (desktops, phones, tv, IoT, security cameras, etc).  Primary upstream network security is provided by Ubiquiti.

As it is a home network, some of the alerts can be suppressed.  For example, rule.uuid, 2027397, “ET POLICY Spotify P2P Client”.

In idstools.sids.modify, I have added the following YAML rule;

```
# Suppress Spotify warnings
2027397:
  - suppress:
      gen_id: 1
      track: by_either
      ip: 192.168.0.0/16
```

However, Suricata is still generating alerts for this rule.  Note the extract from the log (above) "Threshold config parsed: 0 rules(s) found"

I have also tried completely disabling the rule in idstools.sids.disable and this does **not** suppress alert generation for me either.

```
2048911
2018904
2027397
```

I suspect that the problem is the formatting of my YAML rules.  Could someone please have a look at my modified rules for me?

In the dumb questions list; 
Q1. I assume that I can include comments in my YAML rules (just to keep track of which modification is doing what?
Q2. For the idstools.sids.disable, it is just rule numbers?

Here is a slightly expanded extract of my YAML rules.

```
# Suppress Spotify warnings
2027397:
  - suppress:
      gen_id: 1
      track: by_either
      ip: 192.168.0.0/16
# Supress Android connectivity check on TV VLAN
2036220:
  - suppress:
      gen_id: 1
      track: by_either
      ip: 192.168.4.0/24
# Suppress QUAD 9 rules as we are directing traffic to QUAD 9
2048911:
  - suppress:
      gen_id: 1
      track: by_either
      ip: 149.112.112.112
# Suppress QUAD 9 rules as we are directing traffic to QUAD 9
2048911:
  - suppress:
      gen_id: 1
      track: by_either
      ip: 9.9.9.9
```

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
