### DISCUSSION TITLE
SSL/cert problems

### DISCUSSION THREAD

**Discussion by izidood** [Security-Onion-Solutions/securityonion#13110] [2.4]
### Version

2.4.70

### Installation Method

Security Onion ISO image

### Description

upgrading

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

8

### RAM

32

### Storage for /

100GB

### Storage for /nsm

500GB

### Network Traffic Collection

span port

### Network Traffic Speeds

1Gbps to 10Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

Yes, there are salt failures (please provide detail below)

### Logs

No, there are no additional clues

### Detail

Hey, i have some problems with ssl/certs.
i ran a salt '*' state.highstate command and got a bunch of different errors.
im sure theres something in logs, but i dont know what exact logs i need to share from this, or this might be something that is an easy fix perhaps just from this output. i hope someone can help.

```yaml
sudo salt \* state.highstate

----------
          ID: conf_filebeat_key
    Function: x509.private_key_managed
        Name: /opt/so/conf/filebeat/etc/pki/filebeat.key
      Result: False
     Comment: One or more requisite failed: ssl.conf_filebeat_crt
     Started: 06:17:09.279066
    Duration: 0.007 ms
     Changes:

----------
          ID: conf_filebeat_crt
    Function: x509.certificate_managed
        Name: /opt/so/conf/filebeat/etc/pki/filebeat.crt
      Result: False
     Comment: ca_server did not respond. Salt master must permit peers to call the sign_remote_certificate function.
     Changes:

----------
          ID: filebeatpkcs
    Function: cmd.run
        Name: /usr/bin/openssl pkcs8 -in /opt/so/conf/filebeat/etc/pki/filebeat.key -topk8 -out /opt/so/conf/filebeat/etc/pki/filebeat.p8 -passout pass:
      Result: False
     Comment: One or more requisite failed: ssl.conf_filebeat_key
     Started: 06:17:09.279993
    Duration: 0.002 ms
     Changes:

----------
          ID: influxdb_key
    Function: x509.private_key_managed
        Name: /etc/pki/influxdb.key
      Result: False
     Comment: One or more requisite failed: ssl.influxdb_crt
     Started: 06:17:40.741407
    Duration: 0.008 ms
     Changes:

----------
          ID: influxdb_crt
    Function: x509.certificate_managed
        Name: /etc/pki/influxdb.crt
      Result: False
     Comment: ca_server did not respond. Salt master must permit peers to call the sign_remote_certificate function.
     Changes:

----------
          ID: so-telegraf
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: ssl.influxdb_crt, ssl.influxdb_key
     Started: 06:18:29.521900
    Duration: 0.004 ms
     Changes:

----------
          ID: redis_key
    Function: x509.private_key_managed
        Name: /etc/pki/redis.key
      Result: False
     Comment: One or more requisite failed: ssl.redis_crt
     Started: 06:18:22.386146
    Duration: 0.005 ms
     Changes:

----------
          ID: redis_crt
    Function: x509.certificate_managed
        Name: /etc/pki/redis.crt
      Result: False
     Comment: ca_server did not respond. Salt master must permit peers to call the sign_remote_certificate function.
     Changes:

----------
          ID: so-redis
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: ssl.redis_crt, ssl.redis_key
     Started: 06:19:37.851218
    Duration: 0.003 ms
     Changes:

When its done i also get this message: 
Error: Minions returned with non-zero exit code
```

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
