### DISCUSSION TITLE
Alert Tuning Status Mismatch (Says Disabled, but is Enabled)

### DISCUSSION THREAD

**Discussion by corycandia** [Security-Onion-Solutions/securityonion#13248] [2.4]
### Version

2.4.70

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Meets minimum requirements

### CPU

4

### RAM

16

### Storage for /

100

### Storage for /nsm

200

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

Perhaps I am doing something wrong?  I keep getting alerted for something I want to disable and shows disabled.   Detections is the way to do it now, instead of config/idstools/sids/disabled, but that already shows disabled.

I find an alert for a rule (2030387) I'd like to disable.
![Alert-ScreenShot](https://github.com/Security-Onion-Solutions/securityonion/assets/88662234/23ac11a2-f00f-4a9f-99ea-0464d5eabeac)

I use the tuning pivot, and the new Detections module shows me its status is 'disabled'.
![Det-ScreenShot](https://github.com/Security-Onion-Solutions/securityonion/assets/88662234/3d02ca20-8cf7-43bc-9a74-bf2058bde76d)

I check the rules file ```/opt/so/rules/nids/suri/all.rules``` and it shows enabled (not #).  Maybe this doesn't matter because it's now where Detections pulls its status.
![rules-file-screenshot](https://github.com/Security-Onion-Solutions/securityonion/assets/88662234/40a941b8-86e2-4c07-8a14-8c72f94dd11e)

Maybe this is my fault because (prior to the 2.4.7 update), this is my ```/opt/so/saltstack/local/pillar/idstools/soc_idstools.sls```:

```
idstools:
    sids:
        disabled:
            - re:ET INFO
            - "2030387"
            - "2009208"
            - "2009207"
        enabled:
            - re:ET MALWARE
            - re:GPL MALWARE
            - re:ET EXPLOIT
            - re:ET EXPLOIT_KIT
            - re:ET MOBILE_MALWARE
            - re:ET ADWARE_PUP
            - re:ET WEB_SERVER
            - re:ET ATTACK_RESPONSE
            - re:GPL EXPLOIT
            - re:GPL WEB_SERVER
            - re:GPL ATTACK_RESPONSE
            - re:ET ATTACK_RESPONSE
            - "2027237"
        modify:
            - 2024699 "flowbits" "noalert; flowbits"
            - 2025303 "flowbits" "noalert; flowbits"
            - 2024693 "flowbits" "noalert; flowbits"
```

Do I need to remove the previous config information from the soc_idstools.sls file and start over with them in detections?

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
