### DISCUSSION TITLE
Detection Filter not being followed

### DISCUSSION THREAD

**Discussion by DrOnionMaster** [Security-Onion-Solutions/securityonion#13269] [2.4] [answered]
### Version

2.4.80

### Installation Method

Security Onion ISO image

### Description

other (please provide detail below)

### Installation Type

Distributed

### Location

cloud

### Hardware Specs

Exceeds minimum requirements

### CPU

24

### RAM

30GB

### Storage for /

2TB

### Storage for /nsm

2TB

### Network Traffic Collection

tap

### Network Traffic Speeds

1Gbps to 10Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

I am having a problem where the sigma filter that already comes with the rule is not being followed. This is happening with a few other rules but the one that is really annoying me is the "Active Directory Replication from Non Machine Account".

```
title: Active Directory Replication from Non Machine Account
id: 17d619c1-e020-4347-957e-1d1207455c93
status: test
description: Detects potential abuse of Active Directory Replication Service (ADRS) from a non machine account to request credentials.
references:
    - https://threathunterplaybook.com/hunts/windows/180815-ADObjectAccessReplication/notebook.html
    - https://threathunterplaybook.com/library/windows/active_directory_replication.html
    - https://threathunterplaybook.com/hunts/windows/190101-ADModDirectoryReplication/notebook.html
author: Roberto Rodriguez @Cyb3rWard0g
date: 2019/07/26
modified: 2021/11/27
tags:
    - attack.credential_access
    - attack.t1003.006
logsource:
    product: windows
    service: security
detection:
    selection:
        AccessMask: "0x100"
        EventID: 4662
        Properties|contains:
            - 1131f6aa-9c07-11d1-f79f-00c04fc2dcd2
            - 1131f6ad-9c07-11d1-f79f-00c04fc2dcd2
            - 89e95b76-444d-4c62-991a-0facbeda640c
    filter:
        - SubjectUserName|endswith: $
        - SubjectUserName|startswith: MSOL_
    condition: selection and not filter
fields:
    - ComputerName
    - SubjectDomainName
    - SubjectUserName
falsepositives:
    - Unknown
level: critical
```

As you can see this detection should be filtering out any alerts that have a SubjectUserName that starts with 'MSOL_' or ends with '$'. However, I am still getting 1,000's of alerts for account in my environment that start with 'MSOL_' and end with '$'.

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/161877865/2b292822-a6e6-4048-ba1c-884944552115)

I even tried creating a custom filter to mimic the filter already in the YAML and it still didn't filter these out when I was testing it with the console in elastic. 

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
