### DISCUSSION TITLE
PCAP stuck on pending (SO running behind Firewall --> NAT)

### DISCUSSION THREAD

**Discussion by Sidhy** [Security-Onion-Solutions/securityonion#13306] [Unsupported Versions] [answered]
Hi,

I have read through many of the PCAP stuck on pending discussions but did not find the answer / fix for my situation.

I am running SO behind another firewall (pfsense) where I route my traffic using NAT, when I want to inspect the PCAP file from an alert it stays on pending.

I have checked the /nsm/pcap folder and confirmed the PCAP files are present.

In the  /opt/so/log/sensoroni/sensoroni.log file it is filled with the below entry:

```log
{"fields":{"error":"Post \"https://10.6.0.2/sensoroniagents/api/node\": dial tcp 10.6.0.2:443: connect: connection timed out"},"level":"warn","timestamp":"2024-07-04T19:06:02.173125494Z","message":"Failed to submit request"}
{"fields":{"error":"Post \"https://10.6.0.2/sensoroniagents/api/node\": dial tcp 10.6.0.2:443: connect: connection timed out"},"level":"warn","timestamp":"2024-07-04T19:06:02.173192096Z","message":"Failed to poll for pending jobs"}
```

Firewall IP 10.6.0.2
NAT traffic: 10.6.0.2:443 --> 10.6.2.34:443

Web interface is working fine, I had to manually update the /opt/so/saltstack/local/pillar/global/soc_global.sls file to match the firewall ip to make this work

```yml
global:
  soversion: '2.4.70'
  managerip: '10.6.2.34'
  mdengine: 'ZEEK'
  ids: 'Suricata'
  url_base: '10.6.0.2'
  airgap: False
  imagerepo: 'security-onion-solutions'
  pipeline: 'redis'
  repo_host: 'seconion'
  influxdb_host: 'seconion'
  registry_host: 'seconion'
  endgamehost: ''
````

Anyone has advice on solving the issue ?
