### DISCUSSION TITLE
Declare new VAR and use it in HOME_NET

### DISCUSSION THREAD

**Discussion by Carlos-mb** [Security-Onion-Solutions/securityonion#13456] [2.4] [answered]
### Version

2.4.90

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

6

### RAM

64

### Storage for /

300

### Storage for /nsm

300

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

Hello. 

I'm trying to add my external IP as HOME_IP. Since my IP is dynamic, I created a new variable called "DYNIP" to store it (e.g., 99.99.99.99). However, Suricata fails to start after this change.

The output from "docker logs so-suricata" shows the following error:

`i: suricata: This is Suricata version 7.0.6 RELEASE running in SYSTEM mode
E: detect: failed to parse address "9"
E: detect: failed to parse address var "DYNIP" with value "9". Please check its syntax
E: suricata: basic address vars test failed. Please check /etc/suricata/suricata.yaml for errors`

I've noticed that in the /etc/suricata/suricata.yaml file, the value of DYNIP is truncated to its first character:

```
 address-groups:
    HOME_NET: '[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]'
    DYNIP: '9'
```

I've tried various formats for the DYNIP value (e.g., 99.99.99.99/32, "99.99.99.99/32", '99.99.99.99/32', [99.99.99.99/32], "[99.99.99.99/32]") but the issue persists.

And the result is always the same, only the 1st character appears in the yaml file. 

The second problem I'm facing is that 

I'd like to use the var DYNIP in HOME_NET. But when I try to do it using web interface, it reports the error than only allows IP addresses. I tested it in other adddress-groups and it worked fine, I can mix IPs and Vars but HOME_NET doesn't

My three questions are:

1- What am I doing wrong when declaring the var DYNIP to store the external IP
2- Is it possible to include a variable within the HOME_NET address group?
3- And... Has anyone else encountered similar issues when setting a dynamic IP as a local network IP and using it for rule tuning and address group configuration?
4- How can I delete the var DYNIP. There is an option to create it but, How do I delete it while I fix the problem, because Suricata is nor working !!!

Thank you very much.

**EDIT 1:** The variables are created in /opt/so/saltstack/local/pillar/suricata/soc_suricata.sls. Editing the file I can delete the vars and... I have seen that the new vars were created this way:

```
suricata:
    config:
        vars:
            address-groups:
                HOME_NET:
                    - 192.168.0.0/16
                    - 10.0.0.0/8
                    - 172.16.0.0/12
                DYNIP: 79.146.65.183/32
```
If I delete the DYNIP line, Suricata starts correctly. 
I have also tried to use the SOC interface to add a second IP to DYNIP, then I get this:

```
suricata:
    config:
        vars:
            address-groups:
                HOME_NET:
                    - 192.168.0.0/16
                    - 10.0.0.0/8
                    - 172.16.0.0/12
                DYNIP:
                    - 99.99.99.99/32
                    - 99.99.99.99/32
```
As you can see, it's a different format. 
If I delete the second IP, the result is:

```
suricata:
    config:
        vars:
            address-groups:
                HOME_NET:
                    - 192.168.0.0/16
                    - 10.0.0.0/8
                    - 172.16.0.0/12
                DYNIP:
                    - 99.99.99.99/32
```

And Suricata starts correctly.

Could this be a bug? If you create a Variable with a single IP the format in sls file is wrong? The workaround will be create the var with 2 IPs, save it, edit it and remove the second one. 

Now I have to check if the new var is usable in rule tunning. I still doesn't know how to add it to HOME_NET

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
