### DISCUSSION TITLE
Using suricata variables in suricata BPF?

### DISCUSSION THREAD

**Discussion by ejgh-oe** [Security-Onion-Solutions/securityonion#13592] [Unsupported Versions] [answered]
BPF for suricata allows to filter traffic so it doesn't get handled by suricata at all (https://docs.securityonion.net/en/2.4/bpf.html).

My problem: I've got to filter out traffic to around 80 (!) IP-addresses and a specific destination port. 

Writing this in plain BPF would result in a giant BPF expression that given the complexity/length would be prone to all sorts of errors. 

My idea was to split the problem into two: Define those 80 hoss in a single suricata variable (`Administration > Configuration > (Show all configurable settings) > Suricata > Advanced`) and then refer to this variable in a suricata BPF expression.

So, something like

```
suricata:
  config:
    vars:
      address-groups:
        IGNORE_NODES: 
          - 192.168.44.11
          - 192.168.19.118
          - 192.168.56.119
...
```
for the variable definition and then write the BPF expression as

```
not dst port 12345 && not dst $IGNORE_NODES
```

Is this possible or is the BPF configuration for suricata limited to simple BPF expressions (i.e. IP addresses, ports, but no variables)?
