### DISCUSSION TITLE
2.4.110 upgrade - so-elastic-fleet-integration-upgrade errors

### DISCUSSION THREAD

**Discussion by revast** [Security-Onion-Solutions/securityonion#13786] [2.4] [answered]
### Version

2.4.110

### Installation Method

Security Onion ISO image

### Description

upgrading

### Installation Type

Standalone

### Location

on-prem with Internet access

### Hardware Specs

Meets minimum requirements

### CPU

4

### RAM

31

### Storage for /

300

### Storage for /nsm

600

### Network Traffic Collection

tap

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

Yes, there are Failures

### Logs

Yes, there are additional clues in /opt/so/log/ (please provide detail below)

### Detail

SecOnion upgrade to 2.4.110 from 2.4.90 - 3 Different Installations with same specs - all show different error at so-elastic-fleet-integration-upgrade

1rst machine:

```
Summary for local
--------------
Succeeded: 874 (changed=89)
Failed:      1
--------------
...

Soup failed with error 1: Unhandled error
Unhandled error occured, please check /root/soup.log for details.
```

```
 ID: so-elastic-fleet-integration-upgrade                                                                                                                                       
    Function: cmd.run                                                                                                                                                            
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade                                                                                                                     
      Result: False                                                                                                                                                              
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run                                                                                                       
     Started: 09:34:15.286869                                                                                                                                                    
    Duration: 14189.327 ms                                                                                                                                                       
     Changes:                                                                                                                                                                    
              ----------                                                                                                                                                         
              pid:                                                                                                                                                               
                  769427                                                                                                                                                         
              retcode:                                                                                                                                                           
                  1                                                                                                                                                              
              stderr:                                                                                                                                                            
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                
                                                   Dload  Upload   Total   Spent    Left  Speed                                                                                                                                                                                                                                      
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                 
                  100    74    0     0  100    74      0     61  0:00:01  0:00:01 --:--:--    61                                                                                 
                  100    74    0     0  100    74      0     33  0:00:02  0:00:02 --:--:--    33                                                                                 
                  100    74    0     0  100    74      0     23  0:00:03  0:00:03 --:--:--    23                                                                                 
                  100   166  100    92  100    74     22     18  0:00:04  0:00:04 --:--:--    40                                                                                 
                  100   166  100    92  100    74     22     18  0:00:04  0:00:04 --:--:--    40                                                                                 
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                      
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                      
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                      
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                      
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"                                                                                          
              stdout:                                                                                                                                                            
                  Current fortinet_fortigate package version (1.19.0) is not the same as the latest available package (1.25.4)...                                                
                  Upgrading fortinet_fortigate-1...                                                                                                                              
                  Starting dry run...                                                                                                                                            
                  No errors detected. Proceeding with upgrade...                                                                                                                 
                  [{"id":"b8a19fbf-472c-4b66-9372-b02baf7ae07f","name":"fortinet_fortigate-1","success":true}]Current Error: Failed to  
                  retrieve package name for  'Error: Failed to retrieve integrations for 'FortiGate'.' in 'FortiGate'. package version for 
                  'Error: Failed to retrieve integrations for 'FortiGate'.' in 'FortiGate'.) is not the same as the latest available package ()..`
                  
                  Upgrading Error: Failed to retrieve integrations for FortiGate....                                                                                           
                  Starting dry run...                                                                                                                                            
                  Errors detected during dry run. Stopping upgrade...      
                  
```
                  
```
 sudo salt-call state.highstate


Succeeded: 874 (changed=37)
Failed:      1

----------
          ID: so-elastic-fleet-integration-upgrade
    Function: cmd.run
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade
      Result: False
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run
     Started: 10:54:04.734387
    Duration: 8921.047 ms
     Changes:
              ----------
              pid:
                  1089135
              retcode:
                  1
              stderr:
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"
              stdout:
                  Current Error: Failed to retrieve package name for 'Error: Failed to retrieve integrations for 'FortiGate'.' in 'FortiGate'. package version (Error: Failed to retrieve package version for 'Error: Failed to retrieve integrations for 'FortiGate'.' in 'FortiGate'.) is not the same as the latest available package ()...
                  Upgrading Error: Failed to retrieve integrations for 'FortiGate'....
                  Starting dry run...
                  Errors detected during dry run. Stopping upgrade...
----------


```

2nd machine:

```
----------                                                                                                                                                                   
          ID: so-elastic-fleet-integration-upgrade                                                                                                                           
    Function: cmd.run                                                                                                                                                        
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade                                                                                                                 
      Result: False                                                                                                                                                          
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run                                                                                                   
     Started: 10:31:04.153631                                                                                                                                                
    Duration: 12859.275 ms                                                                                                                                                   
     Changes:                                                                                                                                                                
              ----------                                                                                                                                                     
              pid:                                                                                                                                                           
                  616585                                                                                                                                                     
              retcode:                                                                                                                                                       
                  1                                                                                                                                                          
              stderr:                                                                                                                                                        
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                  
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                  
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                  
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                  
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"                                                                                      
              stdout:                                                                                                                                                        
                  Current Error: Failed to retrieve package name for 'Error: Failed to retrieve integrations for 'endpoints-linux'.' in 'endpoints-linux'. package version (Error: Failed to retrieve package version for 'Error: Failed to retrieve integrations 
			   for 'endpoints-linux'.' in 'endpoints-linux'.) is not the same as the latest available package ()
                  Upgrading Error: Failed to retrieve integrations for 'endpoints-linux'....                                                                                 
                  Starting dry run...                                                                                                                                        
                  Errors detected during dry run. Stopping upgrade...                                                                                                        
----------    
```

```
sudo salt-call state.highstate                                                          
----------
          ID: so-elastic-fleet-integration-upgrade
    Function: cmd.run
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade
      Result: False
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run
     Started: 11:33:26.024439
    Duration: 11690.611 ms
     Changes:
              ----------
              pid:
                  872830
              retcode:
                  1
              stderr:
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"
              stdout:
                  Current Error: Failed to retrieve package name for 'Error: Failed to retrieve integrations for 'endpoints-linux'.' in 'endpoints-linux'. package version (Error: Failed to retrieve package version for 'Error: Failed to retrieve integrations for 'endpoints-linux'.' in 'endpoints-linux'.) is not the same as the latest available package ()...
                  Upgrading Error: Failed to retrieve integrations for 'endpoints-linux'....
                  Starting dry run...
                  Errors detected during dry run. Stopping upgrade...
----------
```
               
3rd machine:

```
----------                                                                                                                                                                                
          ID: so-elastic-fleet-integration-upgrade                                                                                                                                        
    Function: cmd.run                                                                                                                                                                     
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade                                                                                                                              
      Result: False                                                                                                                                                                       
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run                                                                                                                
     Started: 10:46:44.965897                                                                                                                                                             
    Duration: 23198.814 ms                                                                                                                                                                
     Changes:                                                                                                                                                                             
              ----------                                                                                                                                                                  
              pid:                                                                                                                                                                        
                  1280754                                                                                                                                                                 
              retcode:                                                                                                                                                                    
                  1                                                                                                                                                                       
              stderr:                                                                                                                                                                     
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                         
                                                   Dload  Upload   Total   Spent    Left  Speed                                                                                           
                                                                                                                                                                                          
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                          
                  100    74    0     0  100    74      0     61  0:00:01  0:00:01 --:--:--    61                                                                                          
                  100    74    0     0  100    74      0     33  0:00:02  0:00:02 --:--:--    33                                                                                          
                  100    74    0     0  100    74      0     23  0:00:03  0:00:03 --:--:--    23                                                                                          
                  100    74    0     0  100    74      0     17  0:00:04  0:00:04 --:--:--    17                                                                                          
                  100   155  100    81  100    74     19     17  0:00:04  0:00:04 --:--:--    36                                                                                          
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                               
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                               
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                               
                  jq: error (at <stdin>:0): Cannot iterate over null (null)                                                                                                               
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"                                                                                                   
              stdout:                                                                                                                                                                     
                  Current pfsense package version (1.16.0) is not the same as the latest available package (1.19.1)...                                                                    
                  Upgrading pfsense-1...                                                                                                                                                  
                  Starting dry run...                                                                                                                                                     
                  No errors detected. Proceeding with upgrade...                                                                                                                          
                  [{"id":"d3546b32-6892-440c-8bbf-bf046c12d847","name":"pfsense-1","success":true}]Current Error: Failed to retrieve 
				  package name for 'Error: Failed to retrieve integrations for 'Linux-Web'.' in 'Linux-Web'. package version (Error: 
				  Failed to retrieve package version for 'Error: Failed to retrieve integrations for 'Linux-Web'.' in 'Linux-Web'.) 
				  is not the same as the latest available package ()...
				  
                  Upgrading Error: Failed to retrieve integrations for 'Linux-Web'....                                                                                                    
                  Starting dry run...                                                                                                                                                     
                  Errors detected during dry run. Stopping upgrade...                                                                                                                     
----------
```

```
sudo salt-call state.highstate    
----------
          ID: so-elastic-fleet-integration-upgrade
    Function: cmd.run
        Name: /usr/sbin/so-elastic-fleet-integration-upgrade
      Result: False
     Comment: Command "/usr/sbin/so-elastic-fleet-integration-upgrade" run
     Started: 11:45:21.121645
    Duration: 16254.228 ms
     Changes:
              ----------
              pid:
                  1518087
              retcode:
                  1
              stderr:
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:0): Cannot iterate over null (null)
                  jq: error (at <stdin>:1): Cannot index number with string "hasErrors"
              stdout:
                  Current Error: Failed to retrieve package name for 'Error: Failed to retrieve integrations for 'Linux-Web'.' in 'Linux-Web'. package version (Error: Failed to retrieve package version for 'Error: Failed to retrieve integrations for 'Linux-Web'.' in 'Linux-Web'.) is not the same as the latest available package ()...
                  Upgrading Error: Failed to retrieve integrations for 'Linux-Web'....
                  Starting dry run...
                  Errors detected during dry run. Stopping upgrade...
----------

```                                                                           


sudo so-status => green

Firewall-Dashboard:  Fortigate / Pfsense / ... logs still seem to come in.




                  

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
