### DISCUSSION TITLE
so-elastalert Missing from Distributed Installation

### DISCUSSION THREAD

**Discussion by squirtle-turtle** [Security-Onion-Solutions/securityonion#13908] [2.4]
### Version

2.4.110

### Installation Method

Cloud image (Amazon, Azure, Google)

### Description

upgrading

### Installation Type

Distributed

### Location

cloud

### Hardware Specs

Exceeds minimum requirements

### CPU

16

### RAM

65.8 GB

### Storage for /

270.5 GB

### Storage for /nsm

2146.4 GB

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

No, one or more services are failed (please provide detail below)

### Salt Status

Yes, there are salt failures (please provide detail below)

### Logs

Yes, there are additional clues in /opt/so/log/ (please provide detail below)

### Detail

We have a distributed environment, including 2 search nodes and 7 forward nodes. There is a mix of on-premise and cloud forward nodes; search nodes and our manager node are hosted in AWS.

On our manager node, so-elastalert is missing, and the Docker container cannot be found. Manual reinstallation of the Docker container (docker pull) fails. 

The issue first arose on a prior manager node when we spun up and accepted the second search node. We redeployed the manager and the search nodes. It worked for a little while - a couple of hours. The issue repeated itself on the second manager node after we tried to do a scorched-earth rebuild. We reviewed other posts here (anything similar) and didn't have any luck.

The errors we get on the Elastic side are tied to unallocated shards. How can we rectify this?

Errors when running "sudo salt-call state.highstate":
```
[ERROR   ] Command 'so-elasticsearch-wait' failed with return code: 1
[ERROR   ] stdout: Waiting for value 'green open' at 'https://localhost:9200/_cat/indices/.kibana*' (1/300)
Server is not ready
```

```
----------
          ID: so-kibana-dashboard-load
    Function: cmd.run
        Name: /usr/sbin/so-kibana-config-load -i /opt/so/conf/kibana/saved_objects.ndjson.template
      Result: True
     Comment: Command "/usr/sbin/so-kibana-config-load -i /opt/so/conf/kibana/saved_objects.ndjson.template" run
     Started: 05:48:41.377991
    Duration: 15.806 ms
     Changes:   
              ----------
              pid:
                  3780687
              retcode:
                  0
              stderr:
              stdout:
```

```
----------
          ID: elastalert_sbin
    Function: file.recurse
        Name: /usr/sbin
      Result: True
     Comment: Recursively updated /usr/sbin
     Started: 05:48:41.428598
    Duration: 208.07 ms
     Changes:   
              ----------
              /usr/sbin:
                  ----------
                  /usr/sbin:
                      ----------
                      user:
                          933
                  user:
                      933
```

```
----------
          ID: wait_for_elasticsearch
    Function: cmd.run
        Name: so-elasticsearch-wait
      Result: False
     Comment: Command "so-elasticsearch-wait" run
     Started: 05:48:43.129805
    Duration: 324077.949 ms
     Changes:   
              ----------
              pid:
                  3780940
              retcode:
                  1
              stderr:
              stdout:
```

```
----------
          ID: wait_for_elasticsearch
    Function: cmd.run
        Name: so-elasticsearch-wait
      Result: False
     Comment: Command "so-elasticsearch-wait" run
     Started: 05:48:43.129805
    Duration: 324077.949 ms
     Changes:   
              ----------
              pid:
                  3780940
              retcode:
                  1
              stderr:
              stdout:
                  Waiting for value 'green open' at 'https://localhost:9200/_cat/indices/.kibana*' (1/300)
                  Server is not ready
```

Clues in logs:
```
[root@angband onion]# so-elasticsearch-query _cluster/allocation/explain?pretty
{
  "note" : "No shard was specified in the explain API request, so this response explains a randomly chosen unassigned shard. There may be other unassigned shards in this cluster which cannot be assigned for different reasons. It may not be possible to assign this shard until one of the other shards is assigned correctly. To explain the allocation of other shards (whether assigned or unassigned) you must specify the target shard in the request to this API.",
  "index" : ".internal.alerts-ml.anomaly-detection-health.alerts-default-000001",
  "shard" : 0,
  "primary" : false,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "REPLICA_ADDED",
    "at" : "2024-10-28T16:01:16.215Z",
    "last_allocation_status" : "no_attempt"
  },
  "can_allocate" : "throttled",
  "allocate_explanation" : "Elasticsearch is currently busy with other activities. It expects to be able to allocate this shard when those activities finish. Please wait.",
  "node_allocation_decisions" : [
    {
      "node_id" : "IVseaez8RuSyFBehC9qlVw",
      "node_name" : "angband-search-1",
      "transport_address" : "10.x.y.z:9300",
      "node_attributes" : {
        "ml.config_version" : "12.0.0",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0"
      },
      "roles" : [
        "data",
        "data_hot",
        "ingest",
        "transform"
      ],
      "node_decision" : "throttled",
      "store" : {
        "matching_size_in_bytes" : 0
      },
      "deciders" : [
        {
          "decider" : "throttling",
          "decision" : "THROTTLE",
          "explanation" : "reached the limit of incoming shard recoveries [2], cluster setting [cluster.routing.allocation.node_concurrent_incoming_recoveries=2] (can also be set via [cluster.routing.allocation.node_concurrent_recoveries])"
        }
      ]
    },
    {
      "node_id" : "TI0wfNmfS_ORWazF7HQgtg",
      "node_name" : "angband-search-2",
      "transport_address" : "10.b.c.d:9300",
      "node_attributes" : {
        "ml.config_version" : "12.0.0",
        "transform.config_version" : "10.0.0",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_hot",
        "ingest",
        "transform"
      ],
      "node_decision" : "throttled",
      "deciders" : [
        {
          "decider" : "throttling",
          "decision" : "THROTTLE",
          "explanation" : "reached the limit of incoming shard recoveries [2], cluster setting [cluster.routing.allocation.node_concurrent_incoming_recoveries=2] (can also be set via [cluster.routing.allocation.node_concurrent_recoveries])"
        }
      ]
    },
    {
      "node_id" : "1h8ZDdvpQ2qfUlIPIvu9gQ",
      "node_name" : "angband",
      "transport_address" : "10.q.r.s:9300",
      "node_attributes" : {
        "ml.config_version" : "12.0.0",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0"
      },
      "roles" : [
        "data",
        "master",
        "remote_cluster_client",
        "transform"
      ],
      "node_decision" : "no",
      "store" : {
        "matching_size_in_bytes" : 249
      },
      "deciders" : [
        {
          "decider" : "same_shard",
          "decision" : "NO",
          "explanation" : "a copy of this shard is already allocated to this node [[.internal.alerts-ml.anomaly-detection-health.alerts-default-000001][0], node[1h8ZDdvpQ2qfUlIPIvu9gQ], [P], s[STARTED], a[id=oHSk5wjKR52y47HK6-e-8A], failed_attempts[0]]"
        }
      ]
    }
  ]
} 
```

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.
