### DISCUSSION TITLE
Issue Adding Sigma Rules from Local Repo

### DISCUSSION THREAD

**Discussion by jstore-embers** [Security-Onion-Solutions/securityonion#13910] [2.4] [answered]
### Version

2.4.100

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

20

### RAM

64 GB

### Storage for /

2 TB

### Storage for /nsm

12 TB

### Network Traffic Collection

tap

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

I am trying to add a private sigma ruleset offered by the DFIR Report. I can use git to pull the repo down to **/nsm/rules/detect-sigma/repos/dfir-report/** and I've configured the following line in the admin interface under rule repos according to the documentation [here](https://docs.securityonion.net/en/2.4/sigma.html)

**{"community":true,"folder":"rules/rules/sigma","license":"Elastic-2.0","repo":"file:///nsm/rules/detect-sigma/repos/dfir-report"}**

I think the above is correct (not sure what I should put for license, so I copied the option from the securityonion-resources repo. Note the full path to the rules root folder in my instance is **/nsm/rules/detect-sigma/repos/dfir-report/rules/rules/sigma** but there are several subfolders.

I'm wondering where I may find logs that are generated when doing a full-update on the elastalert rules from the detections interface or if there's anything obviously wrong with this config.

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.

**Comment by defensivedepth** [comment]
When you say `pull down` - did you download it or did you git clone it? 

That dir needs to be a git repo. You should be able to run `git status` on the following dir: `/nsm/rules/detect-sigma/repos/dfir-report/`

**Reply by jstore-embers** [reply]
I cloned the repo, but I had the path wrong. The repo is /nsm/rules/detect-sigma/repos/dfir-report/**rules/**

git status shows it has the latest files.

Because the repo is the rules subdirectory, I changed the config from:
{"community":true,"folder":"rules/rules/sigma","license":"Elastic-2.0","repo":"file:///nsm/rules/detect-sigma/repos/dfir-report"}
to
{"community":true,"folder":"**rules/sigma**","license":"Elastic-2.0","repo":"file:///nsm/rules/detect-sigma/repos/dfir-repor/**rules**"}

I kicked off a full update for the elastalert rules. That threw an error and now the SOC interface is down with a bad gateway error and so-status shows so-soc as missing

**Reply by jstore-embers** [reply]
Any idea on how to revert that change from the command line. I assume that's stored in Kratos?

**Reply by defensivedepth** [reply]
Delete this config from the following file, then restart soc: `sudo so-soc-restart --force`

This will set that particular config back to the default.

```
/opt/so/saltstack/local/pillar/soc/soc_soc.sls 
soc:
    config:
        server:
            modules:
                elastalertengine:
                    rulesRepos:
                        default:
                            - community: true
                              folder: sigma/stable
                              license: Elastic-2.0
                              repo: https://github.com/Security-Onion-Solutions/securityonion-resources
                            - community: true
                              folder: sigma/stable
                              license: Elastic-2.0
                              repo: https://github.com/Security-Onion-Solutions/securityonion-resourcess
```
