### DISCUSSION TITLE
How to trigger an alert for sudo execution using detection tab

### DISCUSSION THREAD

**Discussion by sandraimmaculate** [Security-Onion-Solutions/securityonion#14066] [Unsupported Versions]
Hello,
I have installed security onion 2.4 in Rocky Linux 9 with 4 vcpu and 16GB RAM and with 250 root volume. I have created a trigger to raise an alert whenever the sudo command is executed in endpoints where the agents is installed using playbook! and it was working. Now as the playbook was replaced with detection tab i have created same rule in detection tab but i'm not getting the alert why ?? still in the alert tab the alerts are coming from playbook
![image](https://github.com/user-attachments/assets/cc00d358-eaa5-4778-a55a-bdffc9fd1004)
it have to give the alert if the rule got trigger in the endpoint where the elastic agent is installed

**Comment by sandraimmaculate** [comment]
I tried to create a custom rule in /opt/so/rules/elastalert/rules/custom/custom_rulefailedlogin.yaml if i add this path in 
![image](https://github.com/user-attachments/assets/e98b26f0-b124-4746-a730-a9357eeb81b2)
the elastalert status is becoming missing 
![image](https://github.com/user-attachments/assets/8695069c-1eba-4203-9876-bff11340f2fc)
i created a sample rule for testing 
```
name: "Frequent Failed Logins Alert"
type: frequency
index: logs-*
num_events: 5
timeframe:
  minutes: 1
filter:
- term:
    event.action: "failed_login"
alert:
- email
email:
- sandra.immaculate@izmoltd.com
```
