### DISCUSSION TITLE
Index in Elastalert rule to send alert mail

### DISCUSSION THREAD

**Discussion by Cantondy** [Security-Onion-Solutions/securityonion#14093] [Unsupported Versions] [answered]
Hello,

I want to create an Elastalert rule that sends an email when a “High” severity alert is detected.
According to a rule found here (dating from 2020): [https://github.com/Security-Onion-Solutions/securityonion/discussions/2141](https://github.com/Security-Onion-Solutions/securityonion/discussions/2141), the rule looks for an index containing “***:so-ids-***".

As this index no longer seems to exist in Security Onion version 2.4, I see the following indexes which could potentially be those containing Suricata alerts: 

- .ds-logs-suricata

- .ds-logs-detections

I'm not sure I'm looking in the right indexes, I'd like my Elastalert rule to look for alerts generated for both Suricata and Sigma (in short, all alerts generated by Security Onion).
Has anyone ever created such a rule, and which index is the right one? 

Thanks in advance !

**Comment by rosswakelin** [comment, marked as answer]
The index you need is **logs-suricata.alerts-so**


Here is an example of some of my rule file:

```
#elasticsearch` Host
es_host: cha-osom-v11
es_port: 9200

# (Required)
# Rule name, must be unique
name: "[OPS IDS]  High Severity Event !!!"


# (Required)
# Index to search, wildcard supported
index: "logs-suricata.alerts-so"

# (Required)
# Type of alert.
# This rule will monitor a certain field and match if that field changes.
type: frequency

# (Required, change specific)
# The field to look for changes in
num_events: 1
timeframe:
    minutes: 3
buffer_time:
    minutes: 5
allow_buffer_time_overlap: true
filter:
    - query:
       query_string:
         query: "event.severity:3 AND event.acknowledged is null"
```
Change event.severity to 4 to get Critical alerts
