### DISCUSSION TITLE
Supported multi network deployment for distributed install

### DISCUSSION THREAD

**Discussion by cbspidi** [Security-Onion-Solutions/securityonion#14143] [2.4]
### Version

2.4.111

### Installation Method

Security Onion ISO image

### Description

installation

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

16

### RAM

32

### Storage for /

250

### Storage for /nsm

500

### Network Traffic Collection

span port

### Network Traffic Speeds

Less than 1Gbps

### Status

No, one or more services are failed (please provide detail below)

### Salt Status

Yes, there are salt failures (please provide detail below)

### Logs

Yes, there are additional clues in /opt/so/log/ (please provide detail below)

### Detail

Hi Guys, 
Are you able to confirm if my setup is a valid deployment scenario?

I'm in a network setup where a manager node and several search nodes (1, 2, and 3) are configured with dual connections.

The manager node has one connection to the internet (with a public IP) and another connection to an isolated LAN. The search nodes also have similar dual connections, with one link providing internet access and the other facilitating inter-node communication. 
The primary issue observed is the failure of the installer to download the necessary certificate and repository files from the manager node, leading to a timeout and failure to join the manager.

Pings and DNS works across all the nodes in the setup.

### Guidelines

- [x] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.

**Comment by cbspidi** [comment]
Setup diagram:

![sec-onion-deplayment drawio-with-background](https://github.com/user-attachments/assets/f032ed2b-85d4-4524-9824-76228dc6173a)

**Reply by cm-ops** [reply]
If you run tcpdump on the management interface of your sensor do you see successful connections to the manager?

**Reply by cbspidi** [reply]
I have configured the manager with URL/fqdn as a way of connecting to it.
From what I have seen in the logs, it will appear that the initial (like stage1) goes through the isolated LAN, but in the next stage, downloading repositories from the manager is on connection to fqdn side(public) and times out.

**Reply by cm-ops** [reply]
What does this show? `sudo salt-call pillar.get host:mainint`

**Reply by cbspidi** [reply]
Hello @cm-ops , 
The command outputs an interface facing the public side, 
```
local:
    ens3
```
routing table below for confirmation 

```
default via 117.225.198.154 dev ens3 proto dhcp src 117.225.198.179 metric 100 
10.147.17.0/24 dev tun0 proto kernel scope link src 10.147.17.10 
169.254.169.254 via 137.205.168.129 dev ens3 proto dhcp src 137.205.168.148 metric 100 
169.254.169.254 via 172.16.16.11 dev ens4 proto dhcp src 172.16.16.208 metric 101 
172.16.16.0/24 dev ens4 proto kernel scope link src 172.16.16.208 metric 101 
172.17.0.0/24 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.255.0/24 dev sobridge proto kernel scope link src 192.168.255.1 
```

Where i would like to connect my search nodes is on ens4 in the `172.16.16.0/24` network, and/or connect other sensor nodes in the `10.147.17.0/24` on the `tun0` interface

**Reply by cm-ops** [reply]
Looks like currently salt is using `ens3` as the management interface. 

You can check the entire grid with `sudo salt \* pillar.get host:mainint`.  Also, look at the salt mine and see what ip_addrs are in there with `sudo salt-call mine.get '*' network.ip_addrs`. Finally check `sudo sudo salt \* grains.get ip_interfaces` to see if all your interfaces are there with the configured IPs.

Sounds like to get this to work, you might be able to create a bond interface for the management interface. You would also need to edit some files to change the management NIC to the bond interface name. Stay away from the name `bond0` that is being used on the sensors.

**Reply by cbspidi** [reply]
Hi Chris, 
The command output is below; comment on my side on your point about the bond interface. 

In my opinion, creating a bond will not change much as it seems the manager node picks an interface where a default route is attached; creating a bond will not change the entries in the routing table.

If what I say is `true` the only way to get this to work would be to join all the nodes into an overlay network like `zerotier` and pick mgmt interface to be the one facing the overlay. 

The issue with my approach would be the complexity of the setup and the additional cost of overlay and routing in/out of private and public traffic of the overlay.

```
sec-onion-m1-fqdn_manager:
    ens3
sec-onion-s1_searchnode:
    ens3
sec-onion-s2_searchnode:
    ens3
sec-onion-s3_searchnode:
    ens3
``` 
```
local:
    ----------
    sec-onion-m1-fqdn_manager:
        - 117.225.198.148
    sec-onion-s1_searchnode:
        - 172.16.16.217
    sec-onion-s2_searchnode:
        - 172.16.16.250
    sec-onion-s3_searchnode:
        - 172.16.16.152
```
```
sec-onion-m1-fqdn_manager:
    ----------
    docker0:
        - 172.17.0.1
    ens3:
        - 117.225.198.148
        - fe80::f816:3eff:fe84:ea63
    ens4:
        - 172.16.16.208
        - fe80::f8b3:78b4:baf6:927e
    lo:
        - 127.0.0.1
    sobridge:
        - 192.168.255.1
    veth0ab8e2c:
    veth2249adc:
    veth2651d1d:
    veth303d80e:
    veth326e1a9:
    veth4b34528:
    veth97f6ab3:
    veth9a7cb61:
    vethd593300:
    vethe4fe397:
    vethfe0abfe:
    zt2lruwhx6:
        - 10.147.17.10
sec-onion-s2_searchnode:
    ----------
    docker0:
        - 172.17.0.1
    ens3:
        - 172.16.16.250
        - fe80::f816:3eff:fee4:2c28
    lo:
        - 127.0.0.1
    sobridge:
        - 192.168.255.1
    vethb59e3e3:
    vethd414e8e:
sec-onion-s1_searchnode:
    ----------
    docker0:
        - 172.17.0.1
    ens3:
        - 172.16.16.217
        - fe80::f816:3eff:feab:b8c6
    lo:
        - 127.0.0.1
    sobridge:
        - 192.168.255.1
    veth7627691:
    vethb03f0b5:
sec-onion-s3_searchnode:
    ----------
    docker0:
        - 172.17.0.1
    ens3:
        - 172.16.16.152
        - fe80::f816:3eff:fee6:a16a
    lo:
        - 127.0.0.1
    sobridge:
        - 192.168.255.1
    veth36ca620:
    vethabafa0c:
```
