### DISCUSSION TITLE
Email Notification Setup in ElastAlert

### DISCUSSION THREAD

**Discussion by colaint** [Security-Onion-Solutions/securityonion#14181] [Unsupported Versions] [answered]
Hi everyone,

I’m trying to set up **email notifications for alerts** in **Security Onion 2.4.90**, but I’ve run into some confusion regarding **SMTP** settings and rule locations.

**What I’ve done so far:**

- Created a **custom rule** under `/opt/so/rules/elastalert/rules/custom`:
```yaml
name: Email Test
type: any
index: logs-*
alert:
  - "email"
email:
  - "myemail@gmail.com"
```
- Added the **SMTP username and password** via the Security Onion Web UI under “elastalert,” which successfully updated `/opt/so/conf/elastalert/predefined/smtp_auth.yaml`.

**Where I’m stuck:**

According to the documentation, there should be a setting under:
`Web UI > SOC > Config > Server > Modules > ElastAlertEngine > "Notifications: Sev 0/Default Parameters"`
However, I couldn’t find this option in the UI.

**Here is my current SMTP settings:**
```yaml
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
from_addr: "myemail@gmail.com"
smtp_auth_file: '/opt/so/conf/elastalert/predefined/smtp_auth.yaml'
```

**Confusion on Custom Rule Locations:**

I’ve also found older posts suggesting different locations for **custom rules**:

- `/opt/so/saltstack/local/salt/elastalert/files/custom`
- `/opt/so/conf/elastalert/custom`

**Questions:**

1. **Where exactly should I put my SMTP settings?**
2. **Which is the correct path for custom rules?**

Any guidance would be greatly appreciated!

Thanks in advance!
