### DISCUSSION TITLE
Suppress same rule for more hosts

### DISCUSSION THREAD

**Discussion by jobbe997** [Security-Onion-Solutions/securityonion#1723] [Unsupported Versions] [answered]
maybe I'm nog reading the documentation right but this makes salt fail to compile, when 2000488 is mentioned twice.

thresholding:
  sids:
    2000488:
      - suppress:
           gen_id: 1
           track: by_src
           ip: 1.1.1.1
    2000488:
      - suppress:
           gen_id: 1
           track: by_dst
           ip: 1.1.1.2

this also makes salt fail,

thresholding:
  sids:
    2000488:
      - suppress:
           gen_id: 1
           track: by_src
           ip: 1.1.1.1
      - suppress:
           gen_id: 1
           track: by_dst
           ip: 1.1.1.2

**Comment by dougburks** [comment, marked as answer]
This appears to be working correctly for me:
```
thresholding:
  sids:
    2000488:
      - suppress:
          gen_id: 1
          track: by_src
          ip: 1.1.1.1
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.2
```

**Reply by jobbe997** [reply]
I just get:
_sensor:
    Data failed to compile:

```
thresholding:
  sids:
    2000488:
      - suppress:
           gen_id: 1
           track: by_src
           ip: 1.1.1.1
      - suppress:
           gen_id: 1
           track: by_src
           ip: 1.1.1.2
```

If I remove the second suppress it compiles fine.
