### DISCUSSION TITLE
so-rule-update doesn´t work with proxy

### DISCUSSION THREAD

**Discussion by martin8615** [Security-Onion-Solutions/securityonion#1859] [Unsupported Versions]
Hello Security Onion Team,

we installed SO 2 on an infrastructure that needs a proxy to communicate to the internet. Running` yum update` or `sudo soup` works fine but when it comes to updating the rules `sudo so-rule-update` it aborts with the following error:  

```
2020-11-04 12:22:17,641 - <INFO> - Loading ./rulecat.conf.
2020-11-04 12:22:17,646 - <INFO> - Forcing Suricata version to 5.0.
2020-11-04 12:22:17,646 - <INFO> - Checking https://rules.emergingthreats.net/open/suricata-5.0.0/emerging.rules.tar.gz.md5.
2020-11-04 12:22:22,722 - <ERROR> - Failed to check remote checksum: <urlopen error [Errno -3] Try again>
2020-11-04 12:22:22,725 - <INFO> - Fetching https://rules.emergingthreats.net/open/suricata-5.0.0/emerging.rules.tar.gz.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
........
```

We are currently on version 2.3.0. Before updating to a newer version we want to make sure that the rule update works.

While updating the rules we couldn´t see any hits on our firewall or proxy systems. So it looks like our SO installation needs another entry for the rule-update than the "normal" soup.
Downloading the rules as a zipped file from .emergingthreats.net directly works, so the outgoing connection is fine. We also set the environment variables like it´s mentioned in the documentation. On top we configured the yum.conf and the profile.d to make sure the proxy is set.

Hopefully I could provide all the information you need.

Thank you in advance and kind regards,
Martin

**Comment by weslambert** [comment]
Have you tried any of the proxy configuration described here?

https://docs.securityonion.net/en/latest/proxy.html?highlight=proxy

**Comment by martin8615** [comment]
Yes, I tried it with environment variables and the docker config as well. 
Additionally I added the `rules.emergingthreats.net` in the hosts file.

Is there a special way the so-rule-update works?

**Reply by weslambert** [reply]
It should emulate a normal `http/https` request, so maybe there is still an issue with the other proxy config.

**Reply by weslambert** [reply]
Could there also be SSL inspection being performed, to where it may not be able to validate the cert?  

You could check to see what the cert looks like with the following:

`echo | openssl s_client -showcerts -servername rules.emergingthreats.net -connect rules.emergingthreats.net:443 2>/dev/null | openssl x509 -inform pem -noout -text`

**Reply by martin8615** [reply]
That is what I thought so too. But to inspect the SSL connection our proxy or firewall should see the requests.

Unfortunately we get the following error after performing the command: 
```
unable to load certificate
140578395994000:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE
```

The system tries to connect to the website directly without the proxy. I double checked the environment variables (got them in lower and in capital letters) and checked if there is the right proxy in /etc/yum.conf.  Both entries are set and that is strange part. 
Do you know a different way to set the proxy in CentOS besides in the profile.d and the two ways we described? :)

For the time I tried to update the rules I stopped the local firewall to make sure that could not be the problem. But it´s still the same.

**Comment by ips972** [comment]
Hi All, 
Is there any progress in regards to this issue? 
1. why doens't the install wizard take care of the half a day that one would need to make this setup pass through a proxy? Please just add this to the setup wizard. (yum, environment, docker..etc)

2. after making sure soup, yum, wget and curl can successfully download through the proxy... i go to a situation where the so-rule-update would fail. same error message as above. 

I had to write a script to manually download the ET public tgz, and manualy build the rules.all file and then run a sensor update. 
this would cancel any hope of thresholding or sid disable through salt configs... 
and so i'm left with millions of false positive alerts.. 

Please help!

**Reply by TOoSmOotH** [reply]
1. We have an issue for this: https://github.com/Security-Onion-Solutions/securityonion/issues/529 . We just have not been able to get to it yet. PRs are always welcome.

2. The main issue is idstools runs inside a docker container so you would need modify that env variable inside the container. You could probably add `- environment: `to the following section:

https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/idstools/init.sls#L67

Changes would get wiped out on updates but might be worth a shot to see if it works.

**Reply by ips972** [reply]
> 1. We have an issue for this: #529 . We just have not been able to get to it yet. PRs are always welcome.
> 2. The main issue is idstools runs inside a docker container so you would need modify that env variable inside the container. You could probably add `- environment: `to the following section:
> 
> https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/idstools/init.sls#L67
> 
> Changes would get wiped out on updates but might be worth a shot to see if it works.

can you please explain where and how to add the enviroment attributes for proxy in the init.sls
I'm a complete noob to docker and have zero experience with salt.
Thanks!

**Reply by weslambert** [reply]
Try copying `/opt/so/saltstack/default/salt/idstools/init.sls` to `/opt/so/saltstack/local/salt/idstools/init.sls`, and modifying:

```
so-idstools:
  docker_container.running:
    - image: {{ MANAGER }}:5000/{{ IMAGEREPO }}/so-idstools:{{ VERSION }}
    - hostname: so-idstools
    - user: socore
    - binds:
      - /opt/so/conf/idstools/etc:/opt/so/idstools/etc:ro
      - /opt/so/rules/nids:/opt/so/rules/nids:rw
    - watch:
      - file: idstoolsetcsync
```

to be
```
so-idstools:
  docker_container.running:
    - image: {{ MANAGER }}:5000/{{ IMAGEREPO }}/so-idstools:{{ VERSION }}
    - hostname: so-idstools
    - user: socore
    - binds:
      - /opt/so/conf/idstools/etc:/opt/so/idstools/etc:ro
      - /opt/so/rules/nids:/opt/so/rules/nids:rw
    -environment:
       - VARIABLE1=blah
    - watch:
      - file: idstoolsetcsync
```
