### DISCUSSION TITLE
ElastAlert and Suricata

### DISCUSSION THREAD

**Discussion by DashCarlos** [Security-Onion-Solutions/securityonion#2141] [Unsupported Versions] [answered]
Hello, I am trying to create a rule in ElastAlert to send me emails when the severity of the Suricata alert is high, but I have not found information about how to do this. Can anybody help me?

**Comment by stijnpieters** [comment, marked as answer]
[high-severity.yaml.txt](https://github.com/Security-Onion-Solutions/securityonion/files/5615387/high-severity.yaml.txt)
Something like this should work. Just put this file with your config filled in (in yaml format) in `/opt/so/rules/elastalert/`.
This creates an email alert for every alert higher than medium, not just Suricata though. 
For just Suricata alerts, add `AND event.module:suricata` to the query.

es_host should be your security onion manager 
es_port should be 9200 (the port that exposed elastic on your manager)

`aggregation` is there should more than one alert happen in the interval between queries from elastalert to elasticsearch. It will then aggregate all instances of alerts with severity high or higher into the email.

**Reply by DashCarlos** [reply]
Thank you for your help
I have put that file in .yaml format in the directory you indicated, I restarted elastalert and no mail has arrived yet (and I have a lot of traffic) 

```
es_host: localhost
es_port: 9200
name: High Severity Alert

index: "*:so-ids-*"

type: any

aggregation:
    seconds: 5

filter:
- query:
    query_string:
        query: "event.severity: >2 AND event.module:suricata"

alert:
- "email"

email:
- "xxxchoe@gmail.com"
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
from_addr: "xxxchoe@gmail.com"
smtp_auth_file: '/etc/elastalert/smtp_auth_file.txt'
```


 /opt/so/saltstack/default/salt/elastalert/files/elastalert_config.yaml
I did not configure anything in this file except the following:

```
####################
### EMAIL CONFIG ###
####################
alert:
- "email"
email:
- "xxxchoe@gmail.com"
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
from_addr: "xxxchoe@gmail.com"
smtp_auth_file: '/etc/elastalert/smtp_auth_file.txt'
####################
```
/etc/elastalert/smtp_auth_file.txt
```
user: "xxxchoe@gmail.com"
password: "xxxxxxxxx"
```

I have tried to launch the command so-elastalert-test dumping the result in a file and I get this error

`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`
