### DISCUSSION TITLE
Tuning Suppression Examples via Thresholding

### DISCUSSION THREAD

**Discussion by bayden10** [Security-Onion-Solutions/securityonion#2387] [Unsupported Versions] [answered]
Hi,

I have discovered while trying to compose some suppression rules for our standalone pillar, there seems to be some missing documentation for this[ here ](https://docs.securityonion.net/en/2.3/managing-alerts.html#suppressions) which indicates a "See above for `suppress` examples".

An example of suppression requirements would be from this sample I have started with a threshold rule:

```
thresholding:
  sids:
    2006445:
    - threshold:
          gen_id: 1
          type: limit
          track: by_dst
          count: 10
          seconds: 10
      - rate_filter:
          gen_id: 1
          track: by_src
          count: 50
          seconds: 20
          new_action: pass
          timeout: 60
      - suppress:
          gen_id: 1
          track: by_src
          ip: 10.10.3.0/24

```

With this method is it possible to suppress this noise from our Telegraf & Influx hosts, when [SID] + source IP = 10.10.3.0/24  then [SUPPRESS] (from the suppress: tag) or is there a missing section in the documentation for further discussion or examples?
