### DISCUSSION TITLE
Wazuh agents not able to connect to Forward Node

### DISCUSSION THREAD

**Discussion by innovate-support** [Security-Onion-Solutions/securityonion#2455] [Unsupported Versions] [answered]
I've got a Manager and Forward Node setup and working, both v2.3.21.  I've got Wazuh agents sending data successfully to the Manager server, but the Wazuh agents that I've configured to send their data to the Forward Node aren't showing up in the logs.  I allowed the firewall 1514 on the Forward Node, and defined the agent IP's and copied their keys from the Forward Node.  On the agent configs I'm pointing them at the Forward Node IP.  The logs on the agents say they can't connect to the Forward Node IP on port 1514/udp because the server isn't responding.  Am I missing something?

**Comment by weslambert** [comment]
It sounds like there could still be an issue with the firewall, maybe?  Are you able to use netstat/test-netconnection to verify the port is open?  Here is the link for managing firewalls, JIC something might have been missed: https://docs.securityonion.net/en/latest/firewall.html?highlight=firewall#managing

**Comment by MDCAllan** [comment, marked as answer]
I'm having the same problem. I can create and connect agents on the manager node, but not on the forward(sensor) node. 

I agree this is a firewall issue, but I think it originates with files that need to be properly defined from a development perspective... 

My /opt/so/saltstack/default/salt/firewall/assigned_hostgroups.map.yaml has this entry for the sensor node role (which I assume is the "forward" node role):

 sensor:
    chain:
      DOCKER-USER:
        hostgroups:
          self:
            portgroups:
              - {{ portgroups.syslog}}
      INPUT:
        hostgroups:
          anywhere:
            portgroups:
              - {{ portgroups.ssh }}
          dockernet:
            portgroups:
              - {{ portgroups.all }}
          localhost:
            portgroups:
              - {{ portgroups.all }}

Most of the other roles in this file appear to have entries in them that make sense for the roles and that are chosen as part of the development process for the various deployment scenarios. This doesn't look like a file I should be editing to make wazuh work as intended with a forward node, but if I can/should, please let me know what this should look like. 

Thanks!

**Reply by innovate-support** [reply]
Here's the logs of the Agent.
```
2021/02/11 16:16:12 ossec-agent: INFO: Trying to connect to server (10.11.12.156:1514/udp).
2021/02/11 16:17:17 ossec-agent: INFO: Closing connection to server (10.11.12.156:1514/udp).
```

Here's the results when testing connectivity from Agent to Sensor.
```

PS C:\Users\Administrator> Test-NetConnection 10.11.12.156 -Port 1514
WARNING: TCP connect to 10.11.12.156:1514 failed

ComputerName           : 10.11.12.156
RemoteAddress          : 10.11.12.156
RemotePort             : 1514
InterfaceAlias         : 10.11.12.x
SourceAddress          : 10.11.12.88
PingSucceeded          : True
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False

```

If there's a firewall command that needs entered on either the Sensor or the Manager in order to make this work, please advise.

**Reply by trb143** [reply]
You need to run `sudo so-allow`   see https://docs.securityonion.net/en/2.3/so-allow.html

**Reply by innovate-support** [reply]
Already ran so-allow before trying to connect agents. Seems to not function correctly on Sensors, only works right on Manager.

**Reply by MDCAllan** [reply]
Yea sudo so-allow doesn't fix this problem.

**Reply by innovate-support** [reply]
I tried running `sudo so-firewall includehost wazuh_agent X.X.X.X` on the Manager which added the Sensor's IP to the /opt/so/saltstack/local/salt/firewall/hostgroups.local.yaml file, but nothing is resolved. Agent still can't connect to Sensor.

I even tried running `sudo so-allow` again on the Sensor to allow Agent IP, but nothing changed.

**Reply by innovate-support** [reply]
Not sure if this is relevent or not, but this just scrolled across my Sensor terminal.  It shows the IP and Port number that's getting updated in iptables.  Isn't that Port number for Wazuh supposed to be 1514, not 514???  Is there an error in the firewall codes on the Manager somehwere?

````

         ID: iptables_LOGGING_limit
    Function: iptables.append
      Result: True
     Comment: iptables rule for iptables_LOGGING_limit already set (/sbin/iptables --wait -t filter -A LOGGING  -m limit --limit 2/min --jump LOG --log-level 4 --log-prefix "IPTables-dropped: ") for ipv4
     Started: 19:32:50.104484
    Duration: 19.229 ms
     Changes:   

          ID: iptables_log_input_drops
    Function: iptables.append
      Result: True
     Comment: iptables rule for iptables_log_input_drops already set (/sbin/iptables --wait -t filter -A INPUT  --jump LOGGING) for ipv4
     Started: 19:32:50.124164
    Duration: 287.207 ms
     Changes:   

          ID: enable_docker_user_fw_policy
    Function: iptables.insert
      Result: True
     Comment: iptables rule for enable_docker_user_fw_policy already set for ipv4 (/sbin/iptables --wait -t filter -I DOCKER-USER 1 ! --in-interface docker0 --out-interface docker0 --jump LOGGING)
     Started: 19:32:50.411779
    Duration: 297.196 ms
     Changes:   

          ID: enable_docker_user_established
    Function: iptables.insert
      Result: True
     Comment: iptables rule for enable_docker_user_established already set for ipv4 (/sbin/iptables --wait -t filter -I DOCKER-USER 1 -m conntrack ! --in-interface docker0 --out-interface docker0 --ctstate RELATED,ESTABLISHED --jump ACCEPT)
     Started: 19:32:50.709415
    Duration: 343.514 ms
     Changes:   

          ID: insert_DOCKER-USER_self_10.11.12.156_514_tcp_1
    Function: iptables.insert
      Result: True
     Comment: iptables rule for insert_DOCKER-USER_self_10.11.12.156_514_tcp_1 already set for ipv4 (/sbin/iptables --wait -t filter -I DOCKER-USER 1 -p tcp --dport 514 --source 10.11.12.156 --jump ACCEPT)
     Started: 19:32:51.053261
    Duration: 288.965 ms
     Changes:   

          ID: insert_DOCKER-USER_self_10.11.12.156_514_udp_2
    Function: iptables.insert
      Result: True
     Comment: iptables rule for insert_DOCKER-USER_self_10.11.12.156_514_udp_2 already set for ipv4 (/sbin/iptables --wait -t filter -I DOCKER-USER 1 -p udp --dport 514 --source 10.11.12.156 --jump ACCEPT)
     Started: 19:32:51.342648
    Duration: 293.025 ms
     Changes:   

````
