### DISCUSSION TITLE
Suricata Suppression not working or am I not working?

### DISCUSSION THREAD

**Discussion by B3DTech** [Security-Onion-Solutions/securityonion#2528] [Unsupported Versions] [answered]
I'm guessing I'm doing something wrong here.  I added the following to the global.sls.  I have tens of thousands of false alerts showing up for these rules from these source IP's.  My logic is that adding the Suricata suppression rule would prevent these from showing up in SOC Alerts.

```
thresholding:
  sids:
    2028763:
    - suppress:
      gen_id: 1
      track: by_src
      ip: [10.85.189.13, 10.85.160.53, 10.85.129.10]
    2028396:
    - suppress:
      gen_id: 1
      track: by_src
      ip: 10.85.160.14
```

I see it successfully applied on the sensors:

cat threshold.conf
suppress gen_id 1, sig_id 2028763, track by_src, ip ['10.85.189.13', '10.85.160.53', '10.85.129.10']
suppress gen_id 1, sig_id 2028396, track by_src, ip 10.85.160.14

However these sig's are still showing up in SOC Alerts.  

What might I be missing?  Thanks!
