### DISCUSSION TITLE
Encrypted WinLogBeats to LogStash running on SO 2.3.21 (Ubuntu 18.04 Server)

### DISCUSSION THREAD

**Discussion by gh0st-network** [Security-Onion-Solutions/securityonion#2584] [Unsupported Versions] [answered]
Tried to replicate my SO16.04 deployment which had encrypted WinLogBeats to LogStash but encountered issues. The following are the steps I have performed. Appreciate if anyone could advise if I missed any steps:

1) did a so-allow for beats (b) from the entire subnet (/24)
2) copied the CA chain cert, server cert, and server key to "/opt/so/conf/logstash/etc/certs/"
3) copied the "0009_input_beats.conf" to "/opt/so/saltstack/local/salt/logstash/pipelines/config/so" and edited it to look like the following:
```
input {
  beats {
    port => "5044"
    ssl => true
    ssl_certificate_authorities => ["/usr/share/logstash/ca-chain.cert.crt"]
    ssl_certificate => "/usr/share/logstash/certs/server.cert.crt"
    ssl_key => "/usr/share/logstash/certs/server.key.p8"
    ssl_verify_mode => "force_peer"
    tags => [ "beat-ext" ]
  }
}
```
4) restarted logstash (so-logstash-restart) and confirm all services up and running using so-status
5) Attempted to validate the certificates (using guide at https://www.elastic.co/guide/en/beats/winlogbeat/7.9/configuring-ssl-logstash.html) but was presented with a "Connection Refused" error. That said, the attempt using the loopback address 127.0.0.1 was successful. Output is as below:
```
user@server:~/temp$ curl -v --cacert ca-chain.cert.pem https://192.168.1.25:5044
* Rebuilt URL to: https://192.168.1.25:5044/
*   Trying 192.168.1.25...
* TCP_NODELAY set
* connect to 192.168.1.25 port 5044 failed: Connection refused
* Failed to connect to 192.168.1.25 port 5044: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.1.25 port 5044: Connection refused
user@server:~/temp$ curl -v --cacert ca-chain.cert.pem https://127.0.0.1:5044
* Rebuilt URL to: https://127.0.0.1:5044/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5044 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ca-chain.cert.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:5044
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:5044
```
Note: The following is the error from the client-side WinLogBeats running on Windows 10
`2021-01-07T18:31:54.638+0800    ERROR   [publisher_pipeline_output]     pipeline/output.go:154  Failed to connect to backoff(async(tcp://192.168.1.25:5044)): dial tcp 192.168.1.25:5044: connectex: No connection could be made because the target machine actively refused it.`

Thanks in advance for any guidance or advice.

**Comment by gh0st-network** [comment, marked as answer]
I managed to fix my own issue. Appears there is a typo in the "ssl_certificate_authorities" path: should read "/usr/share/logstash/**certs**/ca-chain.cert.crt" instead of "/usr/share/logstash/ca-chain.cert.crt". 

Fixed the path and logstash was happy. Hopefully this ticket will provide guidance for others.

**Reply by ColeVan** [reply]
Hello,
How exactly did you create the certs so that the endpoint could use them? What does your winlogbeat.yml file look like? Any help would be greatly appreciated. I've been trying to figure this out for weeks...

**Reply by gh0st-network** [reply]
Hi, you will need a Certificate Authority to generate and sign your certs. It could be one of those commercial ones or you could also build one your own using OpenSSL. The following are relevant sections of the winlogbeat.yml:

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h

  - name: System

  - name: Security

  - name: Microsoft-Windows-Sysmon/Operational

  - name: Windows PowerShell
    event_id: 400, 403, 600, 800

  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103, 4104, 4105, 4106

**[removed]**

# ---------------------------- Elasticsearch Output ----------------------------
#output.elasticsearch:
  # Array of hosts to connect to.
  #hosts: ["localhost:9200"]

  # Protocol - either `http` (default) or `https`.
  #protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  #username: "elastic"
  #password: "changeme"

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.1.25:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["C:/ProgramData/Elastic/Beats/winlogbeat/certs/ca-chain.cert.pem"]

  # Certificate for SSL client authentication
  ssl.certificate: "C:/ProgramData/Elastic/Beats/winlogbeat/certs/client.cert.pem"

  # Client Certificate Key
  ssl.key: "C:/ProgramData/Elastic/Beats/winlogbeat/certs/client.key.pem"

```
Hope the above helps.
