### DISCUSSION TITLE
Wazuh rules/alerts management

### DISCUSSION THREAD

**Discussion by AnkitSlashKarn** [Security-Onion-Solutions/securityonion#2771] [Unsupported Versions]
I have been getting alot of unwanted alerts in SOC interface mostly via HIDS/Wazuh for events such as Pam user login & Windows Logon Success. I read through the official documentation of Security Onion 2.3 but was unable to find a working method to disable these rules or alerts.
First, I have tried the method mentioned in the Tuning - Managing Alerts Section as well as looking through the Internet.

I have basically tried two things - Disabling the sid in minions file as mentioned in the screenshot below. 

<img width="832" alt="seco doc1" src="https://user-images.githubusercontent.com/14246389/106124317-f5a6f580-6180-11eb-9f07-5415b60c4519.png">

I have some doubts in this 
1. Is the "rule.id" shown in screenshot below - the required "sid" mentioned in the above screenshot ? If not, how can I find SID for a rule/alert I want to disable? Also, how can I disable multiple SIDs that I don't want to see in my Alerts?

<img width="918" alt="SOC1" src="https://user-images.githubusercontent.com/14246389/106124850-8da4df00-6181-11eb-9f0d-e4b98b6272f8.png">

Nevertheless, I went to this filepath and disabled 5501 (screenshot below)

<img width="375" alt="minions1" src="https://user-images.githubusercontent.com/14246389/106125535-4b2fd200-6182-11eb-950b-762e62589753.png">

I am still getting the alerts and this didn't work for me.

So I tried another way of disabling the defined rules -

I went to the filepath **/opt/so/rules/hids/ruleset/rules**  and tried commenting out the specific rules in a xml file to disable those alerts - as shown in the screenshot below

<img width="948" alt="pam1" src="https://user-images.githubusercontent.com/14246389/106128311-4b7d9c80-6185-11eb-9951-177c91388817.png">

This didn't work either and I am still getting the alerts.

Are any of these methods the right approach to disable HIDS/Wazuh rules/alerts ? Thank you so much for reading so far.

I would also be grateful if you could tell me if there is some open source Ruleset Manager (GUI) that can be integrated with Security Onion to manage HIDS and NIDS rules/alerts.
 

<------------------------------ Update since 28th Jan --------------------------------------->

I tried one more way of disabling the alerts. Not sure if this would get the job done. I made  a change in the ossec.conf file changing the  log alert level from 1 to 4. Still getting the alerts. 

<img width="411" alt="ossec2" src="https://user-images.githubusercontent.com/14246389/106291109-3aaa5500-6271-11eb-91eb-7d44785c72e1.png">

**Comment by weslambert** [comment]
You should be able to tune Wazuh rules by following the instructions here: https://docs.securityonion.net/en/latest/wazuh.html?highlight=rules#tuning-rules

**Reply by AnkitSlashKarn** [reply]
@weslambert Thank you for your answer. But how can I disable the rules for which I don't want to see any alerts like successful windows logins. The file you mentioned has two sections - one is for adding local rules and the other one is for modifying some existing rules. I want to disable low level alerts like "Windows Logon Success" "PAM: Login session opened" "PAM: Login session closed." 
 
I have been getting a whole lotta unwanted alerts which I want to disable for a more focused view on alerts.

**Reply by innovate-support** [reply]
Any update on this topic?  This seems like a very common task that should have a detailed explanation in the docs.  I also need to filter out known Wazuh noise.  Please advise.

**Reply by innovate-support** [reply]
@AnkitSlashKarn 
I believe I've come across a solution that seems to be working.

Yes, the **rule.uuid** number shown when drilling down into the Alerts webpage is the number that we'll be keying off of.

You need to add a **thresholding** section (example below) into **/opt/so/saltstack/local/pillar/global.sls**

You need to add a suppress rule for each rule.uuid that you want to hide.  Syntax samples can be found at
https://docs.securityonion.net/en/2.3/managing-alerts.html?highlight=suppression#suppressions 

Here's an example of what I have added to the bottom of my global.sls file.  

```
thresholding:
  sids:
    2019003:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.13
    2000418:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.12,10.11.12.13
    2020084:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.13
    2013505:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.156,10.11.12.157
    5402:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.156,10.11.12.157
```
Once that's saved you need to run the following command to make sure there's no errors.  If you get errors you probably have a syntax problem in the rules you just edited.  Go fix them and try this command again. 
`sudo salt \* state.highstate`

Once the highstate finishes successfully you can check the following file on your Sensors to see all the rules that got propagated.
`sudo cat /opt/so/conf/suricata/threshold.conf`

Now you can check your Alerts webpage.  Change the time range to the last 10 minutes to see the most recent alerts for the rules you wanted to suppress.  Refresh the page after a few minutes.  Those specific alerts should be reducing.  After 10 minutes they should be gone.  This confirms that your suppression rule is working.
