### DISCUSSION TITLE
Detailed alert suppression documentation needed

### DISCUSSION THREAD

**Discussion by innovate-support** [Security-Onion-Solutions/securityonion#2910] [Ideas] [answered]
I have a lot of Alerts that are known traffic that I am comfortable ignoring completely.  I've reviewed the SO docs and tried a few things to suppress those alerts but can't seem to figure out how to successfully filter those out so I never see them.  The docs seem lacking in this area.  Please add samples with screenshots and/or syntax options to the docs.

**Comment by weslambert** [comment]
Hi @innovate-support , 

Would you be able to provide an example of what you were trying to suppress, and how you attempted to do so?

**Comment by innovate-support** [comment, marked as answer]
I've read that entire managing-alerts.html page in the docs and then added the following lines to my global.sls file

nids:
  bpf:
    - not host 10.11.12.69 &&
    - not port 1984
thresholding:
  sids:
    2010935:
      - suppress:
          gen_id: 1
          track: by_src
          ip: 10.11.12.72

My intent was to 'hide' all the alerts with those rule.uuid numbers because they're known traffic that I don't want to see as Alerts.  The nids bpf lines did filter out all that traffic as expected, but the thresholding sids rules did not.  I'm still seeing the same traffic being alerted for rule.uuid 2010935 for that IP.  Here's a screenshot of the alert in question.

![Screenshot from 2021-02-09 13-12-57](https://user-images.githubusercontent.com/20424476/107669618-29891d00-6c4f-11eb-9564-d3771fda6b82.png)

I suspect that I'm just making a simple syntax error with my suppression rule and/or I'm entering it in the wrong config file.  This seems like an easy request for someone who knows what they're doing.  This also seems to be something that EVERYONE needs once they get their systems up and running.  Filtering out the noise is a huge part of making your product useful as apposed to something that's just a flood of random data.  I need to get this suppression stuff figured out because I'm about to start sending Wazuh traffic into the system and I will need to suppress some stuff there too.  I figured I should get it working with this basic network traffic before I was flooded with the Wazuh logs.

**Reply by TOoSmOotH** [reply]
What does your /opt/so/conf/suriacata/threshold.conf look like on your sensor. 

Thresholding only applies to new alerts and does not change past alerts in ES.

**Reply by innovate-support** [reply]
After messing around with it for a bit I found that there was a Salt error happening.  If I clear out the threshold rules from the Manager's global.sls file and reboot the Manager, everything is refreshed and is running fine.  The Sensor's threshold.conf file is empty.  Then I add a threshold rule into the Manager's global.sls file and run 'sudo salt \* state.highstate' to propogate things and the rule does in fact get populated into the Sensor's threshold.conf file correctly.  So far all is well.

Then I add a second rule into the Manager's global.sls file and repeat the manual salt highstate command.  This time I get the following errors.  

**sensor1_sensor:
Data failed to compile:
Pillar failed to render with the following messages:
Rendering SLS 'global' failed. Please see master log for details.
sensor2_sensor:
Data failed to compile:
Pillar failed to render with the following messages:
Rendering SLS 'global' failed. Please see master log for details.
so_managersearch:
Data failed to compile:
Pillar failed to render with the following messages:
Rendering SLS 'global' failed. Please see master log for details.
ERROR: Minions returned with non-zero exit code**


Upon rebooting the Manager the multiple rules DO get pushed to the Sensor's threshold.conf correctly.  If I add more rules it again causes errors.  Rebooting the Manager doesn't help when adding 3 or more rules though.  None of the containers will start anymore.  I have to delete all the threshold rules from the global.sls file and then reboot the Manager before everything goes back to normal.  This seems to be an easily repeatable error as I've tried it a few times with the same results.

**Reply by innovate-support** [reply]
If I add the following into my global.sls file I get the errors when trying to refresh the salt highstate.  When I remove them salt works fine.  Do I have a syntax issue or something?

```
thresholding:
  sids:
    2010935:
      - suppress:
          gen_id: 1
          track: by_src
          ip: 10.11.12.72
    2019003:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.13
    2000418:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.12
    2000418:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.13
    2023213:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.12
    2020084:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.11.12.13
```
