### DISCUSSION TITLE
dns.query.name alerts

### DISCUSSION THREAD

**Discussion by chadlangston** [Security-Onion-Solutions/securityonion#3067] [Unsupported Versions] [answered]
Hi All,

Does anyone know the easiest way to generate alerts when a particular dns is queried. Specifically, I want to send alerts when dns.query.name == something. It looks like using the ElastAlert rules is the easiest method, using the so-elastalert-create tool, but what type of ElastAlert rule should I use? Blacklist? I tried creating the following rule, but I get connection errors when I use the so-elastalert-test tool to test it. Presumably that is becuase the elasticsearch host name is unreachable from outside the docker container running elastalert. Also, I noticed that Playbook uses ElastAlert to generate alerts and wondered if using Playbook to create these dns query alerts would be easier? Thank you in advance for any ideas any one may have on this!

ElastAlert rule
es_host: elasticsearch
es_port: 9200
name: forter
index: "*:so-ids-*"
type: blacklist
compare_key: dns.query.name
blacklist:
    - "forter.com"
filter:
- wildcard:
    event_type: "*"
alert:
- email
email:
 - email@email.com

**Comment by defensivedepth** [comment, marked as answer]
Yes, you can create a Playbook Play for something like this. For example:

```
title: Disallowed DNS Query Name
status: experimental
description: Detects when certain DNS query names are found
author: TBD
logsource:
    product: zeek
    service: dns
detection:
    selection:
        dns.query.name: 
            - forter.com
            - google.com
    condition: selection
falsepositives:
    - None
level: high
```
