### DISCUSSION TITLE
Schema for Sigma->Elastalert converted rules in Playbook using the .security field

### DISCUSSION THREAD

**Discussion by Twide** [Security-Onion-Solutions/securityonion#3146] [Unsupported Versions] [answered]
There is a field mismatch when i compare the elastalert rules (converted from Neo:s github repository) inside Playbook and my sysmon-events (shipped with winlogbeat) that's being indexed to elasticsearch.
Sysmon-elastalert-rules in the playbook library have the .security field-extension for a lot of fields. But all my events are missing that specific extension.

Rule Example:
```
filter:
- query:
    query_string:
      query: (event.code.security:"11" AND winlog.channel.security:"Microsoft\-Windows\-Sysmon\/Operational" AND file.target.security:("*\\svchost.ex...........
```

Log Example:
```
event.code | 11

winlog.channel | Microsoft-Windows-Sysmon/Operational

```
Maybe my events in elasticsearch should have the added ".security"?

I have looked at the sigmac template in the so-soctopus docker (docker exec so-soctopus cat playbook/securityonion-baseline.yml ), but i'am not sure what files is actually being used.

Ideas? :)

**Comment by defensivedepth** [comment, marked as answer]
The `.security` is a subfield that is generated by a special analyzer by https://github.com/neu5ron/es_stk that we use in Security Onion, that gives us case insensitive wildcard searches, specifically for security logs.

If you copy and past the query into Kibana (with Lucene syntax), it should work, though to be fair, we have some fixes shipping in the next release (2.3.30) that should make these queries more accurate.

**Reply by Twide** [reply]
Very nice feature! :) of course that will be a good technique against an evasion attempt.

Maybe this is going into your fix, otherwise i would like to show one side effect of using .security as default when translating Sigma-rules. It's probably at least usable information for others looking at using community sigma-rules.

When Sigma-rules that are written like this:
[notice --> *\ before regsvr32.exe]
```
detection:
  selection1:
    Image: '*\regsvr32.exe'
    CommandLine: '*\Temp\\*'
  selection2:
    Image: '*\regsvr32.exe'
    ParentImage: '*\powershell.exe'
...
```
It gets converted to: 
```
(process.executable.security:"*\\regsvr32.exe" AND process.command_line.security:"*\\Temp\\*")
OR
(process.executable.security:"*\\regsvr32.exe" AND process.parent.executable.security:"*\\powershell.exe")

```
Since neither process.executable.security, process.parent.executable.security or process.command_line.security contains the character --> \ there wont be any hits for this query.

I do not know what the best solution is for this, and i am not skilled enough (at the moment) to solve this with automation ;-)
Possible workarounds:
* Modify rules that use a special character that the .security analyzer will remove.
* Remove the .security extension on the converted elastalert-rules

**Thanks for the truly amazing work you guys are doing with Security Onion!**
