### DISCUSSION TITLE
Installing a heavy node on 2.3.30 fails for elasticsearch (not master eligible)

### DISCUSSION THREAD

**Discussion by trocade** [Security-Onion-Solutions/securityonion#3221] [Unsupported Versions]
I installed a heavy-node with 2.3.30 and elasticsearch seems to be misconfigured and fails with the following  error message:
```
2021-03-02T10:23:41,410][ERROR][org.elasticsearch.bootstrap.Bootstrap] Exception
java.lang.IllegalArgumentException: node with [discovery.type] set to [single-node] must be master-eligible

```
And this is the configuration created during the installation, which indeed sets master to false:

```
node.roles: ['data', 'ingest']
node.attr.box_type: hot
discovery.seed_hosts:
   - <manager>
indices.query.bool.max_clause_count: 1500
```

Also a bit curious about seed_hosts set to the manager?

**Comment by TOoSmOotH** [comment]
Did you select true clustering in advanced?

**Reply by trocade** [reply]
The setting in global.sls is set to true:
```
elasticsearch:
  replicas: 0
  true_cluster: True
  true_cluster_name: 'securityonion'
  discovery_nodes: 1
  hot_warm_enabled: False

```

But during re-installation of the manager I can only remember seeing a question if I would like to run a hot/warm architecture setup.

So If I set true_cluster to false it should act as intended where every node is it's own one node cluster?
