### DISCUSSION TITLE
Suppression won't work with more than 4 IP/IP ranges in a row on 2.3.30

### DISCUSSION THREAD

**Discussion by Masaya-A** [Security-Onion-Solutions/securityonion#3248] [Unsupported Versions]
OS: CentOS Linux 7
SETUP METHOD: network
SETUP MODE: STANDALONE

Until SO2.3.21, a suppression rule shown blow was working.
```
thresholding:
  sids:
    2013028:
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,5.5.5.5
```

On SO 2.3.30, however, I got error in a suricata log and the suppression rule seem to be ignored even though the log says "1 rule found."
> <Error> - [ERRCODE: SC_ERR_PCRE_COPY_SUBSTRING(325)] - pcre_copy_substring failed
> <Info> - Threshold config parsed: 1 rule(s) found

If the IPs are written separatedly like below, it works fine. (And the log says "2 rules found.")
```
thresholding:
  sids:
    2013028:
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 5.5.5.5
```

> <Info> - Threshold config parsed: 2 rule(s) found

If like below, 1.1.1.1 ~ 4.4.4.4 work, 5.5.5.5 ~ 9.9.9.9 not work
```
thresholding:
  sids:
    2013028:
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 5.5.5.5,6.6.6.6,7.7.7.7,8.8.8.8,9.9.9.9
```

If like below, 6.6.6.6 ~ 9.9.9.9 work, 1.1.1.1 ~ 5.5.5.5 not work
```
thresholding:
  sids:
    2013028:
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,5.5.5.5
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 6.6.6.6,7.7.7.7,8.8.8.8,9.9.9.9
```

So suppression won't work with more than 4 IP/IP ranges in a row.

Could you fix this?
(I think this is not a SecurityOnion side problem, but not sure...)
