### DISCUSSION TITLE
Disabling alerts using regex is not working

### DISCUSSION THREAD

**Discussion by amlamarra** [Security-Onion-Solutions/securityonion#3367] [Unsupported Versions] [answered]
I can't seem to disable alerts using regex. For example, I'd like to disable all alerts that start with "ET POLICY". So right now, my `/opt/so/saltstack/local/pillar/minions/<minionid>.sls` file looks like this:
```
idstools:
  config:
    oinkcode: ''
    ruleset: ETOPEN
    urls: null
  sids:
    disabled:
      - 2101411 # GPL SNMP public access udp
      - 're:ET\ POLICY'
```
Then, I run `sudo salt $SENSORNAME_$ROLE state.apply idstools`. In my case, this looks like ` sudo salt securityonion_standalone state.apply idstools`.

I test this out by triggering the "ET POLICY PE EXE or DLL Windows file download HTTP" alert by doing `curl http://testmynids.org/exe/calc.exe`. It seems I can disable by specifying the SID, but not by regex. Other things I've tried are:
```
      - 're:ET\ POLICY'
      - 're:ET POLICY'
      - 're:et policy'
      - 're:et\ policy'
      - 're:policy'
```
Nothing seems to work. I'm still able to trigger the alert. What am I doing wrong?
