### DISCUSSION TITLE
Search nodes - should they be identical in terms of storage volume?

### DISCUSSION THREAD

**Discussion by presianbg** [Security-Onion-Solutions/securityonion#3414] [Unsupported Versions]
Hi,

I can't find anything about - should the search nodes have identical disks in terms of size ?

By looking into the `/opt/so/saltstack/local/pillar/global.sls` :
```
elasticsearch:
  replicas: 0
```
Means its like `RAID0`  and by default every search node has some of the data based on some load balance logic, am I right ?

I can see from another [discussions](https://github.com/Security-Onion-Solutions/securityonion/discussions/2186#discussioncomment-147189) related to retention that `global.sls` can be modified to extend per index lifetime:

```
    so-ids:
      shards: 1
      warm: 7
      **close: 30**
      delete: 365
```
Not sure what `delete: 365`  and `warm: 7` do, but `close:30` means that the data (documents) older than  30 days wont be available anymore, right ?

Also the `log_size_limit` field in `/opt/so/saltstack/local/pillar/minions/$SENSORNAME_$ROLE.sls` can be used to prevent disk being 100% full.

In my understanding we have the data (documents) for max 30 days or until it hit the `log_size_limit` (per search node), which ever happens first. (by default). 

From the [docs](https://docs.securityonion.net/en/2.3/curator.html) :
```
Curator defaults to closing indices older than 30 days. To modify this, change cur_close_days in /opt/so/saltstack/local/pillar/minions/$SENSORNAME_$ROLE.sls.
```

but in our setup the manager pillar has:
```
cur_close_days: null
```
so I assume the `close` value for per index is taken from the `global.sls`:
```
index_settings:
    so-beats:
      shards: 1
      warm: 7
      close: 30
      delete: 365
    so-firewall:
      shards: 1
      warm: 7
      close: 30
      delete: 365
    so-flow:
      shards: 1
      warm: 7
      close: 30
      delete: 365
    so-ids:
      shards: 1
      warm: 7
      close: 30
      delete: 365
```
Now I'm confused what is the best (recommended) way to increase the retention time of  all indexes ?
If I want to extend the retention period for all of the indexes, it should be enough to change
`cur_close_days: null` to `cur_close_days: 45` in the manager pillar and the local `log_size_limit` of each search node will take care not to reach the disk capacity ?

What is the precedence of the configs - `cur_close_days: null` or per index `close` , which overwrites which ?

Edit:
Also I forgot to ask if 300GB is really needed for the rest of the `/`:

```
system-root 253:0    0   293G  0 lvm  /
system-swap 253:1    0     8G  0 lvm  [SWAP]
system-nsm  253:2    0 696.6G  0 lvm  /nsm
system-tmp  253:3    0     2G  0 lvm  /tmp
```
I'm not very familiar with the LVM, but could be some of the space  from the `/` re-assigned to the `/nsm` ?

Cheers,
PY
