### DISCUSSION TITLE
Forwarding Events to an External Destination

### DISCUSSION THREAD

**Discussion by kiaraho** [Security-Onion-Solutions/securityonion#3456] [Unsupported Versions] [answered]
I've successfully setup forwarding of Zeek DNS logs from Logstash to an external destination. The following entires were added to `/opt/so/saltstack/local/pillar/global.sls` on the Manager node:
```
logstash:
  pipelines:
    search:
      config:
        - so/0900_input_redis.conf.jinja
        - so/9000_output_zeek.conf.jinja
        - so/9002_output_import.conf.jinja
        - so/9034_output_syslog.conf.jinja
        - so/9100_output_osquery.conf.jinja
        - so/9400_output_suricata.conf.jinja
        - so/9500_output_beats.conf.jinja
        - so/9600_output_ossec.conf.jinja
        - so/9700_output_strelka.conf.jinja
        - custom/9703_output_custom_dns.jinja
```
The contents of `/opt/so/saltstack/local/salt/logstash/pipelines/config/custom/9703_output_custom_dns.jinja` include:
```
output {
  if [module] =~ "zeek" and [dataset] =~ "dns" {
    tcp {
      host => "192.168.x.x"
      port => 10003
      codec => "json_lines"
    }
  }
}
```
Everything worked fine until I shutdown the host at remote destination 192.168.x.x for maintenance. At that point, I noticed that all logs stopped populating in the Security Onion Console, possibly because nothing was making into Elasticsearch on the Search node. Everything returned to normal once the remote destination host was back online. I have a distributed architecture with a Manager node, one Search node and multiple Sensors.

The SO2 documentation on [Forwarding Events to an External Destination](https://docs.securityonion.net/en/latest/logstash.html#forwarding-events-to-an-external-destination) mentions cloning events, but I don't have a good example for Zeek DNS logs.
