### DISCUSSION TITLE
Encryption of communication between WinLogBeat and LogStash - Please Help

### DISCUSSION THREAD

**Discussion by alex-event** [Security-Onion-Solutions/securityonion#3692] [Unsupported Versions]
I know it's really stupid, but I can't figure out exactly how to create these certificates. This drives me crazy. Can someone send me the exact guide on how to create these certificates or tell me exactly where I am wrong in the encryption configuration.

To create the certificates, I use this guide: https://openvpn.net/community-resources/setting-up-your-own-certificate-authority-ca/

After copying absolutely everything in **/usr/share/logstash/certs** and **/opt/so/saltstack/local/salt/logstash/etc/certs** I restart **logstash** with the following command **so-logstash-restart**. I check the status with **so-status** and everything is **ok**

_I think the documentation in this article is wrong, about the path where I need to copy certificate files: **https://docs.securityonion.net/en/2.3/beats.html?highlight=**_

The contents of /opt/so/saltstack/local/salt/logstash/pipelines/config/so/**0009_input_beats.conf** is:

```
input {
  beats {
    port => "5044"
    ssl => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca.crt"]
    ssl_certificate => "/usr/share/logstash/certs/server1.crt"
    ssl_key => "/usr/share/logstash/certs/server1.key"
    tags => ["beat-ext"]
  }
}

```
On the machine where SO 2.3.40 (CentOS 7) is installed I run the following command:

```
[root@so-eval certs]# curl -v --cacert ca.crt https://172.16.0.10:5044
* About to connect() to 172.16.0.10 port 5044 (#0)
*   Trying 172.16.0.10...
* Connected to 172.16.0.10 (172.16.0.10) port 5044 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: ca.crt
  CApath: none
* Server certificate:
*       subject: E=admin@so-eval.com,name=*,CN=*,OU=IT,O=Event-Sys,L=Sofia,ST=SF,C=BG
*       start date: Mar 30 17:30:30 2021 GMT
*       expire date: Mar 28 17:30:30 2031 GMT
*       common name: *
*       issuer: E=admin@so-eval.com,name=*,CN=*,OU=IT,O=Event-Sys,L=Sofia,ST=SF,C=BG
* NSS error -12276 (SSL_ERROR_BAD_CERT_DOMAIN)
* Unable to communicate securely with peer: requested domain name does not match the server's certificate.
* Closing connection 0
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

On the client machine where Winlogbeat is installed I start:

```
PS C: \Program Files\Elastic\Beats\7.11.2\ winlogbeat>. \ Winlogbeat.exe test output
logstash: 172.16.0.10:5044 ...
  connection ...
    parse host ... OK
    dns lookup ... OK
    addresses: 172.16.0.10
    dial up ... OK
  TLS ...
    security: server's certificate chain verification is enabled
    handshake ... ERROR x509: cannot validate certificate for 172.16.0.10 because it doesn't contain any IP SANs
```

Here is some of the content of winlogbeat.yml:

```
# ------------------------------ Logstash Output ----------------- --------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.16.0.10:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ['C: \Program Files\Elastic\Beats\7.11.2\ winlogbeat\ca.crt']

  # Certificate for SSL client authentication
  ssl.certificate: 'C: \Program Files\Elastic\Beats\7.11.2\ winlogbeat\client1.crt'

  # Client Certificate Key
  ssl.key: 'C: \Program Files\Elastic\Beats\7.11.2\ winlogbeat\client1.key'
```

If I comment on the lines above in winlogbeat.yml (without the certificates) the communication between the client machine and logstash is ok.
