### DISCUSSION TITLE
Yet another question about suppressing alerts

### DISCUSSION THREAD

**Discussion by UMHB-InfoSec** [Security-Onion-Solutions/securityonion#3737] [Unsupported Versions] [answered]
I am sorry to open another thread about suppression but I have searched many times in the discussion list and I have tried every remedy offered but nothing has worked so far.

I have a number of suricata alerts that need to be suppressed.

I tried to follow the documentation from here:

https://docs.securityonion.net/en/2.3/managing-alerts.html#suppressions

but, obviously I am doing something wrong.

I have tried adding the suppression config in the global.sls and then I tried putting the config in 

`/opt/so/saltstack/local/pillar/thresholding/threshold.sls`  

(both on the master server) but it never seems to get pushed to the other boxes in the cluster.

The content of the threshold.sls file is: (slightly sanitized, of course XXX on my system is set to the correct number)

```
thresholding:
  sids:
    2028383:
      - suppress:
         gen_id: 1
         track: by_dst
         ip: 10.3.130.XXX,10.3.170.XXX
    2028780:
      - suppress:
        gen_id: 1
        track: by_dst
        ip: 10.3.130.XXX,10.3.170.XXX
    2008120:
       - suppress:
         gen_id: 1
         track: by_dst
         ip: 192.168.100.XXX,192.168.100.XXX
    2000488:
      - suppress:
        gen_id: 1
        track: by_dst
        ip: 10.2.1.XXX
```
I have tried adding the same config to the end of the global.sls file (I removed the threshold.sls file before adding the entries to global.sls) but it still doesn't seem to change anything.

I have tried waiting 48 hours, nothing; sudo so-rule-update, nothing; salt set highstate, nothing, reboot ... nope.

Anyone have any idea what I am doing wrong?

**Comment by mtnsec** [comment]
Try putting your rules into `/opt/so/saltstack/local/pillar/minions/<minionid>.sls` instead. :)

**Reply by UMHB-InfoSec** [reply]
Is that the preferred way to manage a distributed environment?  Seems like it would be a bit of a pain.

**Reply by mtnsec** [reply]
I'm not sure really - I couldn't get it working in the global.sls either but it works in my specific minion config for the node. My current setup has just one sensor node so it's not a big deal.  But when I go production I'll have multiple and it will definitely be more cumbersome for rule suppressions I need to duplicate at each node. :(

**Comment by TOoSmOotH** [comment]
If you drop the thresholding in global it gets pushed to all sensors. If you drop it in the individual pillar it gets applied to that specific sensor. 

On the sensor check /opt/so/cond/suricata/threshold.conf and make sure you see it there. If you don't see it there run sudo salt-call state.apply suricata on the sensor and see if it shows up.

**Reply by UMHB-InfoSec** [reply]
@TOoSmOotH 

Thank you for the response, it is still not working but I have some more info that may help.

When I issue the command:

`sudo salt-call state.apply suricata`

I get some red text:

```
----------
          ID: surithresholding
    Function: file.managed
        Name: /opt/so/conf/suricata/threshold.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'None' has no attribute 'gen_id'
     Started: 13:29:23.053588
    Duration: 49.294 ms
     Changes:   

```
and 

```
----------
          ID: so-suricata
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: suricata.surithresholding
     Started: 13:29:23.209515
    Duration: 0.011 ms
     Changes:   
```
and the file /opt/so/conf/suricata/threshold.conf still says:

`##### The thresholding pillar has not been defined`

Is there another log file I should be looking at for more info?  Is this an error others have seen?

Some google-ing seems to point to an error in the pillar config but everything looks fine to my uneducated eye.

**Comment by Masaya-A** [comment, marked as answer]
Indent gen_id, track and ip with at least one more space for 2028780, 2008120 and 2000488.
```
thresholding:
  sids:
    2028383:
      - suppress:
         gen_id: 1
         track: by_dst
         ip: 10.3.130.XXX,10.3.170.XXX
    2028780:
      - suppress:
         gen_id: 1
         track: by_dst
         ip: 10.3.130.XXX,10.3.170.XXX
    2008120:
       - suppress:
          gen_id: 1
          track: by_dst
          ip: 192.168.100.XXX,192.168.100.XXX
    2000488:
      - suppress:
         gen_id: 1
         track: by_dst
         ip: 10.2.1.XXX
```
