### DISCUSSION TITLE
FleetDB and Playbook modules are not loading due to a mysql issue?

### DISCUSSION THREAD

**Discussion by Nolan-Mcfly** [Security-Onion-Solutions/securityonion#4185] [General] [answered]
Hello, I have recently begun working with Security Onion as a home project and I have been having a consistent issue with mysql server and security onion not wanting to work together. I can't seem to find much about this issue on the internet as I have searched all over for about two weeks. Attempting to remedy the situation through different means, uninstalling security onion, docker, mysql, and all other dependencies and starting the process over again did not seem to help, in fact it may have hurt. 

Right now, what I am seeing from doing `sudo cat /root/sosetup.log` is an issue between `FleetDB` and `Playbook`. Mostly all modules are being successfully installed/loading into Docker, but here is a snippet from the logs where the issue arises.

_**I am using Ubuntu 18.04.
I have a static IP setup for the server I'm working on.**_

```
----------
          ID: fleetdb
    Function: mysql_database.present
        Name: fleet
      Result: False
     Comment: One or more requisite failed: mysql.so-mysql
     Started: 21:07:54.333399
    Duration: 0.011 ms
     Changes:   
----------
          ID: fleetdbuser
    Function: mysql_user.present
      Result: False
     Comment: One or more requisite failed: fleet.fleetdb
     Started: 21:07:54.337203
    Duration: 0.006 ms
     Changes:   
----------
          ID: fleetdbpriv
    Function: mysql_grants.present
      Result: False
     Comment: One or more requisite failed: fleet.fleetdb
     Started: 21:07:54.340117
    Duration: 0.006 ms
     Changes:   
----------
```
and
```
----------
          ID: create_playbookdbuser
    Function: mysql_user.present
        Name: playbookdbuser
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on '192.168.0.19' (110)
     Started: 21:08:07.936111
    Duration: 261912.003 ms
     Changes:   
----------
          ID: query_playbookdbuser_grants
    Function: mysql_query.run
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on '192.168.0.19' (110)
     Started: 21:12:29.849936
    Duration: 131064.848 ms
     Changes:   
----------
          ID: query_updatwebhooks
    Function: mysql_query.run
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on '192.168.0.19' (110)
     Started: 21:14:40.915454
    Duration: 131071.339 ms
     Changes:   
----------
          ID: query_updatepluginurls
    Function: mysql_query.run
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on '192.168.0.19' (110)
     Started: 21:16:51.987499
    Duration: 131070.6 ms
     Changes:   
----------
```

So, this mostly looks like a mysql server issue that I am having and I am not sure where to go about this. I have mysql installed, through `sudo apt-get install mysql-server` and I am able to access it, this is what it brings back when I look for Users and Databases. 

```
mysql> SELECT User, Host from mysql.user;
+------------------+-----------+
| User             | Host      |
+------------------+-----------+
| debian-sys-maint | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+

mysql> SHOW DATABASES;
+--------------------+                                                                                      
| Database           |                                                                                      
+--------------------+                                                                                      
| information_schema |                                                                                      
| mysql              |                                                                                      
| performance_schema |                                                                                      
| sys                |                                                                                      
+--------------------+ 
```
Any and all help would be very appreciated, and if you have any questions about anything regarding hardware, software, etc, feel free to ask.

Thank you,

Nolan
