### DISCUSSION TITLE
Curator and Elasticsearch snapshot issues

### DISCUSSION THREAD

**Discussion by facyber** [Security-Onion-Solutions/securityonion#4404] [Unsupported Versions]
Hello community,

I've started working on Curator script that would create snapshot data every few days or so, for testing purposes but I am struggling with some issues and I can't find in documentation information i need.

I have test SO Environment with Manager and 1 Heavy Node, I am sending some wazuh data, that are not important, I only need to get disk space to test backup/restore solutions.

So on Manager node first I have create YML file for snapshot action.

`/opt/so/saltstack/local/salt/curator/files/action/so-curator-snapshot-create.yml`

```
actions:
  1:
    action: snapshot
    description: >-
      Snapshot selected indices to 'repository' with the snapshot name or name
      pattern in 'name'.  Use all other options as assigned
    options:
      repository: my_repository
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name:
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 10
    filters:
    - filtertype: pattern
      kind: regex
      value: '^(logstash-ossec.*|so-ossec.*)$'
    - filtertype: period
      period_type: relative
      source: name
      range_from: -10
      range_to: -1
      timestring: '%Y.%m.%d'
      unit: days
```

Then I created shell script that will execute it, that is based on other scripts that came with SO.

`/opt/so/saltstack/local/salt/curator/files/bin/so-curator-snapshot-create`

```
#!/bin/bash

# Avoid starting multiple instances
APP=snapshotcreate
lf=/tmp/$APP-pidLockFile
# create empty lock file if none exists
cat /dev/null >> $lf
read lastPID < $lf
# if lastPID is not null and a process with that pid exists , exit
[ ! -z "$lastPID" -a -d /proc/$lastPID ] && exit
echo $$ > $lf


docker exec so-curator curator --config /etc/curator/config/curator.yml /etc/curator/action/so-ossec-snapshot-create.yml 2>&1
```

Then I added path.repo where my repository will be and where to store snapshot data.

`/opt/so/saltstack/local/salt/elasticsearch/files/elasticsearch.yml`

`path.repo: /tmp/esbackup`

And finaly created curator actions and cron:

`/opt/so/saltstack/local/salt/curator/init.sls`

```
snapshotcreate:  
  file.managed:
    - name: /usr/sbin/so-curator-snapshot-create
    - source: salt://curator/files/bin/so-curator-snapshot-create
    - user: 934
    - group: 939
    - mode: 755

so-curatorsnapshotcreate:
 cron.present: 
   - name: /usr/sbin/so-curator-snapshot-create > /opt/so/log/curator/snapshot-create.log 2>&1
   - user: root
   - minute: '50'
   - hour: '*'
   - daymonth: '*'
   - month: '*'
   - dayweek: '*'
```

There were also steps for creating ES repository, but that part is nto that important for the issue

Now the issues I am struggling with are as it seems permission issues. Apparently after I apply `salt-call state.apply elasticsearch` if it is not `/tmp` folder, I will always get permission denied issue in Elasticsearch logs and it will broke ES, until I change back to /tmp/something or remove path.repo. Even setting permissions to 777 and executable for everyone does not help, I also tried setting specifically for elasticsearch user, or socore, and I can confirm they can create files in those folders, but still getting Access Denied message. Even tried creating folder in SO folder.

```
Unable to access 'path.repo' (/mnt/backup/curator)
AccessDeniedException: /mnt/backup/curator
```

Second weird thing is that if I set let's say `/tmp/esbackup` folder, my script will work and I can confirm by the logs and with the `curl -k -s -X GET "https://localhost:9200/_snapshot/my_repository/_all" | jq` that the snapshot is created successfully, but there is nothing in `/tmp/esbackup` folder, no data at all. We have Graylog instances and for it I created long custom bash scripts that do snapshots in mounted folder and there I can find snapshot data.

Summary:
* What user do I need to set permissions to in order to perform snapshots (curator or root I guess)?
* Is there something else I am missing in my so far testings, scripts, etc? I didn't changed anything in the default folders, only made copies to local and made changes there.

Hopefully somebody have some proposal or solution, as I would really like to make this work, so I can then propose it to Documentation of SO for others.

In case some more information is needed or logs, do tell me.

Thanks in advance
