### DISCUSSION TITLE
Execute custom curator jobs

### DISCUSSION THREAD

**Discussion by gebhard73** [Security-Onion-Solutions/securityonion#4492] [Show and tell]
This is a short description how to run custom curator jobs. I haven't been able to figure out an "official" way but this seems to work fine as of now. Please comment if there are better ways to do this.

The SO documentation can be found here: https://docs.securityonion.net/en/2.3/curator.html (but is somewhat "brief" ... ;-) )
Update 2021-06-27: The documentation has been enhanced based on the information below, thanks @TheN00bBuilder .

1. Create an action file in `/opt/so/saltstack/local/salt/curator/files/action/`:
This action file defines the parameters of the delete job. For examples see `/opt/so/saltstack/default/salt/curator/files/action/`. The file should be owned by `curator:socore`.

2. Create a script file in `/opt/so/saltstack/local/salt/curator/files/bin/`:
This script file will execute curator with the action file. For excamples see `/opt/so/saltstack/default/salt/curator/files/bin/`.

3. Create saltstack file:
The default curator saltstack file must be altered. Copy `/opt/so/saltstack/default/salt/curator/init.sls`  to `/opt/so/saltstack/local/salt/curator` and add the following parts:
- file.managed section for the script, e.g. 
```
curdel-test:
  file.managed:
    - name: /usr/sbin/so-curator-delete-test
    - source: salt://curator/files/bin/so-curator-delete-test
    - user: 934
    - group: 939
    - mode: 755
```
- cron definition:
```
so-curatordelete-test-cron:
 cron.present:
   - name: /usr/sbin/so-curator-delete-test > /opt/so/log/curator/cron-delete-test.log 2>&1
   - user: root
   - minute: '45'
   - hour: '8'
   - daymonth: '*'
   - month: '*'
   - dayweek: '2-5'
```

4. Restart curator:
`sudo so-curator-restart`

5. Check cronjobs:
`sudo crontab -l`
The new job should be listed. Check the bin file's location, too.

Note: please make sure that you copy modifications / additions introduced by SO updates for `/opt/so/saltstack/default/salt/curator/init.sls` into your customized `/opt/so/saltstack/local/salt/curator/init.sls`. See also https://github.com/Security-Onion-Solutions/securityonion/discussions/4441.
