### DISCUSSION TITLE
Run SSH on a non-standard port

### DISCUSSION THREAD

**Discussion by launchdaemon** [Security-Onion-Solutions/securityonion#4553] [Unsupported Versions] [answered]
I have a standalone install of Security Onion 2.3.52 on Ubuntu 18.04.

I am required to run SSH on a non-standard port.  I understand this shouldn't break anything as it is a standalone instance and port 22 is only used during configuration of any sensors which I don't have.

I have modified `/etc/ssh/sshd_config` to add the new port specification as a second port for SSH to listen on (as I am doing this remotely and don't want to lose access on 22 until I am confident the second port is working) and can see it is then listening on both port 22 and the new port with `netstat -lntp`.

I have read the documentation page regarding the [Host Firewall](https://docs.securityonion.net/en/2.3/firewall.html?highlight=firewall#host-firewall).

On my installation, the directory listed in that article for the location of default rules, `/opt/so/saltstack/default/firewall`, does not exist, should it be `/opt/so/saltstack/default/salt/firewall`?

I can see port 22 defined for SSH in `/opt/so/saltstack/default/salt/firewall/portgroups.yaml` but that should not be modified due to risk of being overwritten by an update.

I have added a new portgroup called `alternate_ssh` by running:

`sudo so-firewall addportgroup alternate_ssh`

then added the new port to it e.g.:

`sudo so-firewall add port alternate_ssh tcp 2222`

and I can then see this entry added with:

`sudo so-firewall listports alternate_ssh tcp`

However, there is no firewall section currently in `/opt/so/saltstack/local/pillar/minions/<HOSTNAME>_<ROLE>.sls`.  In `/opt/so/saltstack/default/salt/firewall/assigned_hostgroups.map.yaml` I can see that for the `standalone` role it includes:

```
      INPUT:
        hostgroups:
          anywhere:
            portgroups:
              - {{ portgroups.ssh }}
```
Should I therefore add:
```
firewall:
  assigned_hostgroups:
    chain:
      INPUT:
        hostgroups:
          anywhere:
            portgroups:
              - {{ portgroups.alternate_ssh }}
```
to `/opt/so/saltstack/local/pillar/minions/<HOSTNAME>_<ROLE>.sls`.

I had tried to work out if I could do it with `so-firewall` but that does not list the `anywhere` hostgroup.

**Comment by launchdaemon** [comment]
Additionally, if I only want SSH to be run on the non-standard port, would calling the group just `ssh` essentially overwrite the default `ssh` group to only use the new port?

**Comment by m0duspwnens** [comment]
Hi @launchdaemon. 

Thanks for pointing out the error in the documentation. It has been updated to reflect the proper path of `/opt/so/saltstack/default/salt/firewall`. 

You should be able to add the following to `/opt/so/saltstack/local/salt/firewall/assigned_hostgroups.local.map.yaml`, under each role that you want to open the new ssh port. 

For example:

```
role:
  manager:
    chain:
      INPUT:
        hostgroups:
          anywhere:
            portgroups:
                - {{ portgroups.alternate_ssh }}
  searchnode:
    chain:
      INPUT:
        hostgroups:
          anywhere:
            portgroups:
                - {{ portgroups.alternate_ssh }}
```

As far as overwritting the standard port 22 by just naming the new one ssh, that should work, but I believe there may be a bug with that at the moment. The other issue with trying to the that, is that if we overwrite `ssh` to be 2222, then port 22 will still remain open on the nodes. While it is currently possible to remove port access for IPs in a hostgroup, we don't the ability to remove ports in the same way. To do this across all the nodes, at this time, it would probably be best to make use of the [Salt iptables module](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.iptables.html#salt.modules.iptables).
