### DISCUSSION TITLE
Heavy Node NAT Configuration

### DISCUSSION THREAD

**Discussion by LS3-Allen** [Security-Onion-Solutions/securityonion#4949] [Unsupported Versions]
Distributed deployment running v2.3.60
1 manager
3 heavy nodes

1 of my heavy nodes is connected via site-to-site VPN and is also behind NAT due to IP conflicts with another VPN on my core network.  I have manually allowed the translated IP with so-firewall.  Initially everything worked great, but after several hours communication between the manager and the heavy node stops working.  When I go to the Grid tab the status is ok, but there are 0 EPS.

> Original IP address = 192.168.108.x
> Translated IP address = 192.168.172.x

If I go to the minion .sls file and change the IP address from the translated 192.168.172.x IP address back to the original 192.168.108.x and run state.highstate it will work for a few hours again.  Eventually the communication will stop and I have to go back to the minion .sls file and change the IP address back to the translated IP address.  When I do that I will start to get a massive surge in EPS, but that node will not show up in Hunt or Kibana searches.

Once the EPS surge dies down to normal I go back to the minion .sls file and change the IP back to the original address then run state.highstate again.  Once I do that the EPS will stay at what I call normal, 200-800, and the node will be available in Hunt and Kibana.  However, it only works for maybe 6-8 hours before I have to repeat the cycle again.

Which log file should I be looking at for clues about this problem?  I've looked at the elasticsearch log but all I see in there are deprecated messages.  Is the minion .sls file the correct place I need to be making the IP address changes for the heavy node behind NAT?

**Comment by LS3-Allen** [comment]
Here is the minion .sls config:
```
host:
         mainint: 'em1'
     sensoroni:
         node_address: '192.168.108.x'
         node_description: 'ABI Heavy Node 2'
      
       ntp:
         servers:
           - '0.pool.ntp.org'
           - '1.pool.ntp.org'
      sensor:
        interface: 'bond0'
        mainip: '192.168.108.x'
        mainint: 'em1'
        zeek_pins:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
        suripins:
          - 11
          - 12
          - 13
          - 14
          - 15
        manager: 'bg-soman-01'
        mtu: 1500
        uniqueid: 1626811612
        hnsensor: 192.168.108.0/22
      steno:
        enabled: True
      patch:
        os:
          source: 'manager'
          schedule_name: 'auto'
          enabled: True
          splay: 300
     
      elasticsearch:
        mainip: '192.168.108.x'
        mainint: 'em1'
        esheap: '25000m'
        esclustername: '{{ grains.host }}'
        node_type: 'search'
        es_port: 9200
        log_size_limit: 4502
        node_route_type: 'hot'
     
      logstash_settings:
        ls_pipeline_batch_size: 125
        ls_input_threads: 1
        lsheap: 1000m
        ls_pipeline_workers: 24
```
