### DISCUSSION TITLE
Elastalert error

### DISCUSSION THREAD

**Discussion by kiaraho** [Security-Onion-Solutions/securityonion#5070] [Unsupported Versions] [answered]
I created the following rule and placed it in the `/opt/so/rules/elastalert/` directory as per the documentation.
```
name: malware-detected
index: "*:so-ids-*"
type: frequency
num_events: 1

timeframe:
  seconds: 1

filter:
- query:
    query_string:
      query: "rule.name:malware AND event.severity_label:high"

alert:
- slack

slack:
 - https://hooks.slack.com/services/<redacted>
```
Test completes successfully when running `so-elastalert-test`. However, after I run `so-elastalert-restart` the `so-elastalert` status now reports ERROR. Output of `docker logs so-elastalert` shown below.
```
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py:139: UserWarning: Connecting to https://<redacted>:9200 using SSL with verify_certs=False is insecure.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '<redacted>'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '<redacted>'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Elastic Version: 7.13.2
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation. 
```

**Comment by ericchiles** [comment]
Not sure if you are still having this problem, but I was running into similar problems and it ended up being YAML format/syntax issues. Try changing the end part

slack:
  - https://hooks.slack.com/services/<redacted>
  to
slack_webhook_url: "https://hooks.slack.com/services/<redacted>"

**Reply by kiaraho** [reply]
@ericchiles just to confirm, is this the correct syntax, because I'm still getting errors?

```
name: malware-detected
index: "*:so-ids-*"
type: frequency
num_events: 1

timeframe:
  seconds: 1

filter:
- query:
    query_string:
      query: "rule.name:malware AND event.severity_label:high"

alert:
- slack

slack:
- slack_webhook_url: "https://hooks.slack.com/services/<redacted>"
```
