### DISCUSSION TITLE
Elasticsearch data backup

### DISCUSSION THREAD

**Discussion by facyber** [Security-Onion-Solutions/securityonion#5074] [Show and tell] [answered]
Hello community, just wanted to share possible way of backups of ES data, I did not tested backup and restore with large amount of data, only few GB maybe, but still, maybe someone will get an idea to improve the way.

**Note: Please do test it first on your test environment before production, and of course create a backup/snapshots, whatever.**

My architecture is Manager + Heavy Nodes, so I guess this guide is for that setup as I am not sure if all the files are the same for other types.

**1) Create Curator YML file**

This configuration will first delete all snapshots that are older than 7 days, so we can keep it weekly update which I suggest, because it would be better to keep more smaller backups, than one big, as the big one can take a lot of time for backup depending of your resources and of course there is higher risk for something to happen during the backup so you would need to start all over. If you want to keep more, play a bit with `unit` and `unit_count` values. After it deletes the latest one, it will create a new snapshot of **all** ES data, or better say of **all** indices.

Create a Curator config file in `/opt/so/saltstack/local/salt/curator/files/action/` folder (let's say we name it `so-curator-snapshot-create.yml`):

```
actions:
  1:
    action: delete_snapshots
    description: Delete snapshots older than 7 days
    options:
      repository: my_repository
      disable_action: True
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
  2:
    action: snapshot
    description: Weekly snapshot of all Elasticsearch data.
    options:
      repository: my_repository
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: 'curator-%Y%m%d%W-%H%M%S'
      include_global_state: True
      partial: False
      wait_for_completion: True
      # -1 for max_wait means it will wait indefinitely for the action to complete.
      # It should be used for testing on larger amount of data to see how long will it take to create a snapshot
      max_wait: 3600
      wait_interval: 10
    filters:
    - filtertype: period
      period_type: relative
      source: name
      range_from: -1
      range_to: -1
      timestring: '%Y.%m.%d'
      unit: weeks
      week_starts_on: monday
```

Apply changes with `sudo salt-call state.apply curator`

**2) Create Curator BASH script**

Then you need to create a Curator BASH script that will execute the Curator script through the Docker. This was basically just a copy and edited version of some other script that came with SO.

```
#!/bin/bash

# Avoid starting multiple instances
APP=snapshotcreate
lf=/tmp/$APP-pidLockFile
# create empty lock file if none exists
cat /dev/null >> $lf
read lastPID < $lf
# if lastPID is not null and a process with that pid exists , exit
[ ! -z "$lastPID" -a -d /proc/$lastPID ] && exit
echo $$ > $lf


docker exec so-curator curator --config /etc/curator/config/curator.yml /etc/curator/action/so-curator-snapshot-create.yml 2>&1
```

**3) ES backup folder**

For this part I will first show config files and then explain how it works (at least I believe it works like this hehe). for the purpose of example, let's say you have mounted shared backup folder at location `/mnt/sharedfolder`, wher you will first create a folder `esdata`.

Then inside the Elasticsearch container create `/tmp/esdata` folder:

a) `docker ps | grep elasticsearch` to get ES container ID
b) `docker exec -u root -it <ES_ID> bash`
c) `mkdir /tmp/esdata`
d) `exit` to exit the container

Then edit `/opt/so/saltstack/local/salt/elasticsearch/files/elasticsearch.yml` and add `path.repo: /tmp/esdata` just bellow `path.logs`.

Then edit `/opt/so/saltstack/local/salt/elasticsearch/init.sls` and under `so-elasticsearch` -> `binds` add `/mnt/sharedfolder/esdata:/tmp/esdata:rw`, so it should look something like this:

```
so-elasticsearch:
- binds:
   - /opt/so/conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
   - /opt/so/conf/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
   - /nsm/elasticsearch:/usr/share/elasticsearch/data:rw
   - /opt/so/log/elasticsearch:/var/log/elasticsearch:rw
   - /opt/so/conf/ca/cacerts:/etc/pki/ca-trust/extracted/java/cacerts:ro
   - /mnt/sharedfolder/esdata:/tmp/esdata:rw
```
Then use `sudo salt-call state.apply elasticsearch` or maybe `sudo salt-call state.highstate` to apply changes.

Now explanation: When a curator creates a snapshot, a noticed that it create it inside the Docker container, not the outside of it, therefor the only folder where we are able to write data is `/tmp` folder, which is the reason why we create `/tmp/esdata` folder so we can keep data there. The value `/mnt/sharedfolder/esdata:/tmp/esdata:rw` will then link the folder inside the container to the folder outside of it, on our mounted shared folder, so when the snapshot data is create inside the `/tmp/esdata`, they will also be available on shared folder. If you delete something from inside the container, it will also be deleted from outside folder, so I suggest you to create additional BASH script that will copy/move data from mounted shared folder to another one just to be safe.

**4) Create a cronjob**

Make a copy of `/opt/so/saltstack/default/salt/curator/init.sls` to `/opt/so/saltstack/local/salt/curator/init.sls` if you don't already have one and add the following somewhere in the file.

```
snapshotcreate:
  file.managed:
    - name: /usr/sbin/so-curator-snapshot-create
    - source: salt://curator/files/bin/so-curator-snapshot-create
    - user: 934
    - group: 939
    - mode: 755

so-curatorsnapshotcreate:
 cron.present:
   - name: /usr/sbin/so-curator-snapshot-create
   - user: root
   - minute: '0'
   - hour: '0'
   - daymonth: '*'
   - month: '*'
   - dayweek: '1'
```

Apply changes with `sudo salt-call state.apply curator`

And I believe this is it. You can go through Curator Documentation here to see more options to make it more personalized to your environment, as this was more for testing purposes. Feel free to propose changes or if something should be different. 

Cheers
