### DISCUSSION TITLE
Playbook and Office 365 Issues

### DISCUSSION THREAD

**Discussion by Git-Me-Some-Hub** [Security-Onion-Solutions/securityonion#5116] [Unsupported Versions] [answered]
ISO - 2.3.61-Steno 

I am just assuming that this is my own issues understanding Sigma rules, but I am getting a bit confused on what I need to pull specific Office 365 event to alert on. I ultimately want a basic international login alert, but I have other IDS alerts that come in on Syslog (cef, cisco, etc...) that I would want to alert on any, so I am trying to figure out the naming structure. 

Do I use service in the sigma rule for modules in SO? Below is my test to see if I get any alert on any "userloggedIn" Events

```
title: Microsoft o365 - success login03
status: experimental
description: Detects any US login
author: 
date: 
modified: 
references:
logsource:
  service: o365 #tried o365.audit, office365 too
detection:
  selection:
    action: UserLoggedIn
  condition: selection
falsepositives:
- unknown
level: low
tags:

```

Any direction would be appreciated.

**Comment by fluffyunicorn24** [comment, marked as answer]
Ok, I am definitely not a sigma expert, but I have written a few.  What is the log source that you are getting your o365 data?  You need to point it towards the data, like:

logsource:
  product: 
  index: <index where you have 365 logs>

You will also need to tell it more in the detection side.  What in the log shows that the user logged in (selection + condition) ? and does it have geo ip data there? You might have to add a fields section like:

fields:
 - [geoip][ip]
 
I will say your rule that you are trying to write is very broad.  I am sorry I cant help you better.

**Reply by Git-Me-Some-Hub** [reply]
Thank you for the reply, you are correct it is very broad... I wanted it that way so I would make sure it was firing quickly to decide on the correct usage for Office365. Once I can confirm this is correct, and being processed by the processors correctly I was going to start getting more specific. 

The index is the general so-beats*, with event.dataset: o365.audit, event.provider: AzureActiveDirectory

I found a great listing in the master Sigma Github on a break down of this, but I guess I need to know how the processors are working on the data I put in there. 
https://github.com/SigmaHQ/sigma/wiki/Specification 

```
category - examples: firewall, web, antivirus
product - examples: windows, apache, check point fw1
service - examples: sshd, applocker

[...]

You can use the values of 'category, 'product' and 'service' to point the converters to a certain index. 
You could define in theconfiguration files that the category 'firewall' converts to ( index=fw1* OR index=asa* ) 
during Splunk search conversion or the product 'windows' converts to "_index":"logstash-windows*" in 
ElasticSearch queries.

```
**You can use the values of 'category, 'product' and 'service' to point the converters to a certain index.**

**Reply by fluffyunicorn24** [reply]
I unfortunately do not work with those logs but I would think it would be a little like:

logsource:
product:
index: 'so-beats*'
conditions:
   event.dataset: o365.audit 

For the international ip part you need to see how that is being displayed in the log.  I am not sure if it has a geo tag or not.  That will be your next condition.  

I hope this helps a bit.

**Reply by Git-Me-Some-Hub** [reply]
Thanks a lot for the push, I was a little confused on it you needed to use the relative terms or if you could use the very specific field names or not. I just got my first hits. Again it is meant to be broad, but now that I know it is working I will narrow in on what I want. 

```
title: Microsoft o365 - success login04
status: experimental
description: Detects any US login, but filter India
author: Me
date: 2021/08/
modified: 2021/08/
logsource:
  index: so-beats*
detection:
  selection:
    event.dataset:
    - o365.audit
    o365.audit.Operation:
    - UserLoggedIn
    o365.audit.ResultStatus:
    - Success
    source.geo.country_iso_code:
    - US
  filter:
    source.geo.country_iso_code:
    - IN
  condition: selection and not filter
falsepositives:
- unknown
level: low
```

Thanks again!
