### DISCUSSION TITLE
Sysmon/winlogbeat event code 1 events cannot be indexed

### DISCUSSION THREAD

**Discussion by making-maddie** [Security-Onion-Solutions/securityonion#5148] [Unsupported Versions] [answered]
Background: Running SO Appliance 2.3 standalone (Downloaded/Installed < 10 days ago). I am trying to send sysmon logs through winlogbeat to SO. All sysmon logs are able to be ingested except for event code 1 (process creation). Here is the error that I receive:

`response=>{
        "index"=>{
            "_index"=>"so-beats",
            "_type"=>"_doc",
            "_id"=>nil,
            "status"=>400,
            "error"=>{
                "type"=>"illegal_argument_exception",
                "reason"=>"field [process.pe.description] already exists"
            }
        }
    }`

After I created a backup of the sysmon ingest pipeline file and removed the lines that deal with process.pe.description, I received the same error except for the next field, process.pe.product.

Next I removed all lines regarding the process.pe.* fields and elasticsearch started ingesting properly. Obviously this is not ideal, but it got me going. 

Can anyone tell me why that is happening and how to fix it? Thanks.

Here is the discussion that I started on discuss.elastic.co about this issue before I realized it might be unique to SO.
[https://discuss.elastic.co/t/could-not-index-event-due-to-field-already-exists/281229](https://discuss.elastic.co/t/could-not-index-event-due-to-field-already-exists/281229)

[a comment by an automated account is not shown]

**Comment by defensivedepth** [comment, marked as answer]
@dhaynes331 @chris-ci  Which version of Winlogbeat are you using?  

From https://docs.securityonion.net/en/2.3/sysmon.html#winlogbeat

`If you are shipping Sysmon logs via Winlogbeat, confirm that your Winlogbeat configuration does NOT use the Elastic Sysmon module. Security Onion will do all the necessary parsing.`

The FOSS version of winlogbeat is what you are looking for, and is what is available for download in the Security Onion Console under Downloads.

**Reply by making-maddie** [reply]
@chris-ci Please read the answer by @defensivedepth. It is the correct solution

@defensivedepth I am using winlogbeat 7.14 non oss version. I will switch to that. Are you referring to the portion of the winlogbeat.yml config that sets the processors for sysmon? Here is the current config for windows log inputs in my winlogbeat.yml file.

```
winlogbeat.event_logs:
  - name: Security
    processors:
      - script:
          lang: javascript
          id: security
          file: ${path.home}/module/security/config/winlogbeat-security.js
  - name: Microsoft-Windows-Sysmon/Operational
    processors:
      - script:
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js
```

My assumption is that I should remove everything under `  - name: Microsoft-Windows-Sysmon/Operational`

Thank you.
