### DISCUSSION TITLE
How To Find rootfs/nsmfs UIDs

### DISCUSSION THREAD

**Discussion by LS3-Allen** [Security-Onion-Solutions/securityonion#5178] [Unsupported Versions] [answered]
SO 2.3.61
ISO install
Distributed deployment
1 manager, 3 heavy nodes
so-status - elasticsearch missing

I just re-ran setup on one of my heavy nodes.  When setup was finished Elasticsearch was missing and would not start.  Logs indicated an IP address problem so I checked the nodestab.sls and sensorstab.sls on the manager.  I found some of the lines of data were mismatched or missing all together.  I corrected most of it, but the rootfs: line is empty.  What command can I use to find the rootfs UID?

 ```
abi-sonode-02_heavynode:
     ip: 192.168.108.5
     manint: eml
     totalcpus: 24
     guid: s59Or1OfEBU2KIu7
     rootfs:
     nsmfs: 9442002944000
     monint: bond0
```
