### DISCUSSION TITLE
Wazuh never connected

### DISCUSSION THREAD

**Discussion by ThreeEyedRaven-99** [Security-Onion-Solutions/securityonion#5223] [Unsupported Versions] [answered]
Hello! I have an issue connecting wazuh agent to the SO manager. In wazuh endpoint ossec logs it shows:
2021/08/20 17:44:21 ossec-agent: WARNING: Unable to connect to any server.
2021/08/20 17:44:21 ossec-agent: INFO: Closing connection to server (103.x.x.x:1514/udp).
2021/08/20 17:44:21 ossec-agent: INFO: Trying to connect to server

In Wazuh manager it shows agent "Never Connected".
I have allowed the traffic in manager using so-allow. Also, IP is pointed to the manager in ossec configuration. 

I am using SO 2.3.61 distributed on centos7.   

Any help is appreciated. Thanks in advance.

**Comment by weslambert** [comment, marked as answer]
Have you tried checking the ossec log on the manager?  Have you also verified with tcpdump that the agent is actually hitting the correct box, and is not being rejected from the firewall perspective? Could there be NAT or something else going on?

**Reply by abesinger** [reply]
FWIW, check IPtables settings on your receiving host (sensor or manager); I had some problems initially getting Wazuh to work, I had to manually add an entry to the minion pillar file for my sensor node, like this:
```
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          wazuh_agent:
            portgroups:
              - portgroups.wazuh_agent
```
