### DISCUSSION TITLE
Retrive Fortigate 60E syslog with SecurityOnion 2.3.70

### DISCUSSION THREAD

**Discussion by Devil45** [Security-Onion-Solutions/securityonion#5320] [Unsupported Versions]
Hello!
I’m working on a project and the objective is to found a solution to retrieve FortiGate Logs without using FortiAnalyzer. I’ve searched some other solutions and I’ve found SecurityOnion. I installed the eval version and I’ve tried to send those logs to SecurityOnion, but there’re things that I don’t understand:
-	In the fortigate logs configuration, I have to precise the IP address(or FQDN) of the server. But the only IP that I’ve configured, on SecurityOnion, is the management (which is used to access security Onion via navigator). Can it retrieve the logs via this IP (I have some doubts) or does it has to go through the sniffing port?
-	There’s also modules that can be installed for filebeat. And I saw a specific module about Fortinet logs. Does it include Fortigates logs types? 

Maybe it’s not the appropriate version I’m using. I’ve some difficulties to understand certain of those versions.
I appreciate in advance for the attention given to my questions and for the informations and advices provided. If you need more information, let me know.

P.S : Sorry if my English is not the best. I’m from Switzerland.

**Comment by weslambert** [comment]
You should be able to use the Fortinet Filebeat module to achieve this:
```
fortinet:
      firewall:
        enabled: true 
        var.input: udp
        var.syslog_host: 0.0.0.0 
        var.syslog_port: 9004
```

https://docs.securityonion.net/en/latest/filebeat.html?#modules
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-fortinet.html#filebeat-module-fortinet

Then make sure to allow the port using so-firewall, etc:

Ex. : https://docs.securityonion.net/en/latest/firewall.html?highlight=syslog#allow-hosts-to-send-syslog-to-a-sensor-node

**Reply by Devil45** [reply]
Hello !

Thank you for your response. I have put this code in the /opt/so/saltstack/local/pillar/minions/$managername_manager.sls : 
```
filebeat:
  third_party_filebeat:
    modules:
      fortinet:
        firewall:
          enabled: true
          var.input: udp
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9004
```

Does it work the same as the code you provided ?
Also, does this code activate the module ? I've been through the filebeat documentation and there are some commands to enable specific  modules. But if i type this, the command is not recognized : 
```
filebeat modules enable ...
OR
./filebeat modules enable ...
```

Do i need to use it with salt command as input ? How to do it ?

I'll put the firewall rule for allowing the syslog of my fortigate and see the result.
