### DISCUSSION TITLE
Suricata docker reboots every 24h

### DISCUSSION THREAD

**Discussion by sleepingbel** [Security-Onion-Solutions/securityonion#5330] [Unsupported Versions] [answered]
Hello all,

SO standalone install 2.3.40 updated to 2.3.70 Hotfix [GRAFANA_DASH_ALLOW]
ZEEK metadata

8 vCPU
24 GB vRAM
2.5 TB diskspace

After updating from 2.3.61 Hotfix [STENO, MSEARCH] to 2.3.70 Hotfix [GRAFANA_DASH_ALLOW], I did see that the suricata docker reboots every 24h, is this normal?

![Knipsel](https://user-images.githubusercontent.com/29328171/131241224-0ca0d6aa-f71d-4885-b4e3-cdb504463a6d.PNG)

When I look in the suricata logs I don't see any errors (/opt/so/log/suricata/)

regards
Bart

**Comment by Masaya-A** [comment]
Same here.
It seems so-rule-update makes suricata's container restarting when the rule file is updated.
EDIT:
Salt (suricata/init.sls) watches rule directories, so actually restarted by salt.
```
    - watch:
      - file: /opt/so/conf/suricata/suricata.yaml
      - file: surithresholding
      - file: /opt/so/conf/suricata/rules/
      - file: /opt/so/conf/suricata/bpf
```

I think restarting whole suricata (container) is not necessary to apply up-to-date rules. For my RPM installation of suricata, `systemctl reload suricata` `(ExecReload=/bin/kill -USR2 $MAINPID)` works properly.
