### DISCUSSION TITLE
Zeek: Fillingup my disk

### DISCUSSION THREAD

**Discussion by vijaytejak** [Security-Onion-Solutions/securityonion#5332] [Unsupported Versions] [answered]
I have zeek running my disk is filling up, when I see spool is filling up in /nsm/zeek folder, how to automatically remove old data from spool folder

## Outout of /opt/so/saltstack/local/pillar/minions/$SENSORNAME_$ROLE.sls
```
elasticsearch:
  es_port: 9200
  esclustername: '{{ grains.host }}'
  esheap: 5374m
  log_size_limit: 40
  mainint: enp1s0
  mainip: 192.168.0.x
  node_route_type: hot
  node_type: ''
```

## Output of du -sh * in /nsm folder
```
[root@analyst nsm]# du -sh *
780M    backup
13G     docker-registry
40G     elasticsearch
732K    grafana
0       import
1.5G    influxdb
0       logscan
4.0K    logstash
236M    mysql
24K     osquery
1.1M    pcap
0       pcapindex
0       pcapout
0       pcaptmp
706M    repo
4.0K    soc
212K    strelka
0       suricata
2.4M    thehive
44M     wazuh
71G     zeek
```
