### DISCUSSION TITLE
Processing syslog data

### DISCUSSION THREAD

**Discussion by cyb3rz3us** [Security-Onion-Solutions/securityonion#5470] [Unsupported Versions] [answered]
I have my central syslog server forwarding copies of all log data to SO.  This log data is from various different devices such as pfSense, Sophos, Mikrotik, vmWare, Apple, etc.  I know that in some cases, such as Sophos, filebeat modules can be used to process the inbound logs but that seems to be extra work since the same data is already being received via the inbound syslog data stream.

My understand of SO thus far informs me that the logs are currently processed using Zeek and SO's library of pipelines but that does't really do the trick.  So, can't I just build the requisite parsers, indicies, etc. to digest those same already received logs in order to grab the data as desired? 

What I'm also wondering is that since the logs are already being processed, does this mean I need a new copy, so to speak, in order for me to perform additional data harvesting; or can I just add a new pipeline and go from there?

**Comment by abesinger** [comment]
I don't I'll completely answers your question, but here's a couple of things to know.  First, if you want to modify the syslog ingest pipeline, you might want to take a look at what I posted in #5251.

But I suspect you want your own separate pipelines.  So, if you can add the tag `import` and the fields `module` and `dataset` to your log data, logstash will direct the message to an elasticsearch ingest pipeline named `<module>.<dataset>`  And then you can create as many different ingest pipelines as you have different types of logs, without having to modify any of the default SO pipelines.

If you want to understand better how that's happening, take a look at `/opt/so/conf/logstash/pipelines/search/9002_output_import.conf`:

```
output {
  if "import" in [tags] {
    elasticsearch {
      pipeline => "%{module}.%{dataset}"
```

**Comment by dylangerdaly** [comment]
From what I've seen, SO's entire syslog logging service is totally broken, I opened the port, pointed my Mikrotik device at it and expected it to 'just work', I'm not seeing anything come in from the device despite seeing 514 traffic come into the management interface

**Comment by abesinger** [comment]
I'm not quite sure what you did, but I have it working just fine. But there are a few steps required to enable everything.  Here's what I did:

Background: I have a distributed SO deployment. Syslog goes to a sensor node, which has filebeat listening on port 514 by default. You can verify this by looking at `/opt/so/conf/filebeat/etc/filebeat.yml` on the sensor node.

I had to do two things to get it to work:

I used `so-allow` to add the ip address of the log sources to the `syslog` role.  You can verify what's been allowed with `so-firewall includedhosts syslog`

I edited `/opt/so/saltstack/local/pillar/minions/<hostname>_sensor.sls` and made sure it had the following:

```
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          log_sources:
            portgroups:
              - portgroups.syslog
      INPUT:
        hostgroups:
          log_sources:
            portgroups:
              - portgroups.syslog
 ```

Note that I had to add the log_sources/portgroups.syslog relationship under both DOCKER and INPUT.  The SO documentation isn't  completely clear on that. You would think it would only be required in one, but once I put it on both places, it started working just fine.

**Reply by DinhDiesel** [reply]
I have a question regarding this file. I'm in a distributed environment could I send my syslogs to manager since the heavy is like an ext
![so2_manager_slsfile](https://user-images.githubusercontent.com/87437722/136032800-357845cb-fe07-4227-8e84-efbd7d064575.jpg)
ension of the manager?

**Reply by weslambert** [reply]
Please start a new Discussions post with your question to avoid confusion with the main topic of discussion.

**Reply by DinhDiesel** [reply]
@welambert i apologize for that, was not my intention.

**Reply by revast** [reply]
> I edited `/opt/so/saltstack/local/pillar/minions/<hostname>_sensor.sls` and made sure it had the following:
> 
> ```
> firewall:
>   assigned_hostgroups:
>     chain:
>       DOCKER-USER:
>         hostgroups:
>           log_sources:
>             portgroups:
>               - portgroups.syslog
>       INPUT:
>         hostgroups:
>           log_sources:
>             portgroups:
>               - portgroups.syslog
> ```
> 

Looks like **log_sources** is not working for me; When I run  _salt-call state.highstate_ after pasting this, I get an Error:
```
  Rendering SLS 'base:firewall' failed: Jinja variable 'dict object' has no attribute 'log_sources'
```

I had to change it to **syslog**

```
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
         syslog:
            portgroups:
              - portgroups.syslog
      INPUT:
        hostgroups:
          syslog:
            portgroups:
              - portgroups.syslog
```
