### DISCUSSION TITLE
Right configure for external logstash to SO

### DISCUSSION THREAD

**Discussion by n0th1nt0lOOz** [Security-Onion-Solutions/securityonion#5641] [Unsupported Versions]
Hi all
I'm using SO2.3.70 in Distribution Mode
I have an ELK cluster for log centralize
I want to send winlogbeat & linux auditd/syslog to SO in the right way to make it usable in SO for hunt, alert for detection,...

My current logstash.conf pipeline config:

```
input {
        beats {
                port => 5044
                host => "0.0.0.0"
        }

        tcp {
                port => 5000
        }
}

output {
        elasticsearch {
                hosts => "elasticsearch:9200"
                user => "elastic"
                password => "changeme"
                ecs_compatibility => disabled
                index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }

        elasticsearch {
                hosts => "192.168.87.51:9200" // This is the heavynode
                user => "so_elastic"
                password => "nFHrqKrQZV0aRSJYKjf4"
                ecs_compatibility => disabled
                index => "so-beats"
        }
        stdout { codec => rubydebug }
}
```

Is this configure true? anyone could help me on the right way?
Should I use my logtash to save beats log into file and use filebeats to ship this file to SO?

Thanks & Regards

**Comment by n0th1nt0lOOz** [comment]
Hi, anyone could help?

**Comment by clairmont32** [comment]
I'm pretty sure filebeats will be able to support your need to ship the syslogs into SO but you may want to check around the docs for some configs/examples to be sure.

https://docs.securityonion.net/en/latest/logs.html

**Reply by n0th1nt0lOOz** [reply]
Hi @clairmont32 
Now I change from using external logstash to make that external logstash output to a file and use filebeat to ship it to the heavy node. Now I'm trying to ship the winlogbeat log.
Although I allow the beats on manager via so-allow but my filebeat till not connect to the heavy node so I point it to the manager.

On manager node I changed the file /opt/so/saltstack/default/pillar/logstash/manager.sls to:

```
{%- set PIPELINE = salt['pillar.get']('global:pipeline', 'redis') %}
logstash:
  pipelines:
    manager:
      config:
        - so/0009_input_beats.conf
        - so/0010_input_hhbeats.conf
        - so/6700_winlogbeat.conf
        - so/6600_winlogbeat_sysmon.conf
        - so/9999_output_redis.conf.jinja
        - so/9500_output_beats.conf.jinja
        - so/9034_output_syslog.conf.jinja
        - so/9050_output_filebeatmodules.conf.jinja
```
Copy the manager.sls file to /opt/so/saltstack/local/ and then restart logstash and elasticsearch
But nothing come into the logstash. My logstash log:

```
[root@somaster logstash]# docker logs --follow so-logstash
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
```
Nothing change and I don't see any log appear.
Any idea?
Thanks
add the issus #5681
