### DISCUSSION TITLE
Problem when adding beats host

### DISCUSSION THREAD

**Discussion by n0th1nt0lOOz** [Security-Onion-Solutions/securityonion#5681] [Unsupported Versions]
Hi all
I'm using 2.3.70 with distribution mode
I post for the first and last parts of adding beats host process. I don't know why they can't add this
![image](https://user-images.githubusercontent.com/28757980/135024032-2b51b71c-4c92-4534-ba35-8b4dd17c047e.png)
![image](https://user-images.githubusercontent.com/28757980/135024048-d671b01e-8369-4e4e-925c-951a66e92501.png)

The hostgroup file. Don't know why they were not created automatically
![image](https://user-images.githubusercontent.com/28757980/135024399-8f3628f8-6dba-4632-8c54-17da691baff2.png)

This show both on manager and heavy. Should I create myself? Or need a new install/soup?

Thanks

**Comment by n0th1nt0lOOz** [comment]
I checked the doc and set it on my manager
```
[root@somaster infosec]# cat /opt/so/saltstack/local/salt/firewall/hostgroups.local.yaml
firewall:
  hostgroups:
    analyst:
      ips:
        delete: []
        insert: [127.0.0.1, '192.168.87.0/24,10.23.0.161', 10.23.1.183]
    beats_endpoint:
      ips:
        delete: []
        insert: [127.0.0.1, 192.168.87.52]
    beats_endpoint_ssl:
      ips: {delete: null, insert: null}
    elasticsearch_rest:
      ips: {delete: null, insert: null}
    fleet:
      ips: {delete: null, insert: null}
    heavy_node:
      ips:
        delete: []
        insert: [192.168.87.51, 192.168.87.52]
    manager:
      ips:
        delete: []
        insert: [127.0.0.1, 192.168.87.47]
    minion:
      ips:
        delete: []
        insert: [127.0.0.1, 192.168.87.47, 192.168.87.51, 192.168.87.52]
    node:
      ips: {delete: null, insert: null}
    osquery_endpoint:
      ips:
        delete: []
        insert: [127.0.0.1]
    search_node:
      ips:
        delete: []
        insert: [127.0.0.1, 192.168.87.47]
    sensor:
      ips:
        delete: []
        insert: [127.0.0.1, 192.168.87.47, 192.168.87.51, 192.168.87.52]
    strelka_frontend:
      ips: {delete: null, insert: null}
    syslog:
      ips: {delete: null, insert: null}
    wazuh_agent:
      ips: {delete: null, insert: null}
    wazuh_api:
      ips: {delete: null, insert: null}
    wazuh_authd:
      ips: {delete: null, insert: null}
```

Done the `salt \* state.highstate` but till not able to connect to the heavynode

**Comment by n0th1nt0lOOz** [comment]
New update
I changed the file /opt/so/saltstack/default/pillar/logstash/manager.sls to:
```
{%- set PIPELINE = salt['pillar.get']('global:pipeline', 'redis') %}
logstash:
  pipelines:
    manager:
      config:
        - so/0009_input_beats.conf
        - so/0010_input_hhbeats.conf
        - so/6700_winlogbeat.conf
        - so/6600_winlogbeat_sysmon.conf
        - so/9999_output_redis.conf.jinja
        - so/9500_output_beats.conf.jinja
        - so/9034_output_syslog.conf.jinja
        - so/9050_output_filebeatmodules.conf.jinja
```

Copy this file to /opt/so/saltstack/local/ and then restart logstash and elasticsearch
But nothing come into the logstash. My logstash log:
```
[root@somaster logstash]# docker logs --follow so-logstash
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties

```

Any idea?
Thanks
