### DISCUSSION TITLE
Custom playbook plays

### DISCUSSION THREAD

**Discussion by Sahale** [Security-Onion-Solutions/securityonion#5744] [Unsupported Versions] [answered]
Hello!
I need help with creating custom plays. My case: I have "custom" unparsed syslog input (i.e. modproxy log) and I want to create alerts when attack is detected. For example, I want playbook to detect "XSS attack" alerts when this happens. Another example: create alert when antivirus (like Symantec or Kaspersky) detects something in system.
Now I don't understand what I have to do with Playbook, because there is no such sigma ruleset. Please, tell me what steps should I do?
Thanks a lot for your help!

**Comment by clairmont32** [comment, marked as answer]
This video from the SO Essentials intro training video playlist may help.
https://youtu.be/IS2SOlDedPc

**Reply by Sahale** [reply]
Thanks!
I've already seen it and created some well working plays. The only problem is syslog.

Another example: I get syslog from my firewall. In this syslog I can see some blocked traffic from DMZ. Now I want playbook to generate alerts when such traffic appears by detecting interface in syslog message (it's just example, I understand that there could be much better ways). So I create something like that:
```
title: Traffic from DMZ
status: experimental
description: Detects traffic from DMZ.
author: F
logsource:
    product: syslog
detection:
    selection:
        message: "*in:vlan13*"
    condition: selection
falsepositives:
    - None
level: medium
```

When I push convert button I get `message.security:*in:vlan13*`, but I need to get `message:*in:vlan13*`, because unparsed syslog doesn't have `message.security` field, but only `message.keyword`. That's why I cannot create play: it simply doesn't work.
