### DISCUSSION TITLE
Netflow filebeat help needed

### DISCUSSION THREAD

**Discussion by 0nnyx** [Security-Onion-Solutions/securityonion#5781] [Unsupported Versions] [answered]
On SO 2.3.80 and previous, after following the doc at https://docs.securityonion.net/en/2.3/filebeat.html I'm still unable to get any netflow index and don't know where the problem lies.

Additions made to /opt/so/saltstack/local/pillar/minions/securityonion_standalone.sls :

```
filebeat:
  third_party_filebeat:
    modules:
      netflow:
        log:
          enabled: true
          var.netflow_host: 0.0.0.0
          var.netflow_port: 2055

firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          netflow:
            portgroups:
              - netflowPorts

```
_netflow refers to my router IP exporting netflow defined with so-firewall addhostgroup then includehost
netflowPorts refers to so-firewall addportgroup then addport for udp 2055_

I could confirm when applying salt state that the filebeat and firewall additions were parsed without errors. 
However, when checking on Kibana for a new index or checking https://(SO IP)/kibana/app/home#/tutorial/netflowLogs, I get "No data has been received from this module yet".

I tried then copying the /opt/so/saltstack/default/salt/filebeat/ folder to  /opt/so/saltstack/local/salt/filebeat/ and change init.sls to add udp 2055 in the port bindings. This didn't improve.

Looks to me like either the filebeat module is not fully enabled either the port isn't forwarded to filebeat. Note I'm sure my netflow export works as I have another ELK instance getting netflow data properly.
