### DISCUSSION TITLE
WinlogBeats and Sysmon not seeing all events

### DISCUSSION THREAD

**Discussion by Git-Me-Some-Hub** [Security-Onion-Solutions/securityonion#5904] [Unsupported Versions] [answered]
(ISO, 2.3.70 - Manager + Search)
I have tried to post this in the Elastic Discuss Forum, but to me that does not seem very active. Thought maybe out of all the smart people I could get some traction. 
- https://discuss.elastic.co/t/winlogbeat-sysmon-module-and-even-code-1-missing/285620 

My issue is that I am using Winlogbeats and Sysmon to send Windows events to SO. 

The problem is that I am not receiving any Sysmon eventid: 1 events in SO. I am not limiting the sending of these logs events, and I am able to confirm that I can see them in the event viewer.... yet nothing is searchable in SO. 

Any ideas? 

Event Viewer: 
![image](https://user-images.githubusercontent.com/17930434/137515505-67e01e2d-f952-4ba2-b5ad-a43e006bc3fb.png)

Log Specifics: 
![image](https://user-images.githubusercontent.com/17930434/137515552-825b45cd-d283-4a81-a308-242c75cbb302.png)

SO Dashboard view of Event IDs: 
![image](https://user-images.githubusercontent.com/17930434/137515607-1b77a191-88fe-4f88-aefc-c6e029c4e2c6.png)

**Comment by dougburks** [comment, marked as answer]
sysmon process creation logs seem to be working fine for me. Here's an example:
https://blog.securityonion.net/2021/10/quick-evtx-analysis-meterpreter.html

Are you able to duplicate this issue on a fresh installation?

**Reply by Git-Me-Some-Hub** [reply]
Thanks Doug. so I went and did the same look at my home lab verse my production server, and I am seeing the same thing. I will note it if  a different version too, o I will go ahead an update it. Can you tell me if you are also using Winlogbeats or some other logging shipper?

I do not use Hunt all that much, but I did go ahead and get what I think you are looking for. I will note this server does get turned off an on at times.
Hunt:
![![image](https://user-images.githubusercontent.com/17930434/138804513-40d3bc96-c923-4d49-9dd7-fcd9115bdfcc.png)](https://user-images.githubusercontent.com/17930434/138804482-408f3e08-1d25-48d4-872b-ba0adc526bd5.png)


Kibana:
![image](https://user-images.githubusercontent.com/17930434/138804491-bd1e5444-306f-4275-acb1-5b43ab1249ea.png)


Event Viewer:
image

Winlogbeats Config: I believe this is the default config, as it is different from my Production environment.

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h

  - name: System

  - name: Security
    processors:
      - script:
          lang: javascript
          id: security
          file: ${path.home}/module/security/config/winlogbeat-security.js

  - name: Microsoft-Windows-Sysmon/Operational
    processors:
      - script:
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js

  - name: Windows PowerShell
    event_id: 400, 403, 600, 800
    processors:
      - script:
          lang: javascript
          id: powershell
          file: ${path.home}/module/powershell/config/winlogbeat-powershell.js

  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103, 4104, 4105, 4106
    processors:
      - script:
          lang: javascript
          id: powershell
          file: ${path.home}/module/powershell/config/winlogbeat-powershell.js

  - name: ForwardedEvents
    tags: [forwarded]
    processors:
      - script:
          when.equals.winlog.channel: Security
          lang: javascript
          id: security
          file: ${path.home}/module/security/config/winlogbeat-security.js
      - script:
          when.equals.winlog.channel: Microsoft-Windows-Sysmon/Operational
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js
      - script:
          when.equals.winlog.channel: Windows PowerShell
          lang: javascript
          id: powershell
          file: ${path.home}/module/powershell/config/winlogbeat-powershell.js
      - script:
          when.equals.winlog.channel: Microsoft-Windows-PowerShell/Operational
          lang: javascript
          id: powershell
          file: ${path.home}/module/powershell/config/winlogbeat-powershell.js
```

**Reply by dougburks** [reply]
That doesn't look like the default config for Winlogbeat OSS. Please try following the directions here:
https://docs.securityonion.net/en/2.3/beats.html#winlogbeat

**Reply by Git-Me-Some-Hub** [reply]
Doh, I missed a very important part of it before.... Shoot. 
`If you are shipping Sysmon logs, confirm that your Winlogbeat configuration does NOT use the Elastic Sysmon processing module as Security Onion will do all the necessary parsing.`

I am using the default Winlogbeat from Beats Github, so that must be my problem... that I created by not following directions. Much appreciated. I will confirm if I see them after the change. 

Thanks!

**Reply by Git-Me-Some-Hub** [reply]
Ok, I am trying not to be an idiot here, but I feel like I have done as instructed on the site. I have removed the processor rules, and have just the sysmon operational logs being forwarded, but now I get no (event.module) sysmon logs at all from those clients just the normal eventlog selections. 

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 168h
  - name: System
    ignore_older: 168h
  - name: Security
    ignore_older: 168h
  
  - name: "Microsoft-Windows-TaskScheduler/Operational"
    ignore_older: 168h
    
  - name: "Microsoft-Windows-Application-Experience/Program-Inventory"
    event_id: 903,904
    ignore_older: 168h    
  
  - name: Microsoft-Windows-TerminalServices-RDPClient/Operational
    event_id: 23,24,25,1102
    ignore_older: 168h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Admin
    event_id: 23,24,25,1102
    ignore_older: 168h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    event_id: 23,24,25,1102
    ignore_older: 168h
    
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurity
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurityVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/FirewallVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Network Isolation Operational
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h  
  - name: "Microsoft-Windows-WindowsUpdateClient/Operational"
    event_id: 20,24,25,31,34,35
    ignore_older: 168h  
  

  - name: Microsoft-Windows-Sysmon/Operational
    ignore_older: 168h
  - name: Windows PowerShell
    event_id: 400, 403, 600, 800
  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103, 4104, 4105, 4106
  - name: ForwardedEvents
    tags: [forwarded]
--------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["siem01p.domain.com:5044"]
```


The installation diretories are not the same as the normal Winbeats install, but I have used your Fields file and my own config file. 
![image](https://user-images.githubusercontent.com/17930434/139099644-7021baf3-ea4c-4a4f-9fe2-32d19e1308d4.png)

Winlogbeats says it is sending the logs? 
![image](https://user-images.githubusercontent.com/17930434/139100061-ad26dd8b-411b-44c8-b8e6-75bd82ab2fef.png)

**Reply by Git-Me-Some-Hub** [reply]
I am getting my Homelab to work right away, just like you expected... Now I have to see what may be wrong in the production environment that I can attribute it...

**Reply by Git-Me-Some-Hub** [reply]
HomeLab works fine - 2.3.80:ISO:SearchManager(1x)
Production NOT working - 2.3.80:ISO:Manager+Search+Forwarder(3x)

I just updated my production version to 2.3.80 as I was having the issue on a previous version. This has not fixed anything. I have confirmed the winbeat version 7.13.4 is the same on both Home and Prod. I copied over the Winbeats config from Prod to Home and all is still working at home. 

Same: 
- SO version
- WinlogBeats Version
- WinlogBeats Config


That leaves something else in Prod that is not properly parsing the syslogs, maybe? Because as I showed the winbeats logs shows they are being shipped, and the eventlog as coming in just fine.  
![image](https://user-images.githubusercontent.com/17930434/139150927-2784d053-4d8a-4e42-81bd-74145a64b9d6.png)

Any ideas on where to look for troubleshooting?

**Reply by dougburks** [reply]
Are you still using the standard Winlogbeat download from the Elastic site?  Have you tried the Winlogbeat OSS version that we include on our SOC Downloads page?

**Reply by Git-Me-Some-Hub** [reply]
So I did try the latest version from the SO download page, but I did not get it to work. I then moved the directory over to my normal install directory, but it did not fix anything. I then download new bits from elastic on v.7.13.4 and placed the yml file back in there and it worked out of the gate. I did notice the fields file was a different size form OSS version.  I am all good, but it not sure what was up with the version, so I have an other version 7.11.x version that worked with just a yml update push. 

I will have to go back and test the OSS version once more on a fresh box and see what I did wrong. 

I do appreciate the push to keep looking.

**Reply by faurkaurage** [reply]
> That doesn't look like the default config for Winlogbeat OSS. Please try following the directions here: https://docs.securityonion.net/en/2.3/beats.html#winlogbeat

I am using Security Onion 2.3.80 and the download page offers the winlogbeat MSI file (7.13.4). I'm not very familiar with installing and configuring winlogbeats via the MSI as I normally use the Zip folder option. 

Questions:
1. Are there any clear directions posted on how to install/configure winlogbeats via the MSI method?
2. Is there any major differences between the winlogbeat MSI file hosted on the SO download page versus the one from the elastic.co website?

I'm having the exact same issue as Mr. @Git-Me-Some-Hub and have been troubleshooting for ~5 hours and my brain is ready to explode. Any thoughts or assistance would be greatly appreciated.

**Reply by faurkaurage** [reply]
> So I did try the latest version from the SO download page, but I did not get it to work. I then moved the directory over to my normal install directory, but it did not fix anything. I then download new bits from elastic on v.7.13.4 and placed the yml file back in there and it worked out of the gate. I did notice the fields file was a different size form OSS version. I am all good, but it not sure what was up with the version, so I have an other version 7.11.x version that worked with just a yml update push.
> 
> I will have to go back and test the OSS version once more on a fresh box and see what I did wrong.
> 
> I do appreciate the push to keep looking.

Hello Mr. @Git-Me-Some-Hub, my team is facing the exact same problem as you described. Were setting up a lab environment and no matter what we do we can not see any SYSMON event logs in Security Onion (minus the event id 5). Can you explain again exactly what you did to resolve your issue.  Did you end up using an older version of winlogbeats? 

Right now i'm using the below

Security Onion: 2.3.80
Winlogbeats: 7.13.4
Sysmon: 13.24  also tried 13.30 released last week but same results 

Thank you so much for all the insight and any help you can provide

**Reply by Git-Me-Some-Hub** [reply]
Hey @faurkaurage, 

So I had not really used the MSI, and I think I ended up putting the config file in the wrong spot, but I just tested and I got it working. 

MSI Directories: 
Logs: C:\ProgramData\Elastic\Beats\winlogbeat\logs
Config/Fields: C:\ProgramData\Elastic\Beats\winlogbeat
Current Running Config: C:\ProgramData\Elastic\Beats\winlogbeat\data\.winlogbeat
- Make sure this lists all the event channels you want to ship. 
- Download out of SO Console. 

ZIP Directories: 
Logs: C:\ProgramData\winlogbeat\logs
Config/Fields: C:\Program Files\Winlogbeat
Current Running Config: C:\ProgramData\winlogbeat\.winlogbeat
- Make sure this lists all the event channels you want to ship. 
- https://www.elastic.co/downloads/past-releases/winlogbeat-7-13-4

I don't think it  matters on your Sysmon version, I am currently using both the last one and latest version. If you are getting events in your Event Viewer log location it should ship. I was looking to see Process creations, Event ID 1, so I opened a cmd prompt and typed in whoami over and over to test. You might want to do something easy like that. 

Let me know if that helps. 

Edit: 
I did not answer one part, I think the main thing that was wrong with me was the config file and processors. Below is what I have working on my workstations. I removed event id 2 and 3 because they are noisy, and I have other things checking that data. For Sysmon, most would want all events, not what I limited it to (event_id: 1, 4-255). 
The issues I had with my production was two-fold; probably not knowing the proper location for the config, and one machine had a newer version of Winlogbeats... though I have not gone back and confirmed the 7.15.1 does not work, just not recommended.

**Reply by faurkaurage** [reply]
@Git-Me-Some-Hub, Dude!! Thank you so much!!

I finally figured out my issue after so many hours and it was such a simply issue. In hindsight I realize that I didn't quite fully understand what was meant by 

> "If you are shipping Sysmon logs, confirm that your Winlogbeat configuration does NOT use the Elastic Sysmon **processing module** as Security Onion will do all the necessary parsing."

I thought I had to comment/delete the **ENTIRE SYSMON** portion of the config, but after analyzing your config I realized I still needed to 'call' the SYSMON name and event ids but just erase everything under 'processors' 

**BAD** for Security Onion with SYSMON
  - name: Microsoft-Windows-Sysmon/Operational
    processors:
      - script:
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js

**Good** for Security Onion with SYSMON
  - name: Microsoft-Windows-Sysmon/Operational

Now on to working with Caldera. You the Man, thanks again for your help

**Reply by dougburks** [reply]
I've updated https://docs.securityonion.net/en/2.3/beats.html to say:

> If you are shipping Sysmon logs, confirm that your Winlogbeat configuration simply collects the Sysmon logs and does NOT use the Elastic Sysmon `processors` section as Security Onion will do all the necessary parsing.

**Comment by Git-Me-Some-Hub** [comment]
For anyone down the road that would like to know what my winlogbeats.yml looks like. One of the Channels is not something I have in my event log, but I think it will be in the future. 

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 168h
  - name: System
    event_id: 104,102,1102,4719,6005,7022,7023,7024,7025,7026,7031,7032,7034,7045,4697,7022,7023,104,6
    ignore_older: 168h
 
  - name: "Microsoft-Windows-TaskScheduler/Operational"
    ignore_older: 168h
   
  - name: "Microsoft-Windows-Application-Experience/Program-Inventory"
    event_id: 903,904
    ignore_older: 168h     
  - name: Microsoft-Windows-TerminalServices-RDPClient/Operational
    event_id: 23,24,25,1102
    ignore_older: 168h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Admin
    event_id: 23,24,25,1102
    ignore_older: 168h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    event_id: 23,24,25,1102
    ignore_older: 168h 
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurity
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurityVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/FirewallVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Network Isolation Operational
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 168h
  - name: "Microsoft-Windows-WindowsUpdateClient/Operational"
    event_id: 20,24,25,31,34,35
    ignore_older: 168h   
  - name: Security
    event_id: 4740,4728,4732,4756,4735,4724,4625,4648,1102,4624,5038,6281,4634
    ignore_older: 168h

  - name: Microsoft-Windows-Sysmon/Operational
    event_id: 1, 4-255
  - name: Windows PowerShell
    event_id: 400, 403, 600, 800
  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103, 4104, 4105, 4106
  - name: ForwardedEvents
    tags: [forwarded]
```
