### DISCUSSION TITLE
No port forwarding for added filebeat inputs

### DISCUSSION THREAD

**Discussion by Sahale** [Security-Onion-Solutions/securityonion#5956] [Unsupported Versions] [answered]
Hello.
SO 2.3.80. I added another UDP input as in the [example](https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/filebeat/pillar.example)
```
filebeat:
  config:
    inputs:
      - type: udp
         enabled: true
         host: "0.0.0.0:2514"
         fields:
           module: n
           dataset: n
         pipeline: "n"
         index: "n"
         fields_under_root: true
```
And the same for tcp. Restarted with `state.apply filebeat` and didn't find new ports forwarding in docker:
`e498bf95a219   node-with-modified-filebeat:5000/security-onion-solutions/so-filebeat:2.3.80        "/usr/local/bin/dock…"   18 minutes ago   Up 18 minutes         0.0.0.0:514->514/tcp, 0.0.0.0:5066->5066/tcp, 0.0.0.0:514->514/udp                                         so-filebeat`

I entered filebeat docker to make sure I got actual config and it looks like everything ok here:
```
[root@so-filebeat filebeat]# cat filebeat.yml  | grep 2514
  host: 0.0.0.0:2514
  host: 0.0.0.0:2514
```
What I have to do to make docker ports available?
