### DISCUSSION TITLE
Elasticsearch templates

### DISCUSSION THREAD

**Discussion by Sahale** [Security-Onion-Solutions/securityonion#6004] [Unsupported Versions] [answered]
Hi,
I have a question about custom template file location. According to file `/opt/so/saltstack/default/salt/elasticsearch/templates/custom/place_custom_template_in_local`, I have to place files `/opt/so/saltstack/local/salt/logstash/pipelines/templates/custom/`.
I created jinja-file, added it there on manager, restarted logstash on node and didn't find new file. Changed jinja to simple json - didn't help, moved file to `/opt/so/saltstack/local/salt/elasticsearch/templates/custom/` - neither.
Where should I place custom templates? Thanks!

**Comment by lan94** [comment]
I'm not quite sure what you're trying to accomplish. Do you want to add Logstash pipelines or Elasticsearch templates?

For **Elasticsearch templates**:

Looking at the default elasticsearch configuration file (`/opt/so/saltstack/default/salt/elasticsearch/init.sls`), it appears that these templates are managed and copied into place when elasticsearch is started. There you will find the following paragraph:

```
#sync templates to /opt/so/conf/elasticsearch/templates  
{% for TEMPLATE in TEMPLATES %}  
es_template_{{TEMPLATE.split('.')[0] | replace("/","_") }}:  
  file.managed:  
    - source: salt://elasticsearch/templates/{{TEMPLATE}}
    {% if 'jinja' in TEMPLATE.split('.')[-1] %}
    - name: /opt/so/conf/elasticsearch/templates/{{TEMPLATE.split('/')[1] | replace(".jinja", "")}}
    - template: jinja
    {% else %}
    - name: /opt/so/conf/elasticsearch/templates/{{TEMPLATE.split('/')[1]}}
    {% endif %}
    - user: 930
    - group: 939
```
You said you restarted logstash, but did you also try restarting elasticsearch?

For **Logstash Pipeline**:

If you place template files in the `/opt/so/saltstack/local/salt/logstash/pipelines/config/custom/` directory, you must also add this pipeline in the global definition file `/opt/so/saltstack/local/pillar/global.sls`. There you can add and define all logstash pipelines that will be used. For example:

```
logstash:
  pipelines:
    search:
      config:
        - so/0900_input_redis.conf.jinja
        - so/9000_output_zeek.conf.jinja
        - so/9002_output_import.conf.jinja
        - so/9034_output_syslog.conf.jinja
        - so/9100_output_osquery.conf.jinja
        - so/9400_output_suricata.conf.jinja
        - so/9500_output_beats.conf.jinja
        - so/9600_output_ossec.conf.jinja
        - so/9700_output_strelka.conf.jinja
        - custom/9599_output_ossec.conf.jinja
```
