### DISCUSSION TITLE
Wazuh agents not connecting to sensors

### DISCUSSION THREAD

**Discussion by PatRussell87** [Security-Onion-Solutions/securityonion#6012] [Unsupported Versions] [answered]
ver. 2.3.80 in a distributed environment

Having issues with Wazuh agents connecting to sensors. I've worked through every post I can find on this and none of the accepted solutions are working for me. From what I can tell, the sensors are not getting the firewall state applied from the master node. When attempting to update using 'salt-call state.apply firewall' on the master there are no errors. Running the same command on either of my sensors results in several fails, all similar to the example below :
`----------
          ID: insert_DOCKER_USER_wazuh_agent_172.xx.xx.xx_1514_tcp_14
    Function: iptables.insert
      Result: False
     Comment: Failed to set iptables rule for insert_DOCKER_USER_wazuh_agent_172.xx.xx.xx_1514_tcp_14.
              Attempted rule was /sbin/iptables --wait -t filter -I DOCKER_USER 1 -p tcp --dport 1514 --source 172.xx.xx.xx --jump ACCEPT
     Started: 17:04:24.866347
    Duration: 92.685 ms
     Changes:
----------`

I've modified the pillar .sls files to include the host groups/port groups as indicated in several solutions and can see the proper entries in the hostgroups.local.yaml file on my master node.

Not sure what else to do...going directly to the master node with host information is not an option for my use case.

Pat

**Comment by solo-securing** [comment]
1. sudo so-firewall addhostgroup wazuhtosensor
2. sudo so-firewall includehost wazuhtosensor "HOST_IP"
3. Add this text to /opt/so/saltstack/local/pillar/minions/<SENSOR_HOSTNAME>_<SENSOR>.sls
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER: 
        hostgroups:
          wazuhtosensor:
            portgroups:
              - portgroups.wazuh_agent
4. On MASTER run "sudo salt <HOSTNAME>_<ROLE> state.apply firewall". Or run "sudo salt-call state.apply firewall" from NODE you want to open port.

Reference: https://docs.securityonion.net/en/2.3/firewall.html

**Reply by PatRussell87** [reply]
I have followed those steps. It's the final one, to apply the updates via salt, that give multiple errors like the example in my original post.

**Comment by PatRussell87** [comment]
Follow-up question:

Should I see the firewall yaml files on a sensor? Neither of mine have them in the same directory that the master does. I believe this is what is causing the errors when trying to apply the firewall salt state.

**Reply by samuel809** [reply]
i was having the same issue, tried the @NgoQuangThien and worked for me.

**Comment by PatRussell87** [comment]
I will walk through those steps again tomorrow and see what happens.

**Reply by PatRussell87** [reply]
I have followed the steps listed above (and in the docs) several times, both before and after reinstalling the sensor. No change. The firewall changes are not applying to the sensor node. I get the same errors as noted in my post above.

There are no network blocks between the manager and sensor, the firewall files just don't appear to be transferred so the update errors out.

Any thoughts on how I can confirm that the sensor is actually able to get the firewall config from the manager?

**Reply by samuel809** [reply]
have you define the agent on the **sensor** for wazuh?
please make sure you specify the sensor ipaddress on the wazuh client.

docker exec -u 0 -it so-wazuh /var/ossec/bin/agent_control -lc

should tell you if the agent connected.

**Comment by PatRussell87** [comment]
@samuel809 - I have added the agent to the sensor and extracted the key for it. It is unable to connect due to the firewall rules not getting updated from the manager node. I also cannot add endpoints locally using the so-allow command. Here is the error from trying so-allow:

> <Traceback (most recent call last):
>   File "/usr/sbin/so-firewall", line 392, in <module>
>     main()
>   File "/usr/sbin/so-firewall", line 382, in main
>     code = cmd(options, args[1:])
>   File "/usr/sbin/so-firewall", line 303, in includehost
>     result = addIp(args[0], args[1], 'insert')
>   File "/usr/sbin/so-firewall", line 101, in addIp
>     content = loadYaml(hostgroupsFilename)
>   File "/usr/sbin/so-firewall", line 73, in loadYaml
>     file = open(filename, "r")
> FileNotFoundError: [Errno 2] No such file or directory: '/opt/so/saltstack/local/salt/firewall/hostgroups.local.yaml'>

**Reply by samuel809** [reply]
i had the same while trying the so-allow on the foward sensor node, this has to be treated by the so-firewall salt config.
please try updating the salt config from de sensor, if you had made the changes on the manager to the sensor_role.sls, log in to the sensor and execute a "sudo salt-call state.apply"

and what are you seeing in the agent wazuh log?

**Reply by PatRussell87** [reply]
@samuel809 - I have updated the sensor .sls file on the manager, but when running the state.apply command on the sensor I get the errors noted in my original post:

> ----------
          ID: insert_DOCKER_USER_wazuh_agent_172.xx.xx.xx_1514_tcp_14
    Function: iptables.insert
      Result: False
     Comment: Failed to set iptables rule for insert_DOCKER_USER_wazuh_agent_172.xx.xx.xx_1514_tcp_14.
              Attempted rule was /sbin/iptables --wait -t filter -I DOCKER_USER 1 -p tcp --dport 1514 --source 172.xx.xx.xx --jump ACCEPT
     Started: 17:04:24.866347
    Duration: 92.685 ms
     Changes:
----------

Nothing I have tried, short of a complete redeploy of my environment, seems to change anything. I have this issue on two sensors, each in a different environment but connected to the same manager. All other data is getting back to the manager from these sensors as long as I don't have to do anything with the firewalls.

**Reply by samuel809** [reply]
please share your /opt/so/saltstack/local/pillar/minions/<HOSTNAME>_<ROLE>.sls config

**Comment by PatRussell87** [comment]
Here it is (ips redacted) : 
```
host:
 mainint: 'ens160'
sensoroni:
 node_address: '172.yyy.yyy.yyy'
 node_description: ''
ntp:
 servers:
   - '172.yyy.yyy.yyy'
sensor:
  interface: 'bond0'
  mainip: '172.yyy.yyy.yyy'
  mainint: 'ens160'
  zeek_lbprocs: 1
  suriprocs: 1
  manager: 'so-manager'
  mtu: 1500
  uniqueid: 1635430972
steno:
  enabled: True
  bpf:
   - not port 443
patch:
  os:
    source: 'manager'
    schedule_name: 'manual'
    enabled: True
    splay: 300
suricata:
 config:
   vars:
     address_groups:
       EXTERNAL_NET: "!HOME_NET"
firewall:
 assigned_hostgroups:
   chain:
     DOCKER_USER:
       hostgroups:
         wazuh_agent:
           portgroups:
             - portgroups.wazuh_agent
```
