### DISCUSSION TITLE
Playbook filtering using IP keywords

### DISCUSSION THREAD

**Discussion by hacker0ni** [Security-Onion-Solutions/securityonion#6122] [Unsupported Versions] [answered]
Hey everyone!

I'm trying to write a Play but it doesn't seem to be working. I've read in a lot of discussions that the .security field is required. Currently I'm ingesting OSQuery logs, mapping the columns to related fields to visualize them in Hunt and these fields include source.ip, destination.ip etc. But by default I have the source.ip.keyword generated and no source.ip.security. Is this the reason why my play isn't working ? Here's the example Play:
```
title: My Play
description: this looks for unknown IPs in the my_query result
status: experimental
author: somedude
tags:
logsource:
  product: osquery
  index: "*:so-osquery-*"
  conditions:
    event.module: 'osquery'
detection:
  selection:
    source.ip:
      - 192.168.0.1
      - 192.168.0.2
  filter:
    event.query: '*custom_events'
  condition: filter and not selection
falsepositives:
- unknown
level: medium
```
When I convert the play, I get an ES query that looks for exactly what I want, but somehow I'm not getting any alerts from playbook in Hunt or Kibana. Thanks in advance!

**Comment by defensivedepth** [comment, marked as answer]
Can you post the ES query that is generated?

**Reply by hacker0ni** [reply]
The ES query looks like the following:
```
(event.module.security:"osquery" AND event.query.security:*custom_events AND (NOT (source.ip.keyword:(192.168.0.1 OR 192.168.0.2))))
```
the custom_events has a prefix of the pack name sent by osquery so I had to use a wildcard. If I don't use a wildcard, the generated query will try to escape forward slashes with a backslash and that won't work in ES. Say the full name is `pack/custom_pack/custom_events` the ES query will look like `... AND event.query.security:pack\/custom_pack\/custom_events ...` So I used a wildcard to address that issue. When I paste the ES query in Kibana, I see the results I want to see, but somehow I'm not getting any Playbook alerts even when I generate new logs that should trigger the alert. Thanks for the response!

**Reply by defensivedepth** [reply]
Just to cover the bases - Can you confirm that the Play is `Active`?

And then paste / link to the Elastalert config for this Play found under `/opt/so/rules/elastalert/playbook/<Play-ID>.yaml`

The PlayID will be found in the Play.

**Reply by hacker0ni** [reply]
Yes, the Play is set to `Active` in the Playbook. Here's the ElastAlert config for the Play:
```
alert:
- "modules.so.playbook-es.PlaybookESAlerter"
 
elasticsearch_host: "<my_manager's_FQDN>:9200"
play_title: "My Play"
event.module: "playbook"
event.dataset: "alert"
event.severity: 2
rule.category: ""
play_url: "https://<my_manager's_FQDN>/playbook/issues/39"
kibana_pivot: "https://<my_manager's_FQDN>/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),interval:auto,query:(language:lucene,query:'_id:{[_id]}'),sort:!('@timestamp',desc))"
soc_pivot: "https://<my_manager's_FQDN>/#/hunt"
sigma_level: "medium"

filter:
- query:
    query_string:
      query: (event.module.security:"osquery" AND event.query.security:*custom_events AND (NOT (source.ip.keyword:(192.168.0.1 OR 192.168.0.2))))
index: '*:so-osquery-*'
name: My Play - 063bbb5bb
priority: 3
realert:
  minutes: 0
type: any
```
Redacted some fields for privacy & security.

**Reply by defensivedepth** [reply]
So next step is to tail the elastalert log for errors - make sure that an alert is going to be generated and then run:

`sudo tail -f /opt/so/log/elastalert/*.log | grep 063bbb5bb`

I think what's happening is that the elastalert file is missing the `play_id` field.

**Reply by hacker0ni** [reply]
Thanks for the answer! It seems that the Play is running but weirdly it's not getting any hits according to the log:
```
2021-11-15 19:13:06,578     INFO           elastalert Queried rule my play - 063bbb5bb from 2021-11-15 19:03 +0000 to 2021-11-15 19:13 +0000: 0 / 0 hits
2021-11-15 19:13:06,588     INFO           elastalert Ran my play - 063bbb5bb from 2021-11-15 19:03 +0000 to 2021-11-15 19:13 +0000: 0 query hits (0 already seen), 0 matches, 0 alerts sent
```
Any ideas on what may be the cause? When I copy and paste the exact ES query, I can see the exact data I want to be alerted on.

**Reply by defensivedepth** [reply]
@hacker0ni When you see this log show up in Elastalert, and then you run the query in Kibana, is the result in Kibana within 10min of your current time? Elastalert only looks back 10min to check for results.

**Reply by hacker0ni** [reply]
Thanks for reaching out! When I run the query myself, the matching results are about a week old. But I've tried making the Playbook active and generating logs that'd trigger the Play and still didn't have any luck with it, since these logs aren't generated that often.

**Reply by defensivedepth** [reply]
Not sure I understand - are you saying that you can't manually generate the logs in your env?

Have you been able to get any Play based on osquery logs to generate an alert?

**Reply by hacker0ni** [reply]
I only have a single Play that is active, because all my queries are custom and I have a Linux based environment, so most Plays don't work out-of-the-box. I believe it's going to be more useful when I start ingesting syslogs as well.

To address the confusion, I can generate logs that would trigger the Play I've written and I have already tried generating them while the Play was active, but sadly the Playbook still did not generate the alerts.

**Reply by defensivedepth** [reply]
Ok, I believe one of the issues you are seeing is related to osquery-based Plays. I will plan to get a fix in for this.

**Reply by hacker0ni** [reply]
Thanks for the amazing project and the support!

**Reply by hacker0ni** [reply]
@defensivedepth It seems the Play is working now. Not sure what changed honestly, but I wanted to let you know so you don't spend time on why it's not working. One small change I've made to the Sigma rule is that instead of using a filter and a selection, I simply used selection1 and selection2. Under the condition I've used something along the lines of `selection1 and not selection2`.

**Reply by defensivedepth** [reply]
Can you post the new sigma rule that you are using and resulting elastalert config? Just want to make sure of a couple things.

**Reply by hacker0ni** [reply]
Of course, the sigma looks like the following:
```
title: My Play
description: This Play looks for query results that are not generated by known good IPs
status: experimental
author: hacker0ni
tags:
logsource:
  conditions:
    event.module: 'osquery'
detection:
  selection1:
    event.query:
    - '*my_query'
  selection2:
    source.ip:
    - 192.168.0.1
    - 192.168.0.2
  condition: selection1 and not selection2
falsepositives:
- unknown
level: medium
```
and the ElastAlert config looks like the following, note that the Play ID has changed because I've re-written the rule by creating a new one, I've also redacted my manager's FQDN:
```
alert:
- "modules.so.playbook-es.PlaybookESAlerter"

elasticsearch_host: "<manager_FQDN>:9200"
play_title: "My Play"
play_id: "92ebcbdda"
event.module: "playbook"
event.dataset: "alert"
event.severity: 2
rule.category: ""
play_url: "https://<manager_FQDN>/playbook/issues/40"
kibana_pivot: "https://<manager_FQDN>/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),interval:auto,query:(language:lucene,query:'_id:{[_id]}'),sort:!('@timestamp',desc))"
soc_pivot: "https://<manager_FQDN>/#/hunt"
sigma_level: "medium"

filter:
- query:
    query_string:
      query: (event.query:(*my_query) AND (NOT (source.ip.keyword:(192.168.0.1 OR 192.168.0.2))))
index: '*:so-*'
name: My Play - 92ebcbdda
priority: 3
realert:
  minutes: 0
type: any

```
