### DISCUSSION TITLE
yum connects every 15 minutes

### DISCUSSION THREAD

**Discussion by Masaya-A** [Security-Onion-Solutions/securityonion#6130] [Unsupported Versions] [answered]
Despite of #4985, all of my standalone rigs connect to repo.securityonion.net:443 every 15 minutes.
It seems that `salt state.highstate` does this since timing of connections is following "minute" value in `salt/schedule.sls`.
I want to reduce the number of connections like every 12 hours, but I couldn't figure out how to, except chainging state.highstate intervals.
Could you tell me any ideas how to fix, please? Or is this a specification?

Following log is from my proxy (squid) server (Accutual IPs were sanitised, and time is UNIX time):
```
1636350493.973   1048 IP.OF.SEC.ONION TCP_TUNNEL/200 45483 CONNECT repo.securityonion.net:443 - FIRSTUP_PARENT/IP.OF.PARENT.PROXY -
1636351394.187   1238 IP.OF.SEC.ONION TCP_TUNNEL/200 45470 CONNECT repo.securityonion.net:443 - FIRSTUP_PARENT/IP.OF.PARENT.PROXY -
1636352294.478   1404 IP.OF.SEC.ONION TCP_TUNNEL/200 45469 CONNECT repo.securityonion.net:443 - FIRSTUP_PARENT/IP.OF.PARENT.PROXY -
1636353194.047   1142 IP.OF.SEC.ONION TCP_TUNNEL/200 45468 CONNECT repo.securityonion.net:443 - FIRSTUP_PARENT/IP.OF.PARENT.PROXY -
1636354094.843   2007 IP.OF.SEC.ONION TCP_TUNNEL/200 45405 CONNECT repo.securityonion.net:443 - FIRSTUP_PARENT/IP.OF.PARENT.PROXY -
```

Result of `salt-call schedule.list`:
```
local:
    schedule:
      patch_os_schedule:
        args:
        - patch.os
        enabled: true
        function: state.sls
        hours: 12
        jid_include: true
        maxrunning: 1
        name: patch_os_schedule
        return_job: true
        splay: 300
      salt-minion-state-apply-test:
        args:
        - salt.minion-state-apply-test
        enabled: true
        function: state.sls
        jid_include: true
        maxrunning: 1
        minutes: 5
        name: salt-minion-state-apply-test
        splay:
          end: 180
          start: 0
      schedule:
        enabled: true
        function: state.highstate
        jid_include: true
        maxrunning: 1
        minutes: 15
        name: schedule
```

===============================
Security Onion version: 2.3.80
Install source: Network
OS: CentOS 7
Install type: Standalone
