### DISCUSSION TITLE
Is my BPF filter bad?

### DISCUSSION THREAD

**Discussion by influence2006** [Security-Onion-Solutions/securityonion#6250] [Unsupported Versions] [answered]
Today I noticed that my bpf filter that used to work from 2.3.70 is no longer working in 2.3.80
```
nids:
 bpf:
  - not host 10.0.4.84 &&
  - not host 10.0.10.171 &&
  - not host 172.16.116.77 &&
  - not host 172.17.76.85 &&
  - not host 10.0.11.92
  ```
  
  Anyone else having issues with bpf filters?

**Comment by dougburks** [comment]
That appears to match what we have documented at https://docs.securityonion.net/en/2.3/bpf.html for a Suricata NIDS BPF.

What exactly are you seeing that leads you to believe that this Suricata NIDS BPF is no longer working?

**Reply by influence2006** [reply]
@dougburks highstate says my bpf filter fails, I am seeing these ips/hostnames in kibana. I do not use zeek.

**Reply by dougburks** [reply]
Are you able to provide the exact highstate message?

Have you double-checked your syntax? See the warning at:
https://docs.securityonion.net/en/2.3/salt.html#configuration

**Reply by influence2006** [reply]
@dougburks 
```
----------
          ID: suribpfcompilationfailure
    Function: test.configurable_test_state
      Result: False
     Comment: BPF Syntax Error - Discarding Specified BPF
     Started: 15:23:56.230927
    Duration: 1.498 ms
     Changes:
```
