### DISCUSSION TITLE
SO 2.3.90 Logstash Error on Search Node

### DISCUSSION THREAD

**Discussion by ben-sec** [Security-Onion-Solutions/securityonion#6341] [Unsupported Versions] [answered]
Hello!

Yesterday I ran soup on my Manager Node to install SO 2.3.90 and  this morning I noticed that Logstash is no longer running on my Search Node. I restarted the node and found the following errors in logstash.log:

```
[2021-11-24T08:15:23,828][ERROR][logstash.inputs.beats    ] Invalid setting for beats input plugin:
      input {
        beats {
          # This setting must be a path
          # File does not exist or cannot be opened /usr/share/logstash/filebeat.crt
          ssl_certificate => "/usr/share/logstash/filebeat.crt"
          ...
        }
      }
    [2021-11-24T08:15:23,830][ERROR][logstash.inputs.beats    ] Invalid setting for beats input plugin:
        input {
        beats {
          # This setting must be a path
          # File does not exist or cannot be opened /usr/share/logstash/filebeat.key
          ssl_key => "/usr/share/logstash/filebeat.key"
          ...
        }
     }

```

What went wrong and how can I fix that? Thanks in advance!

Cheers, Ben

**Comment by m0duspwnens** [comment, marked as answer]
@ben-sec Did you customize the pipeline on the searchnode? Can you run the following from the searchnode? 
`salt-call pillar.get logstash:pipelines`

**Reply by ben-sec** [reply]
Yes, I have two custom pipelines:

```
ocal:
    ----------
    manager:
        ----------
        config:
            - so/0009_input_beats.conf
            - so/0010_input_hhbeats.conf
            - so/9999_output_redis.conf.jinja
            - custom/dns-gdc-import.conf
            - custom/dns-pdc-import.conf
            - custom/dns-output.conf
            - custom/beacons-import.conf.jinja
    search:
        ----------
        config:
            - so/0900_input_redis.conf.jinja
            - so/9000_output_zeek.conf.jinja
            - so/9002_output_import.conf.jinja
            - so/9034_output_syslog.conf.jinja
            - so/9050_output_filebeatmodules.conf.jinja
            - so/9100_output_osquery.conf.jinja
            - so/9400_output_suricata.conf.jinja
            - so/9500_output_beats.conf.jinja
            - so/9600_output_ossec.conf.jinja
            - so/9700_output_strelka.conf.jinja
            - so/9800_output_logscan.conf.jinja
            - so/9900_output_endgame.conf.jinja
```

**Reply by m0duspwnens** [reply]
Just to confirm, is this the output from running `salt-call pillar.get logstash:pipelines` from the manager or from your searchnode? Did you add the manager pipeline to your searchnode?

**Reply by TOoSmOotH** [reply]
The issue according to the error message is you are using a filebeat input directly on the search node. Is this what your custom pipeline is doing?

**Reply by ben-sec** [reply]
That's the output from the Search node. I declared the following in /opt/so/saltstack/local/pillar/global.sls on the Manager node

```
logstash:
     pipelines:
       manager:
         config:
           - so/0009_input_beats.conf
           - so/0010_input_hhbeats.conf
           - so/9999_output_redis.conf.jinja
           - custom/dns-gdc-import.conf
           - custom/dns-pdc-import.conf
           - custom/dns-output.conf
           - custom/beacons-import.conf.jinja
```
