### DISCUSSION TITLE
Elastalert custom rule not working

### DISCUSSION THREAD

**Discussion by Sahale** [Security-Onion-Solutions/securityonion#6406] [Unsupported Versions] [answered]
Hello.
I am trying to create custom rule to detect if any host stopped sending me logs via syslog.
So I've created this rule:
```
index: '*:so-syslog-*'
name: Host stopped sending syslog logs beta - 4b5812bd9
type: flatline
doc_type: _doc
threshold: 1    # if it drops down below, alert will be triggered
use_count_query: true   # I don't need to get results, only total numbers
query_key: log.source.address   # unique for every host
timeframe:
  minutes: 5
falsepositives:
    - None
priority: 2
realert:
  minutes: 60
```
But I don't get any alerts after disabling sending logs at all on some hosts. so-elastalert-test return 0 matches also. Am I missing something?
Thanks a lot.

**Comment by weslambert** [comment, marked as answer]
Have you tried removing `doc_type`? Also you might try checking the logs in `/opt/so/log/elastalert` for clues.

**Reply by Sahale** [reply]
`doc_type` is required, when `use_count_query` set.
I've changed rule to 
```
index: '*:so-syslog-*'
name: Host stopped sending syslog logs beta - 4b5812bd9
type: flatline
threshold: 1
query_key: log.source.address
timeframe:
  minutes: 30
falsepositives:
  - None
fields:
   - log.source.address
priority: 2
realert:
  minutes: 0
```
and it's working now.

I have some problem with same rule for syslog: field `log.source.address` contains port also and every change of source port triggers alert. Should I change parser to generate source IP or there is another way? Thanks!
