### DISCUSSION TITLE
Send Cisco syslog to Filebeat

### DISCUSSION THREAD

**Discussion by rusqq** [Security-Onion-Solutions/securityonion#6591] [Unsupported Versions] [answered]
Hello there!

I'm a new Security Onion user for few weeks and I'm truly in love with all options. I try to suit it to my needs and as there I'm not a developer it's a little challenge for me. 

Please have a look for an architecture I'm trying to build. I've got a few Cisco devices and I would like to send all syslogs to Elasticsearch instance in Security Onion. To be honest maybe my understanding is wrong but as far as I know I have to configure Filebeat for this.

![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/96235374/146354750-53b48123-4434-46c0-966f-afe3601ffd0d.png)
 
Have a look at my config in `/opt/so/saltstack/default/salt/filebeat/thirdpartydefaults.yaml`

```
third_party_filebeat:
  modules:
    [...]
    cisco:
      asa:
        enabled: false
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9001
      ftd:
        enabled: false
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9003
      ios:
        enabled: false
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9002
      nexus:
        enabled: false
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9506
      meraki:
        enabled: false
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9525
      umbrella:
        enabled: false
      amp:
        enabled: false

```

So as far as I know I have only to configure devices to send syslog to ports 9001, 9002 etc. Ok great, but how can I enable it? Could I do it in `/opt/so/saltstack/local/pillar/minions/securityonion_standalone.sls` file? My config there look like this:

```
filebeat:
 third_party_filebeat:
   modules:
    cisco:
     asa:
      enabled: true

```
But when I put netstat -tulnp I don't see Security Onion is listening to these ports but I enabled it on firewall. How can I fix it?
