### DISCUSSION TITLE
Suricata threshold breaks highstate

### DISCUSSION THREAD

**Discussion by rosswakelin** [Security-Onion-Solutions/securityonion#6678] [Unsupported Versions] [answered]
Hi

We are trying to suppress some suricata rules from firing from some source devices.
We are following the instructions in the documentation, and in the latest video (thanks for that) but are still having an issue.
This is the lines we have added to global.sls:

``` 
thresholding:
  sids:
    2031297:
      - suppress:
        gen_id: 1
        track: by_src
        ip: 10.16.96.30
```
We then ran **so-idstools-restart** and s**o-rule-update** and both ran without any errors.
When we run **salt sensorname_sensor state.highstate** we get two errors:

```
----------
          ID: surithresholding
    Function: file.managed
        Name: /opt/so/conf/suricata/threshold.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'None' has no attribute 'gen_id'
     Started: 10:25:58.964670
    Duration: 54.374 ms
     Changes:
----------

```
and 
```----------
          ID: so-suricata
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: suricata.surithresholding
     Started: 10:25:59.039361
    Duration: 0.029 ms
     Changes:
----------
```
This is running 2.3.91 using the ISO install.

**Comment by dougburks** [comment, marked as answer]
Have you made any other changes to global.sls?

Did you add those lines to the very end of global.sls?

Have you double-checked spacing?

If you remove the lines from global.sls, does the error go away?

**Comment by mnasec** [comment]
Same on my installation, Version 2.3.91, spaces in yml double checked and suppression is not working:

```
[root@xxx pillar]# tail global.sls
docker:
  range: '172.17.0.0/24'
  bip: '172.17.0.1/24'
thresholding:
  sids:
    2101411:
      - suppress:
        gen_id: 1
        track: by_src
        ip: <ip-address>
[root@xxx pillar]#
```
          ID: surithresholding
    Function: file.managed
        Name: /opt/so/conf/suricata/threshold.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'None' has no attribute 'gen_id'
     Started: 23:06:36.987898
    Duration: 64.253 ms
     Changes:

          ID: so-suricata
    Function: docker_container.running
      Result: False
     Comment: One or more requisite failed: suricata.surithresholding
     Started: 23:06:37.065592
    Duration: 0.003 ms
     Changes:

```Summary for xxx_sensor
--------------
Succeeded: 248 (changed=14)
Failed:      2
--------------
Total states run:     250
Total run time:    58.524 s
```
After removing the lines:
```
--------------
Succeeded: 250 (changed=16)
Failed:      0
--------------
Total states run:     250
Total run time:    77.838 s
```

```
[root@xxx pillar]# tail global.sls
      - windows
redis_settings:
  redis_maxmemory: 812
playbook:
  api_key: xxx
sensoroni:
  node_checkin_interval_ms: 10000
docker:
  range: '172.17.0.0/24'
  bip: '172.17.0.1/24'
```

**Reply by mnasec** [reply]
grrr i really missed two additional spaces in the line after suppress, before gen_id ... ;-(
```
[root@xxx pillar]# tail global.sls
docker:
  range: '172.17.0.0/24'
  bip: '172.17.0.1/24'
thresholding:
  sids:
    2101411:
      - suppress:
          gen_id: 1
          track: by_src
          ip: <ip-address>
```
seems to work, after a highstate i got no error anymore:
```

          ID: surithresholding
    Function: file.managed
        Name: /opt/so/conf/suricata/threshold.conf
      Result: True
     Comment: File /opt/so/conf/suricata/threshold.conf updated
     Started: 23:51:09.777896
    Duration: 108.815 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,2 +1,2 @@

                  -##### The thresholding pillar has not been defined
                  +suppress gen_id 1, sig_id 2101411, track by_src, ip <ip-address>

Summary for xxx_sensor
--------------
Succeeded: 250 (changed=16)
Failed:      0
--------------
Total states run:     250
Total run time:    72.262 s
