### DISCUSSION TITLE
BPF Syntax Error - Discarding Specified BPF

### DISCUSSION THREAD

**Discussion by Grackis** [Security-Onion-Solutions/securityonion#6785] [Unsupported Versions] [answered]
Hello Everyone, I have seen many posts on here with people having issues with their BPF filters and for the life of me I cannot understand why I cannot get these errors to stop, I have tried it both ways I will show below and Both of them throw the same error when I restart the respective services related to the filter I am editing

I have tried using and && or || I have tried - not "stuff" I have tried every combination of things that I was able to find on the web to try and debug why this isn't working. I use BPF filters in Wireshark on the regular and these should work. Why is this having issues in Security Onion? so very frustrating been trying to figure out what's wrong for days =(

```
steno:
 bpf:
  - not port 443
  - not dst port 445 &&
  - not (src host a.a.a.a || src host b.b.b.b || src net c.c.c.c/24)
  - not port 53 &&
  - not (dst host a.a.a.a || dst host b.b.b.b || dst host c.c.c.c || dst host d.d.d.d)
nids:
 bpf:
  - not port 53 &&
  - not (dst host a.a.a.a || dst host b.b.b.b || dst host c.c.c.c || dst host d.d.d.d)
  - not dst port 15000 &&
  - not src net 10.69.0.0/16
zeek:
 bpf:
  - not port 53 &&
  - not (host a.a.a.a || host b.b.b.b || host c.c.c.c || host d.d.d.d)
  - not port 88 &&
  - not (host a.a.a.a || host b.b.b.b)


Alternate Method Attempt:
zeek:
 bpf:
  - not dst host a.a.a.a or
  - not dst host b.b.b.b or
  - not dst host c.c.c.c or
  - not dst host d.d.d.d and
  - not port 53
  - not host a.a.a.a or
  - not host b.b.b.b and
  - not port 88
```

**Comment by Grackis** [comment, marked as answer]
So, After further Testing. I can get the following lines to work. but as soon as i add another line it errors out, so something is clearly going wrong at this point im still not sure what.
```
zeek:
 bpf:
  - not port 53 &&
  - not (host a.a.a.a || host b.b.b.b || host c.c.c.c || host d.d.d.d)
```
If i add anything after this, like another line or anything at all it then errors out.
Examples:
```
zeek:
 bpf:
  - not port 53 &&
  - not (host a.a.a.a || host b.b.b.b || host c.c.c.c || host d.d.d.d)
  - not port 443
``` -This fails

**Reply by Grackis** [reply]
OK, I think i figured it out for anyone else having this issue, it was my fault not the software per usual =)

So apparently, you need to append each line with an AND or OR until the very bottom its not "separate" lines so my code Should of looked like....

```
steno:
 bpf:
  - not port 443 &&
  - not (dst port 445 && (src host a.a.a.a || src host b.b.b.b || src net c.c.c.c/24)) &&
  - not (port 53 && (dst host a.a.a.a || dst host b.b.b.b || dst host c.c.c.c || dst host d.d.d.d))
nids:
 bpf:
  - not (port 53 && (dst host a.a.a.a || dst host b.b.b.b || dst host c.c.c.c || dst host d.d.d.d)) &&
  - not (dst port 15000 && src net 10.69.0.0/16)
zeek:
 bpf:
  - not (port 53 && (host a.a.a.a || host b.b.b.b || host c.c.c.c || host d.d.d.d)) &&
  - not (port 88 && (host a.a.a.a || host b.b.b.b))
```

I hope this helps anyone else having this issue
