### DISCUSSION TITLE
Jinga Rendoring Error -  Rendering SLS 'base:filebeat' failed: Jinja variable None has no element 0

### DISCUSSION THREAD

**Discussion by lugashisnotafed** [Security-Onion-Solutions/securityonion#6798] [Unsupported Versions]
Hey everyone,
I'm having some rendering issues for one of my minions.
Running 2.3.91
2 sensors
1 sensor works fine  while the other gives me an error which will be listed below. I'm not exactly a saltstack/jinja pro so any help would be appreciated.
```

    Data failed to compile:
----------
    Rendering SLS 'base:firewall' failed: Jinja variable None has no element 0
/var/cache/salt/minion/files/base/firewall/hostgroups.yaml(23):
---
[...]
          - 127.0.0.1
    self:
      ips:
        delete:
        insert:
          - {{ salt['grains.get']('ip_interfaces').get(salt['pillar.get']('sensor:mainint', salt['pillar.get']('manager:mainint', salt['pillar.get']('elasticsearch:mainint', salt['pillar.get']('host:mainint')))))[0] }}    <======================
---
----------
    Rendering SLS 'base:filebeat' failed: Jinja variable None has no element 0

```

**Comment by m0duspwnens** [comment]
@lugashisnotafed This code is trying to find the IP address of the node by looking at element 0 of the grains.ip_interfaces list for the interface defined in the pillar. In this case, check the value of the pillar `sensor:mainint` and `host:mainint` within the pillar file for the minion located at `/opt/so/saltstack/local/pillar/minions/<hostname>_sensor.sls`. The value should be the your main interface that has an IP and a connection to the network.

**Reply by lugashisnotafed** [reply]
Here's a snip of the minion SLS file.  *fyi the other one that works has identical config aside from the internal IPs*
```
# cat BROKEN_sensor.sls
host:
  mainint: 'tun0'
sensoroni:
  node_address: 'someinternaladdy'
  node_description: 'somename'

sensor:
  interface: 'bond0'
  mainip: 'someinternalip'
  mainint: 'tun0'
```snip`````
```
  
  Could it be some wierd space or something in the sls file?

**Reply by m0duspwnens** [reply]
If you run `salt-call grains.get ip_interfaces`, do you see tun0 listed? If tun0 is listed, is the first item in the list the IP of the node?

**Reply by lugashisnotafed** [reply]
Yea it appears so. Below is the output from the broken sensor
I tried it on the working sensor and received similar output but have differen't ens160 and tun0 ips.

the funny thing is when is so-checkin FROM the sensor it updates no problem.

```
# salt-call grains.get ip_interfaces
local:
    ----------
    bond0:
    docker0:
        - 172.17.0.1
    ens160:
        - 172.16.x.x
    ens192:
    lo:
        - 127.0.0.1
    tun0:
        - 172.31x.x
```
