### DISCUSSION TITLE
Suppressing Multiple SIDs for an IP

### DISCUSSION THREAD

**Discussion by wdhachfeld** [Security-Onion-Solutions/securityonion#6911] [Unsupported Versions] [answered]
I'm going to apologize in advance if this is something that has been covered before. It seems like it has probably been asked. But I can't for the life of me locate an answer searching through the discussions and documentation...

On my small home network I have a Mac that is used solely for the Time Machine backup of 2 laptops. I'm finding that the SMB backup traffic triggers a **lot** of false positive alerts. So I would like to disable all (or at least multiple) Suricata rules for the backup Mac (which I can assign a fixed IP). From the documentation my understanding is that I need to modify my _/opt/so/saltstack/local/pillar/minions/securityonion_standalone.sls_ and add something like the following:

```
thresholding:
  sids:
    're:ET POLICY':
      - suppress:
        gen_id: 1
        track: by_either
        ip: 192.168.0.42
```

But I've never seen an example anywhere in the documentation or these discussions where anything other than an actual numeric SID is used. So I'm skeptical the above would actually work. Is there a way to do this? Or do I have to cut/paste the suppression section for each and every SID that I'd like to suppress?
