### DISCUSSION TITLE
Security Onion 2 Disable Rules By Category

### DISCUSSION THREAD

**Discussion by bit1290** [Security-Onion-Solutions/securityonion#6948] [Unsupported Versions] [answered]
Hello,

In security onion 16 we could disable rules by category:

https://docs.securityonion.net/en/16.04/alerts.html#disable-the-category

But i dont see that on security onion 2:

https://docs.securityonion.net/en/2.3/managing-alerts.html#disable-the-sid

Is there any way to disable rules by category on security onion 2?

Thanks :)

**Comment by presianbg** [comment, marked as answer]
It's right there (your 2nd link):
![image](https://user-images.githubusercontent.com/2163486/150736445-cbdaa50c-cc50-42ca-b8bc-5cc8452e7b2a.png)

here is mine:
```
idstools:
  config:
    oinkcode: 'snip'
    ruleset: ETPRO
    urls: null
  sids:
    disabled:
    - '2028807'
    - '2027390'
    - '2101411'
    - '2027766'
    - '2013504'
    - '2027865'
    - 're:ET POLICY'
    - 're:ET INFO'
    - 're:ET CHAT'
    - '2032981'
    - '2027758'
    - '2027757'
```

Cheers,
PY
