### DISCUSSION TITLE
Rita Filebeat

### DISCUSSION THREAD

**Discussion by johnununu** [Security-Onion-Solutions/securityonion#6971] [Unsupported Versions] [answered]
## BE SURE TO FOLLOW **https://docs.securityonion.net/en/latest/about.html** FOR ADDING/MODIFYING/CREATING ANYTHING!!!

First pull down **mongo:4.2.18** docker image and get it over to your sensor/forwarding nodes (where zeek logs are created)
Follow Rita install procedures (**https://github.com/activecm/rita**) on the forward/sensor nodes.  Be sure to use:
```
          sudo ./install.sh --disable-zeek --disable-mongo
```
On the manager in a distributed deployment, this worked for me.  There is some room for improvement.
# /opt/so/saltstack/local/salt/filebeat/etc/filebeat.yml
```
- type: filestream
  paths:
    - /logs/filebeat/beacons.csv
  exclude_lines: ['^Score']
  prospector.scanner.resend_on_touch: true
  index: "so-rita-%{+yyyy.MM.dd}"
  fields:
    module: rita
    category: network
    dataset: beacons
  processors:
  - add_tags:
      tags: ["rita","beacon"]
  - decode_csv_fields:
      fields:
        message: beacons.csv
      separator: ","
      ignore_missing: false
      overwrite_keys: true
      trim_leading_space: false
      fail_on_error: true
  - extract_array:
      field: beacons.csv
      mappings:
        score: 0
        source.ip: 1
        destination.ip: 2
        connections: 3
        avg_bytes: 4
        intvl_range: 5
        size_range: 6
        top_intvl: 7
        top_size: 8
        top_intvl_count: 9
        top_size_count: 10
        intvl_skew: 11
        size_skew: 12
        intvl_dispersion: 13
        size_dispersion: 14
        total_bytes: 15

  fields_under_root: true
  clean_removed: false
  close_removed: false
```
# /opt/so/saltstack/local/pillar/logstash/search.sls 
```
        - custom/9997_output_rita.conf.jinja
```     
# /opt/so/saltstack/local/salt/logstash/pipelines/config/custom/9997_output_rita.conf.jinja 
```
{%- if grains['role'] == 'so-eval' -%}
{%- set ES = salt['pillar.get']('manager:mainip', '') -%}
{%- else %}
{%- set ES = salt['pillar.get']('elasticsearch:mainip', '') -%}
{%- endif %}
{%- set ES_USER = salt['pillar.get']('elasticsearch:auth:users:so_elastic_user:user', '') %}
{%- set ES_PASS = salt['pillar.get']('elasticsearch:auth:users:so_elastic_user:pass', '') %}
output {
  if [module] =~ "rita" {
    elasticsearch {
      pipeline => "%{module}.%{dataset}"
      hosts => "{{ ES }}"
{% if salt['pillar.get']('elasticsearch:auth:enabled') is sameas true %}
      user => "{{ ES_USER }}"
      password => "{{ ES_PASS }}"
{% endif %}
      index => "so-rita"
      template_name => "so-rita"
      template => "/templates/so-rita-template.json"
      ssl => true
      ssl_certificate_verification => false
    }
  }
}
```
# /opt/so/saltstack/local/pillar/elasticsearch/search.sls 
```
        - custom/so-rita-template.json.jinja
```
# /opt/so/saltstack/local/salt/elasticsearch/templates/custom/so-rita-template.json.jinja 
```
{%- set SHARDS = salt['pillar.get']('elasticsearch:index_settings:so-rita:shards', 1) %}
{%- set REPLICAS = salt['pillar.get']('elasticsearch:replicas', 0) %}
{%- set REFRESH = salt['pillar.get']('elasticsearch:index_settings:so-rita:refresh', '30s') %}
{
  "index_patterns": ["so-rita-*"],
  "version":50001,
  "order":11,
  "settings":{
    "number_of_replicas":{{ REPLICAS }},
    "number_of_shards":{{ SHARDS }},
    "index.refresh_interval":"{{ REFRESH }}"
  }
}
```
# /opt/so/saltstack/local/salt/elasticsearch/files/ingest/rita.beacons
```
{
  "description" : "rita.beacons",
  "processors" : [
    { "csv":      {
        "description": "Beacons from RITA.",
        "field": "message",
        "target_fields": ["score","source.ip","destination.ip","connections","avg_bytes","intvl_range","size_range","top_intvl","top_size","top_intvl_count","top_size_count","intvl_skew","size_skew","intvl_dispersion","size_dispersion","total_bytes"],
        "separator": ",",
        "ignore_missing": true,
        "trim": true
        }
    },
    { "set": { "field": "_index", "value": "so-rita", "ignore_failure": true } },
    {
      "date_index_name": {
        "field": "@timestamp",
        "index_name_prefix": "{{ _index }}-",
        "date_rounding": "d",
        "ignore_failure": true,
        "index_name_format": "yyyy.MM.dd"
      }
    }
  ]
}
```
# /opt/so/saltstack/local/pillar/global.sls
```
elasticsearch:
  ...
  ...
  index_settings:
    ...
    ...
    so-rita:
      shards: 1
      warm: 7
      close: 15
      delete: 365
```
# cronjob script on forwarding/sensor nodes 
```
#!/bin/bash
docker run -d --name mongo -p 127.0.0.1:27017:27017 mongo:4.2.18
/usr/local/bin/rita import --rolling --numchunks 1 /nsm/zeek/logs/$(date -d"-1day" +"%Y-%m-%d") yesterday
/usr/local/bin/rita show-beacons yesterday > /opt/so/log/filebeat/beacons.csv
docker stop mongo && docker rm mongo
```

This will get you beacons from the day before in the so-rita-DATE index.
