### DISCUSSION TITLE
ElastAlert MS Teams working but need help on Query

### DISCUSSION THREAD

**Discussion by IzacFrank** [Security-Onion-Solutions/securityonion#7051] [Unsupported Versions] [answered]
Hello all,
My MS Teams alerts are working with the below config on a standalone installation but I like to get alert only when there is Malware/Trojan detection and modify the alert a little bit with more info and better format.

I tried the below query and didn't work. Could you please help with the query?
Thank you very much in advance.
Isac
```
filter:
  - query:
      query_string:
        query: "(alert.signature:\"ET TROJAN\" OR alert.signature:\"ET CURRENT EVENTS\" OR alert.signature:\"ET MALWARE\" OR alert.signature:\"ET MOBILE MALWARE\" OR alert.signature:\"ET CNC\") AND (alert.signature:*ransom* OR alert.signature:*crypto* OR alert.signature:\"check-in\" OR alert.signature:checkin OR alert.signature:download* OR alert.signature:DL OR alert.signature:macro OR alert.signature:cnc OR alert.signature:dropper OR alert.signature:beacon OR alert.signature:backdoor OR alert.signature:c2 OR alert.signature:m2)"
```

I get alerts like the below on Teams now and they are very often so one alert would be enough per host. No matter which number I enter to "event.severity:", I get medium or low events but not only the high events. I tried 1,2 or 3.

![image](https://user-images.githubusercontent.com/93327361/151953135-fa40983a-aeed-424d-85c2-be729dd716de.png)

MS_Teams_Alert.yaml 
```
      1 # elasticsearch Host
      2 # es_host: 
      3 # es_port: 9200
      4
      5 # (Required)
      6 # Rule name, must be unique
      7 name: High Alert
      8
      9
     10 # (Required)
     11 # Index to search, wildcard supported
     12 index: "*:so-ids-*"
     13
     14 # (Required)
     15 # Type of alert.
     16 # This rule will monitor a certain field and match if that field changes.
     17 type: frequency
     18
     19 # (Required, change specific)
     20 # The field to look for changes in
     21 num_events: 1
     22 timeframe:
     23     minutes: 3
     24 buffer_time:
     25     minutes: 5
     26 allow_buffer_time_overlap: true
     27 filter:
     28     - query:
     29        query_string:
     30         query: "event.severity: 4"
     31         query: "event.module: suricata"
     32         query: "event.dataset: alert"
     33
     34 include:
     35  - rule.name
     36  - rule.category
     37  - source.ip
     38  - destination.ip
     39  - destination.port
     40
     41 # (Required)
     42 # The alert is use when a match is found
     43 alert:
     44 - "ms_teams"
     45 ms_teams_alert_summary: "Alert"
     46 ms_teams_theme_color: '#ff0000'
     47 ms_teams_webhook_url: "https://xxxxx.webhook.office.com/webhookb2/8xx5ccxxx32c0-6def-492dxxxx
```
