### DISCUSSION TITLE
Suricata logs to manager node

### DISCUSSION THREAD

**Discussion by rusqq** [Security-Onion-Solutions/securityonion#7063] [Unsupported Versions] [answered]
Hi,

I deployed one manager node and one forward node. I enabled suricata and zeek on forward node and want to send all logs via filebeat to logstash/elasticsearch. Unfortunately I don't see any events on manager node. Here's a `/opt/so/conf/filebeat/etc/filebeat.yml `config:

```
#----------------------------- Elasticsearch/Logstash output ---------------------------------

output.logstash:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # The Logstash hosts
  hosts: ["so-manager:5644"]

  # Number of workers per Logstash host.
  worker: 1

  # Number of records to send to Logstash input at a time
  bulk_max_size: 2048
```
I am not sure, but probably I should change the logstash host. I changed it to IP:5044 and after an error to :5644, but nothing. Any ideas?
