### DISCUSSION TITLE
Netflow Data Unable to be Imported to Security Onion

### DISCUSSION THREAD

**Discussion by talkelley3** [Security-Onion-Solutions/securityonion#7453] [Unsupported Versions] [answered]
I've been working on implementing Netflow into our standalone Security Onion install following this doc page: https://docs.securityonion.net/en/2.3/filebeat.html
The ports section of `/opt/so/saltstack/local/salt/filebeat/init.sls` shows as 
```
- port_bindings:
127         - 0.0.0.0:514:514/udp
128         - 0.0.0.0:514:514/tcp
129         - 0.0.0.0:5066:5066/tcp
130         - 0.0.0.0:2055:2055/udp
```
/opt/so/saltstack/local/pillar/minions/<manager.sls> Shows
```
filebeat:
   third_party_filebeat:
     modules:
       netflow:
         log:
           enabled: true
           var.netflow_host: 0.0.0.0
           var.netflow_port: 2055
       cisco:
         meraki:
           enabled: true
           var.syslog_host: 0.0.0.0
           var.syslog_port: 2057
 firewall:
   assigned_hostgroups:
     chain:
       DOCKER-USER:
         hostgroups:
           meraki:
             portgroups:
               - portgroups.meraki
           netflow:
             portgroups:
               - portgroups.netflow
       INPUT:
         hostgroups:
           meraki:
             portgroups:
               - portgroups.netflow
           netflow:
             portgroups:
               - portgroups.netflow
```
docker ps | grep so-filebeat Shows:
```
3054ad63e447   secon1:5000/security-onion-solutions/so-filebeat:2.3.100             "/usr/local/bin/dock…"   21 seconds ago   Up 19 seconds         0.0.0.0:514->514/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:2055->2055/tcp, 0.0.0.0:2055->2055/udp, 0.0.0.0:2057->2057/tcp, 0.0.0.0:5066->5066/tcp, 0.0.0.0:2057->2057/udp   so-filebeat
```
