### DISCUSSION TITLE
Thresholding-based alert suppression does not work when it should

### DISCUSSION THREAD

**Discussion by DrewHorrigan** [Security-Onion-Solutions/securityonion#7464] [Unsupported Versions]
Hi, we've been tuning our rules in SO and I keep finding occurrences of alerts that, by all accounts, have been excluded via thresholding/suppression.

Here is the corresponding section of our `global.sls` pillar file for a specific SID (IPs have been changed to protect the innocent):

```
thresholding:
  sids:
    # ... some lines skipped ... #
    2034800:
      - suppress:
          gen_id: 1
          track: by_src
          ip: 10.0.0.1
      - suppress:
          gen_id: 1
          track: by_dst
          ip: '[10.0.0.2, 10.0.0.3, 10.0.0.4, 10.0.0.5, 10.0.0.6]'
      - suppress:
          gen_id: 1
          track: by_dst
          ip: '[10.0.0.7, 10.0.0.8, 10.0.0.9, 10.0.0.10]'
```

When checking `/etc/suricata/threshold.conf` in `so-suricata` container, I can see that the thresholding settings have indeed been replicated from the pillar file:
```
suppress gen_id 1, sig_id 2034800, track by_src, ip 10.0.0.1
suppress gen_id 1, sig_id 2034800, track by_dst, ip [10.0.0.2, 10.0.0.3, 10.0.0.4, 10.0.0.5, 10.0.0.6]
suppress gen_id 1, sig_id 2034800, track by_dst, ip [10.0.0.7, 10.0.0.8, 10.0.0.9, 10.0.0.10]
```

Despite that, we still get alerts. I checked `/nsm/suricata/eve-*.json` directly, and I do indeed see the corresponding entry with dest_ip 10.0.0.4:
```
{"timestamp":"2022-03-07T07:12:04.021994+0000","flow_id":243729466373006,"in_iface":"bond0","event_type":"alert","vlan":[123],"src_ip":"10.1.0.1","src_port":54031,"dest_ip":"10.0.0.4","dest_port":25,"proto":"TCP","community_id":"1:WgStK8g9w/t7G1FtXVrshHGm8oQ=","alert":{"action":"allowed","gid":1,"signature_id":2034800,"rev":2,"signature":"ET EXPLOIT Apache log4j RCE Attempt - lower/upper TCP Bypass M2 (Outbound) (CVE-2021-44228)","category":"Attempted Administrator Privilege Gain","severity":1,"metadata":{"attack_target":["Server"],"created_at":["2021_12_17"],"cve":["CVE_2021_44228"],"deployment":["Internal","Perimeter"],"former_category":["EXPLOIT"],"signature_severity":["Major"],"tag":["Exploit"],"updated_at":["2021_12_17"]},"rule":"alert tcp $HOME_NET any -> any any (msg:\"ET EXPLOIT Apache log4j RCE Attempt - lower/upper TCP Bypass M2 (Outbound) (CVE-2021-44228)\"; flow:established,to_server; content:\"|24 7b|jndi|3a|\"; nocase; fast_pattern; pcre:\"/^(l|r|d|\\x24\\x7b(lower|upper)\\x3a(l|r|d)\\x7d)(d|n|m|\\x24\\x7b(lower|upper)\\x3a(d|n|m)\\x7d)(a|i|s|\\x24\\x7b(lower|upper)\\x3a(a|i|s)\\x7d)(p|\\x24\\x7b(lower|upper)\\x3a(p)\\x7d)/Ri\"; content:\"|3a 2f 2f|\"; distance:0; reference:cve,2021-44228; classtype:attempted-admin; sid:2034800; rev:2; metadata:attack_target Server, created_at 2021_12_17, cve CVE_2021_44228, deployment Perimeter, deployment Internal, former_category EXPLOIT, signature_severity Major, tag Exploit, updated_at 2021_12_17;)"},"payload_printable":"REDACTED,"stream":0,"packet":"REDACTED","packet_info":{"linktype":1}}
```

A side note about the square brackets in IP lists. SO documentation [specifies just using a comma-separated list of IPs with no brackets](https://docs.securityonion.net/en/2.3/managing-alerts.html#threshold). However, [Suricata documentation uses IP lists in square brackets](https://suricata.readthedocs.io/en/suricata-6.0.0/configuration/global-thresholds.html#suppress), which is its own syntax referring to IP groups. After I found that the exceptions do not work as they should, I experimented with different formats using a Suricata rule triggering on a test signature, and the thresholding seems to be working fine with both formats for the test case - but we're still getting alerts for the production rule.

Can you help me identify why the live exceptions do not work?
