### DISCUSSION TITLE
bpf specifically between 2 hosts and port

### DISCUSSION THREAD

**Discussion by RagnarSTS** [Security-Onion-Solutions/securityonion#7527] [Unsupported Versions] [answered]
I need a hint on a bpf syntax for the global.sls probably because I'm not 100% understanding the multiple conditions.
Seco itself does a ton of DNS lookups for everything under the sun that comes through it.  That is super....but I don't need the act itself captured in stenographer.  I might not even want it run through zeek.  I get how to dump all packets for a specific host or a specific port, but not sure how to join them all together.  

Functionally:
10.10.10.10: randomsource -> 10.10.10.3:53

**Comment by mnasec** [comment, marked as answer]
To filter out the traffic you mentioned you should try : 

```
not (src host 10.10.10.10 and dst host 10.10.10.3 and dst port 53)
```
 as a BPF e.g. (https://www.ibm.com/docs/en/qsip/7.4?topic=queries-berkeley-packet-filters).

To use this filter for stenographer (steno), zeek (zeek) and suricata (nids) you may bind this filter in the global pillar for all forward nodes or only on minion level for a specific forward node (https://docs.securityonion.net/en/2.3/bpf.html?highlight=bpf#global-bpf)
```
steno:
  bpf:
    - not (src host 10.10.10.10 and dst host 10.10.10.3 and dst port 53)
nids:
  bpf:
    - not (src host 10.10.10.10 and dst host 10.10.10.3 and dst port 53)
zeek:
  bpf:
    - not (src host 10.10.10.10 and dst host 10.10.10.3 and dst port 53)
```

I did not test it, but it should work this way.
Hope this helps!
