### DISCUSSION TITLE
Elastalert smtp setup

### DISCUSSION THREAD

**Discussion by wompRS** [Security-Onion-Solutions/securityonion#7531] [Unsupported Versions] [answered]
It would seem the documentation is extremely lacking in this area. I know you guys are all hard at work and there is a lot to cover in the manual. I noticed that there is no longer a so-email command. Why might this be? In the documentation it is very unclear whether Elastalert supports SMTP itself or if it still needs a nullmailer to function. From there, the setup for a nullmailer and Elastalert is completely missing. Elastalert does have a section regarding setting up your smtp_server configuration but it is very scarce.

I am sure I am not the only one that is having these issues. Previously in Security Onion 1 I had no issues getting everything set up to send to my teams channel using a .ms address. Currently, however, there is no such luck. Why was this feature removed, do you plan to re-add it, and/or am I just yelling at the wind and missing something simple?

**Comment by dougburks** [comment]
Looking at https://docs.securityonion.net/en/2.3/elastalert.html#email-internal, it seems to me like ElastAlert can send directly to an external SMTP server and so no need for nullmailer. Have you tried following these instructions?

![image](https://user-images.githubusercontent.com/1659467/158169170-83d9a8ed-5056-4970-8141-b17bf2e89d39.png)

**Reply by wompRS** [reply]
Yes, I have followed those instructions. I will sanitize this configuration but this is exactly what I have inside of playbook:

- We are set up to send to an MS Teams channel as we did successfully with the previous version of Security Onion (16.x)
- We are using a direct-send relay to forward internally to our tenant's teams channel
- I have a previous configuration used with the old version (16.x) that I have post at the bottom and sanitized with identical entries.


**/opt/so/rules/elastalert/playbook/testalert.yaml**

Note that bolded items below have been replaced to sanitize config

`
```
alert:
- "email"
email:
- "**teamschannel**@amer.teams.ms"
smtp_host: "**rasutherland**.mail.protection.outlook.com"
smtp_port: 25
from_addr: "securityonion@**domain.org**"

elasticsearch_host: "securityonion:9200"
play_title: "SCM Database Privileged Operation"
play_id: "bdb5aefca"
event.module: "playbook"
event.dataset: "alert"
event.severity: 4
rule.category: "builtin"
play_url: "https://securityonion/playbook/issues/56"
kibana_pivot: "https://securityonion/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),interval:auto,query:(language:lucene,query:'_id:{[_id]}'),sort:!('@timestamp',desc))"
soc_pivot: "https://securityonion/#/hunt"
sigma_level: "critical"

filter:
- query:
    query_string:
      query: (winlog.channel.security:"Security" AND event.code.security:"4674" AND winlog.event_data.ObjectType.security:"SC_MANAGER\ OBJECT" AND winlog.event_data.ObjectName.security:"servicesactive" AND PrivilegeList.security:"SeTakeOwnershipPrivilege" AND SubjectLogonId.security:"0x3e4")
index: '*:so-*'
name: SCM Database Privileged Operation - bdb5aefca
priority: 1
realert:
  minutes: 0
type: any
```
`



Old alert:


```
# es_host: elasticsearch
# es_port: 9200
name: Attack-Response Activity Observed
type: any
index: "*:logstash-ids*"
# use_count_query: true
doc_type: "doc"
# num_events: 1
# timeframe:
#     minutes: 50
filter:
- query:
    query_string:
       query: "event_type:snort AND message:\"ET ATTACK_RESPONSE\""
realert:
  minutes: 0
alert:
- "email"
email:
- "teamschannel@amer.teams.ms"
smtp_host: "localexchangeserver"
smtp_port: 25
from_addr: "securityonion@domain.org"
alert_text: |
    Attack-response activity detected.
    message: {0}
alert_text_args: ["message"]
alert_text_type: alert_text_only
```
`

**Reply by dougburks** [reply]
Have you checked the logs in `/opt/so/log/elastalert/`?

**Reply by wompRS** [reply]
Absolutely! It is not providing too much information other than that it is not in verbose mode. It's possible this is the problem, however, I find it unlikely that the rule testing mechanism meant to test these specific things is not off by default. The results in the log are such:

cat /opt/so/log/elastalert/elastalert.log

```
2022-03-17 17:28:40,423     INFO           elastalert Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
2022-03-17 17:28:40,639     INFO           elastalert Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
2022-03-17 17:28:40,710     INFO apscheduler.scheduler Adding job tentatively -- it will be properly scheduled when the scheduler starts
2022-03-17 17:28:41,040     INFO           elastalert Queried rule SCM Database Privileged Operation - bdb5aefca from 2022-03-16 17:28 UTC to 2022-03-16 17:38 UTC: 0 / 0 hits
2022-03-17 17:28:41,166     INFO           elastalert Queried rule SCM Database Privileged Operation - bdb5aefca from 2022-03-16 17:38 UTC to 2022-03-16 17:48 UTC: 0 / 0 hits
2022-03-17 17:28:41,272     INFO           elastalert Queried rule SCM Database Privileged Operation - bdb5aefca from 2022-03-16 17:48 UTC to 2022-03-17 17:08 UTC: 0 / 0 hits
2022-03-17 17:28:49,173     INFO           elastalert Queried rule SCM Database Privileged Operation - bdb5aefca from 2022-03-17 17:08 UTC to 2022-03-17 17:18 UTC: 0 / 0 hits
2022-03-17 17:28:49,556     INFO           elastalert Queried rule SCM Database Privileged Operation - bdb5aefca from 2022-03-17 17:18 UTC to 2022-03-17 17:28 UTC: 0 / 0 hits
```

The configuration is such:

cat bdb5aefca.yaml

```
alert:
- "email"
email:
- "999999999.domain.org@amer.teams.ms"
smtp_host: "exch-01"
smtp_port: 25
smtp_ssl: true
from_addr: "securityonion@domain.org"


elasticsearch_host: "securityonion:9200"
play_title: "SCM Database Privileged Operation"
play_id: "bdb5aefca"
event.module: "playbook"
event.dataset: "alert"
event.severity: 4
rule.category: "builtin"
play_url: "https://securityonion-server/playbook/issues/56"
kibana_pivot: "https://securityonion/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),interval:auto,query:(language:lucene,query:'_id:{[_id]}'),sort:!('@timestamp',desc))"
soc_pivot: "https://securityonion/#/hunt"
sigma_level: "critical"

filter:
- query:
    query_string:
      query: (winlog.channel.security:"Security" AND event.code.security:"4674" AND winlog.event_data.ObjectType.security:"SC_MANAGER\ OBJECT" AND winlog.event_data.ObjectName.security:"servicesactive" AND PrivilegeList.security:"SeTakeOwnershipPrivilege" AND SubjectLogonId.security:"0x3e4")
index: '*:so-*'
name: SCM Database Privileged Operation - bdb5aefca
priority: 1
realert:
  minutes: 0
type: any
[user@securityonion playbook]#
```

The result of the so-elastalert-test:

```
Choose a rule to test from the list above (must be typed exactly as shown above): playbook/bdb5aefca.yaml
The results can be rather long.  Would you like to write the results to a file? (y/N) n

Didn't get any results.
1 rules loaded

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'rule_name': 'SCM Database Privileged Operation - bdb5aefca', 'endtime': datetime.datetime(2022, 3, 17, 17, 37, 52, 394553, tzinfo=tzutc()), 'starttime': datetime.datetime(2022, 3, 16, 17, 37, 52, 394553, tzinfo=tzutc()), 'matches': 0, 'hits': 0, '@timestamp': datetime.datetime(2022, 3, 17, 17, 38, 5, 96217, tzinfo=tzutc()), 'time_taken': 12.128985166549683}


Test completed successfully!

```
