### DISCUSSION TITLE
Anyone done elastic performance monitoring (e.g. metricbeat) in SO?

### DISCUSSION THREAD

**Discussion by abesinger** [Security-Onion-Solutions/securityonion#7671] [Unsupported Versions] [answered]
I want to see performance metrics from Elastic (such as shown [here](https://www.elastic.co/guide/en/kibana/7.17/elasticsearch-metrics.html) on a distributed install. I'm wondering if anyone has done it already and can provide some pointers/howtos? It looks like a considerable amount of work to start doing this from scratch.

I've read some of the Elastic docs on the topic. Looks like it now requires installing and configuring metricbeat, along with Elastic configs.  I'm guessing that since SO search nodes are individual clusters, the metricbeat config is going to be a bit different than discussed [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html); that doc assumes one's running a traditional cluster. Unfortunately the Elastic docs are written assuming you've read all of the other documents already and are familiar with what every configuration option means.

So, it would be nice to at least get pointed in the right direction and maybe a couple of steps down the road.

**Comment by trocade** [comment]
This is what I use for monitoring ES clusters with metricbeat and send them to a separate cluster.
There might be limitations due to the basic/oos license if you can actually send information from several cluster to one for monitoring.


**Disclaimer**: I actually don't use this for SO but for other setups, but the approach should be the same.
In our SO setup we use one central big cluster, so for that I was lazy and just enabled internal monitoring since it is still supported by ES until version 8.

xpack_module.yml to get data from a remote cluster:
```
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: [ "https://s<host>:9200" ]
    scope: cluster
    username: "remote_monitoring_user"
    password: "<password>"
    ssl.enabled: true
    ssl.certificate_authorities: ["<ca>" ]
    ssl.verification_mode: "full"
```

And this is metricbeat.yml:
```
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

output.elasticsearch:
  hosts: '<destination>'
  username: '<user>'
  password: '<password>'
  ssl.certificate_authorities: [ "<ca>" ]
  ssl.verification_mode: "full"
  bulk_max_size: "20"
```

I run metricbeat in docker with this docker-compose:
```
     metricbeat:
        image: metricbeat:7.16.3
        hostname: metricbeat
        container_name: metricbeat
        logging:
          options:
            tag: "{{.Name}}"
        restart: unless-stopped
        volumes:
          - metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
          - xpack_module.yml:/usr/share/metricbeat/modules.d/xpack_module.yml:ro
```
