### DISCUSSION TITLE
Filebeat fails to start after upgrade to .110

### DISCUSSION THREAD

**Discussion by tomjones1977** [Security-Onion-Solutions/securityonion#7674] [Unsupported Versions]
**UPDATE** 

The issue appears to be with how salt is generating the config for particular files where logstash variable exist.  The two areas of issue are `filebeat.yml` and `0900_input_redis.conf`.  Both are blank where logstash variables form part of the jinja template.

`/opt/so/saltstack/default/salt/filebeat/etc/filebeat.yml`:
```
  # The Logstash hosts
  hosts:
{%- if grains.role in ['so-sensor', 'so-fleet', 'so-node', 'so-idh'] %}
{%-   set LOGSTASH = namespace() %}
{%-   set LOGSTASH.count = 0 %}
{%-   set LOGSTASH.loadbalance = false %}
{%-   set node_data = salt['pillar.get']('logstash:nodes') %}
{%-   for node_type, node_details in node_data.items() | sort -%}
{%-     if node_type in ['manager', 'managersearch', 'standalone', 'receiver' ] %}
{%-       for hostname in node_data[node_type].keys() %}
{%-         set LOGSTASH.count = LOGSTASH.count + 1 %}
    - "{{ hostname }}:5644" #{{ node_details[hostname].ip }}
{%-       endfor %}
{%-     endif %}
{%-     if LOGSTASH.count > 1 %}
{%-       set LOGSTASH.loadbalance = true %}
{%-     endif %}
{%-   endfor %}
```

`/opt/so/saltstack/default/salt/logstash/pipelines/config/so/0900_input_redis.conf.jinja`:
```
{% set THREADS = salt['pillar.get']('logstash_settings:ls_input_threads', '') -%}
{% set BATCH = salt['pillar.get']('logstash_settings:ls_pipeline_batch_size', 125) -%}
{% from 'logstash/map.jinja' import REDIS_NODES with context -%}

{% for index in range(REDIS_NODES|length) -%}
{%   for host in REDIS_NODES[index] -%}
input {
        redis {
                host => '{{ host }}'
                port => 9696
                ssl => true
                data_type => 'list'
                key => 'logstash:unparsed'
                type => 'redis-input'
                threads => {{ THREADS }}
                batch_count => {{ BATCH }}
        }
}
{%   endfor %}
{% endfor -%}
```

I upgraded a distributed cluster to 110 and rebooted all the nodes.  After the reboot the search and forward nodes failed to start filebeat (and logstash on the search nodes).

`docker logs so-filebeat` shows the same error on all servers:

`Exiting: error initializing publisher: missing required field accessing 'output.logstash.hosts' (source:'/usr/share/filebeat/filebeat.yml')`

I'm not sure which salt config populates the filebeat.yml on each node so am not sure where to check further at this stage.

Filebeat appears to be working on the master node but no logs are being stored in Elasticsearch since the reboot.

Edit:

filebeat.yml is missing the hosts entry:

```
output.logstash:
  enabled: true
  hosts:
  loadbalance: false
  worker: 1
  bulk_max_size: 2048

  ssl.verification_mode: full
  ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]
  ssl.certificate_authorities: ["/usr/share/filebeat/intraca.crt"]
  ssl.certificate: "/usr/share/filebeat/filebeat.crt"
  ssl.key: "/usr/share/filebeat/filebeat.key"
setup.template.enabled: false
```
