### DISCUSSION TITLE
Threshold explanation

### DISCUSSION THREAD

**Discussion by SignauxGirod** [Security-Onion-Solutions/securityonion#7768] [Unsupported Versions] [answered]
Hello,

i'm trying to understand configuration of Thresholding but there are some case that i need explanation.

If i take this : 
```
 - rate_filter:
          gen_id: 1
          track: by_rule
          count: 50
          seconds: 30
          new_action: pass
          timeout: 30
```

someone can tell me the result (if i have 100 match in 30seconds for example) ?

Second example : 

```
11223344:
      - threshold:
          gen_id: 1
          type: threshold
          track: by_dst
          count: 10
          seconds: 10
      - rate_filter:
          gen_id: 1
          track: by_src
          count: 50
          seconds: 20
          new_action: pass
          timeout: 60
```

If i understand right the  type threshold, one alert is display for each 10 count in 10 seconds, in this way what's the goal of the rate_filter ? 

thank you in advance
