### DISCUSSION TITLE
Unable to get Sophos XG filebeat module working

### DISCUSSION THREAD

**Discussion by cyb3rz3us** [Security-Onion-Solutions/securityonion#7778] [Unsupported Versions]
### General

**SO version:** 2.3.110
**Platform:** VM within ESX 6.5
**vCPU:** 8
**RAM:** 32GB
**HDD:** system = 500GB; nsm = 1TB
**RAID status:** not implemented
**Installed using:** SO ISO

### Description

After making the required changes (based on SO and Elastic docs), I do not see the module loaded in the Docker container and therefore, do not see any Sophos XG logs ingested into SO.

#### /opt/so/saltstack/local/pillar/minions/tyr_standalone.sls

```
filebeat:
  third_party_filebeat:
    modules:
      sophos:
        xg:
          enabled: true
          var.default_host_name: [ OMITTED ]
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9514
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          log_sources:
            portgroups:
              - portgroups.beats_custom
      INPUT:
        hostgroups:
          log_sources:
            portgroups:
              - portgroups.beats_custom
```

#### Firewall changes
* Log source is 192.168.5.13
* Logs are sent to UDP 9514

```
[220413_071700+0000 2586] > sudo so-firewall includedhosts syslog
192.168.5.11
192.168.5.13
192.168.5.254

[220413_072825+0000 2591] > sudo so-firewall listportgroups
beats_custom
syslog_cust

[220413_073623+0000 2592] > sudo so-firewall listports beats_custom udp
9514
```

After executing the ```sudo so-filebeat-restart``` command, I do see the above Sophos XG config within the ```/opt/so/conf/filebeat/modules/thirdparty.yml``` file:

```
- module: sophos
  xg:
    enabled: true
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9514
    var.default_host_name: [ OMITTED ]
```

However, when executing the ```filebeat module list``` command within the ```so-filebeat``` container, I do not see the Sophos module.  However, I do see ```thirdparty``` listed and because I'm not sure if Sophos should also be listed, this may be a normal result to this command:

```
[220413_070159+0000 4686] > sudo docker exec -it so-filebeat bash

root@so-filebeat:/usr/share/filebeat# filebeat modules list
Enabled:
securityonion
thirdparty

Disabled:
```

Finally, I did enable DEBUG logging but I do not see even a single instance of the word **sophos** mentioned in any logfile in the  ```/opt/so/log/filebeat/``` directory.
