### DISCUSSION TITLE
getting syslog logs from centralized log server

### DISCUSSION THREAD

**Discussion by Jackson-Pollock** [Security-Onion-Solutions/securityonion#7881] [Unsupported Versions] [answered]
Incase if we have centralized log server where all network devices are forwarding logs to it and then that centralized server outputting it to the Security Onion on syslog:514 then what would be the correct way to parse it using filebeat (since filebeat modules can help to create separate datasets)?
1. Get directly on Security Onion syslog:514 and then use filebeat in SO ([Reference](https://docs.securityonion.net/en/2.3/filebeat.html)) to create separate datasets (In this step currently everything is coming under so-syslog index with raw/unparsed msgs and I am not sure how to separate out log sources using so-filebeat)
2. At centralized log server level make separate log file copies of each device and then configure filebeat modules on it and then forward it to Logstash where we can see separate datasets for each supported device?

Request you to please guide here.

**Comment by Jackson-Pollock** [comment, marked as answer]
About point-1: Can we use filebeat module like below if cisco and panos syslog are coming to so:514 from the log server? 
```
filebeat:
  third_party_filebeat:
    modules:
      cisco:
        ios:
          enabled: true
          var.input: udp
          var.syslog_host: 0.0.0.0
          var.syslog_port: 514
```
```
filebeat:
  third_party_filebeat:
    modules:
      panw:
        panos:
          enabled: true
          var.input: udp
          var.syslog_host: 0.0.0.0
          var.syslog_port: 514
```
