### DISCUSSION TITLE
Custom Zeek Plugin and ZEEK_PLUGIN_PATH environment variable

### DISCUSSION THREAD

**Discussion by Nasica** [Security-Onion-Solutions/securityonion#7892] [Unsupported Versions] [answered]
Good evening,

I am trying to add a custom Zeek plugin within security onion. So far I have added a new bind to allow me to get the plugin into the container and now I am trying to setup the ZEEK_PLUGIN_PATH environment variable in order for Zeek to see the plugin.

I have been trying to do this with salt by adding the following to 
`/opt/so/saltstack/defaults/salt/zeek/init.sls` (note this is just in my home lab at the moment and I will fix this up to use local later)
```
zeek_env_var:
  environ.setenv:
    - name: ZEEK_PLUGIN_PATH
    - value: /root
    - update_minion: True
 ```
after a `so-zeek-restart` I see the following in the output

```
              ID: zeek_env_var
   Function: environ.setenv
       Name: ZEEK_PLUGIN_PATH
       Result: True
 Comment: Environ values were set
     Started: 10:52:28.686988
  Duration: 4.694 ms
  Changes:
                 __________
                 ZEEK_PLUGIN_PATH:
                          /root
```
However, if I do a `docker exec -it so-zeek /bin/bash` and then `printenv` or `docker exec -it so-zeek /bin/printenv` I don't see the environment variable listed.

Am I doing something wrong here?
Am I displaying a fundamental lack of understanding on how SecOnion/Salt/Zeek work?
Is it even possible to put custom plugins into Zeek?

Thanks for your time
