### DISCUSSION TITLE
how to change search node from hot to warm ?

### DISCUSSION THREAD

**Discussion by AhmedMontaaser** [Security-Onion-Solutions/securityonion#7914] [Unsupported Versions]
how can i change the state of searchnode to be a warm node instead of hot node in elastic clustering deployment

**Comment by cm-ops** [comment]
In the searchnode's minion pillar file - `/opt/so/saltstack/local/pillar/minions/` add the following to the elasticsearch pillar:
```
  config:
    node:
      attr:
        box_type: warm
```
Then restart Elasticsearch on the searchnode.
