### DISCUSSION TITLE
BPF To Filter Specific Host and Port Combination

### DISCUSSION THREAD

**Discussion by Mfisher925** [Security-Onion-Solutions/securityonion#7967] [Unsupported Versions] [answered]
Hello,

I'm trying to apply a BPF to prevent ids traffic sniffing for our SNMP server.  I can't seem to get the filter to only filter that specific host and udp port, the filter blocks ALL traffic with that host and ALL traffic with that port.  I'm using the filter below.

```
nids:
  bpf:
    - not host 10.6.67.12 and not udp port 161
```

**Comment by mnasec** [comment, marked as answer]
i would suggest
```
nids:
  bpf:
    - not(host 10.6.67.12 and udp and dst port 161)
```

**Reply by Mfisher925** [reply]
Just tried that exact rule and no luck, doesn't block anything from that host and port.

**Reply by mnasec** [reply]
means you are getting still alarms or do you want to block the pcap generation or the generation of metadata? In this case you should use steno: or zeek: instead of nids:

**Reply by Mfisher925** [reply]
To save disk and processing, we don't want any of the services to create logs/alerts for any of the SNMP traffic from our SNMP server X.X.X.X .

The rule you suggested didn't appear to block any SNMP traffic for some reason.  

When I applied the rule I posted at the top it blocks all SNMP traffic and all traffic from X.X.X.X from being received by the NIDS.

**Reply by mnasec** [reply]
ok, the rule i posted should block the alarms for the **answers** to your snmp server 10.6.67.12.

So to keep it silent for pcap, metadata and alarms, please try:
```
nids:
  bpf:
    - not(host 10.6.67.12 and udp and port 161)
	
zeek:
  bpf:
    - not(host 10.6.67.12 and udp and port 161)
	
steno:
  bpf:
    - not(host 10.6.67.12 and udp and port 161)
```
Please remember yaml format, no tabs, only two spaces
