### DISCUSSION TITLE
Enable filebeat to pickup Zeek syslog files

### DISCUSSION THREAD

**Discussion by Pecillo** [Security-Onion-Solutions/securityonion#7989] [Unsupported Versions] [answered]
Hi

For various reasons I can't use normal syslog, I need to grab the syslog messages via a span port and monitor interface. This part works and I can see the syslog files on the sensor nodes in the zeek log folder. All log files but the syslogs are picked up by filebeat. 

I'd like filebeat to pickup the syslog files from the sensor nodes zeek logs folder.

From what I managed to make out from the documentation I should add a pillar file with the config. However I can see the pillar files on the sensor nodes but not on the master/search node. On the master/search node I do have a salt file with the filebeat config.

Should I create a pillars/filebeat folder och just copy the default salt filebeat file to local salt filebeat  and do the change there on the master/search node. And will that config be picked up on the sensor nodes or do I need to configure each individual sensor node?

If so any pointers in the right direction?

Brand new installation of SO 2.3.110.
1 Master/Slave node
4 sensor nodes that will become 6 nodes next few days.

**Comment by dougburks** [comment, marked as answer]
Have you tried running `so-zeek-logs` and selecting the `syslog` option?
https://docs.securityonion.net/en/2.3/so-zeek-logs.html#so-zeek-logs

**Reply by Pecillo** [reply]
Syslog is enabled, challenge is to get filebeat to pass it on to ELK.

**Reply by dougburks** [reply]
Right, that's what `so-zeek-logs` does. From https://docs.securityonion.net/en/2.3/so-zeek-logs.html#so-zeek-logs:
> If you want to specify what [Zeek](https://docs.securityonion.net/en/2.3/zeek.html#zeek) logs are ingested, you can use so-zeek-logs. It will show you a list of all [Zeek](https://docs.securityonion.net/en/2.3/zeek.html#zeek) logs and you can specify which of those logs are ingested. Once you’ve made your selection, it will modify the [Filebeat](https://docs.securityonion.net/en/2.3/filebeat.html#filebeat) configuration for you.

**Reply by Pecillo** [reply]
Zeek does write a syslog.log file, however default beats input for syslog is tcp/514 and udp/514. So filebeats ignores the file written by Zeek.

sensorhost:/opt/so/conf/filebeat/etc/filebeat.yml:
```
filebeat.inputs:
#------------------------------ Log prospector --------------------------------
- type: udp
  enabled: true
  host: "0.0.0.0:514"
  fields:
    module: syslog
    dataset: syslog
  pipeline: "syslog"
  index: "so-syslog"
  processors:
  - drop_fields:
      fields: ["source", "prospector", "input", "offset", "beat"]
  fields_under_root: true

- type: tcp
  enabled: true
  host: "0.0.0.0:514"
  fields:
    module: syslog
    dataset: syslog
  pipeline: "syslog"
  index: "so-syslog"
  processors:
  - drop_fields:
      fields: ["source", "prospector", "input", "offset", "beat"]
  fields_under_root: true

```

and by adding a pillar file this showed up in the config enabling the processing of the syslog.log file in the Zeek log folder.



```

# USER PILLAR DEFINED INPUTS
- type: filestream
  paths:
  - /nsm/zeek/logs/current/syslog.log
  fields:
    module: syslog
    dataset: syslog
  processors:
  - drop_fields:
      fields: '["source", "prospector", "input", "offset", "beat"]'
  fields_under_root: true
  clean_removed: false
  close_removed: false

```

**Reply by Pecillo** [reply]
I took another look at `so-zeek-logs` it looks like it modifies `/opt/so/saltstack/local/pillar/zeeklogs.sls`.
I can see syslog checked but I can't see it in the `zeeklogs.sls` file.

So I tried to disable is, no change to the file and when I run `so-zeek-logs` again it's still selected. File permissions are rw --r --r so running it via sudo should work.

```
zeeklogs:
  enabled:
    - conn
    - dce_rpc
    - dhcp
    - dnp3
    - dns
    - dpd
    - files
    - ftp
    - http
    - intel
    - irc
    - kerberos
    - modbus
    - notice
    - ntlm
    - pe
    - radius
    - rfb
    - rdp
    - sip
    - smb_files
    - smb_mapping
    - smtp
    - snmp
    - ssh
    - ssl
    - tunnel
    - weird
    - mysql
    - socks
    - x509

```



```
#!/bin/bash
local_salt_dir=/opt/so/saltstack/local

zeek_logs_enabled() {
  echo "zeeklogs:" > $local_salt_dir/pillar/zeeklogs.sls
  echo "  enabled:" >> $local_salt_dir/pillar/zeeklogs.sls
  for BLOG in "${BLOGS[@]}"; do
    echo "    - $BLOG" | tr -d '"' >> $local_salt_dir/pillar/zeeklogs.sls
  done
}

whiptail_manager_adv_service_zeeklogs() {
  BLOGS=$(whiptail --title "so-zeek-logs" --checklist "Please Select Logs to Send:" 24 78 12 \
  "conn" "Connection Logging" ON \
  "dce_rpc" "RPC Logs" ON \
  "dhcp" "DHCP Logs" ON \
  "dnp3" "DNP3 Logs" ON \
  "dns" "DNS Logs" ON \
  "dpd" "DPD Logs" ON \
  "files" "Files Logs" ON \
  "ftp" "FTP Logs" ON \
  "http" "HTTP Logs" ON \
  "intel" "Intel Hits Logs" ON \
  "irc" "IRC Chat Logs" ON \
  "kerberos" "Kerberos Logs" ON \
  "modbus" "MODBUS Logs" ON \
  "notice" "Zeek Notice Logs" ON \
  "ntlm" "NTLM Logs" ON \
  "pe" "PE Logs" ON \
  "radius" "Radius Logs" ON \
  "rfb" "RFB Logs" ON \
  "rdp" "RDP Logs" ON \
  "sip" "SIP Logs" ON \
  "smb_files" "SMB Files Logs" ON \
  "smb_mapping" "SMB Mapping Logs" ON \
  "smtp" "SMTP Logs" ON \
  "snmp" "SNMP Logs" ON \
  "ssh" "SSH Logs" ON \
  "ssl" "SSL Logs" ON \
  "syslog" "Syslog Logs" ON \
  "tunnel" "Tunnel Logs" ON \
  "weird" "Zeek Weird Logs" ON \
  "mysql" "MySQL Logs" ON \
  "socks" "SOCKS Logs" ON \
  "x509" "x.509 Logs" ON 3>&1 1>&2 2>&3 )

  local exitstatus=$?

  IFS=' ' read -ra BLOGS <<< "$BLOGS"

  return $exitstatus
}

whiptail_manager_adv_service_zeeklogs
return_code=$?
case $return_code in
  1)
    whiptail --title "so-zeek-logs" --msgbox "Cancelling. No changes have been made." 8 75
    ;;
  255)
    whiptail --title "so-zeek-logs" --msgbox "Whiptail error occured, exiting." 8 75
    ;;
  *)
    zeek_logs_enabled
    ;;
esac


```

**Reply by dougburks** [reply]
I just tested `so-zeek-logs` and it works as expected for me:
- enabling the `syslog` option writes a new `/opt/so/saltstack/local/pillar/zeeklogs.sls` file that includes `- syslog`
- disabling the `syslog` option writes a new `/opt/so/saltstack/local/pillar/zeeklogs.sls` file that does not include `- syslog`

When you run through `so-zeek-logs` and make a change, is it updating the timestamp on `/opt/so/saltstack/local/pillar/zeeklogs.sls`?

**Reply by Pecillo** [reply]
Strange... Not that I look at the timestamps they get updated. 
Schrodinger setting... You don't know if it there or not until you look.

I did run the so-zeek-logs multiple times... Did I press cancel, since I did not do any changes? Not sure but it works as intended. 

I can now see that syslog section showed up in:` /opt/so/conf/filebeat/etc/filebeat.yml` on the sensor node.

Thanks for the assistance!

**Comment by Pecillo** [comment]
This post had the answer:  #https://github.com/Security-Onion-Solutions/securityonion/discussions/7760

I ended up adding the following to `/opt/so/saltstack/local/pillar/minions/{sensornode.sls}` on the Master node. Remaning question is if I can add this as a global config affecting all sensor nodes and still be sure that a update won't wipe my config.

Now I can see syslog messages extracted by Zeek via a span port. This way I can send syslog messages to a imagined destination possibly terminated via a null route in a router upstream from the SPAN port.

```
filebeat:
  config:
    inputs:
      - type: filestream
        paths:
          - /nsm/zeek/logs/current/syslog.log
        fields:
          module: syslog
          dataset: syslog
        processors:
          - drop_fields:
              fields: '["source", "prospector", "input", "offset", "beat"]'
        fields_under_root: true
        clean_removed: false
        close_removed: false
```
