### DISCUSSION TITLE
RITA data not comming in

### DISCUSSION THREAD

**Discussion by ben-sec** [Security-Onion-Solutions/securityonion#7999] [Unsupported Versions] [answered]
Hello!

Since two days filebeat is no longer reading my RITA output in `/nsm/rita/`, even though RITA is exporting current results in beacons.csv, exploded-dns.csv and long-connections.csv files. There are no filebeat logs for the last two days in `/opt/so/log/filebeat` on my manager node who imported the files in the past flawlessly and according to so-status filebeat is running fine. Any ideas where to find the next clue?

Cheers, Ben

**Comment by weslambert** [comment, marked as answer]
What happens if you perform a `docker logs so-filebeat`? Any clues? Have you tried restarting Filebeat to see if it makes a difference?

**Comment by weslambert** [comment]
As a test, try modifying `/opt/so/salstack/default/salt/filebeat/etc/filebeat.yaml`  and add an id to each `filestream` input:

Ex. 

`id: rita-beacon`

`id: rita-connection`

`id: rita-dns`

```
- type: filestream
  id: rita-dns
  paths:
    - /nsm/rita/exploded-dns.csv
  exclude_lines: ['^Domain', '^No results']
  fields:
    module: rita
    dataset: dns
    category: network
  processors:
  - drop_fields:
      fields: ["source", "prospector", "input", "offset", "beat"]
  fields_under_root: true
  pipeline: "rita.dns"
  index: "so-rita"
```

Then restart Filebeat: `so-filebeat-restart`
