### DISCUSSION TITLE
BPF Does Not Seem To Be Filtering Alerts in SOC

### DISCUSSION THREAD

**Discussion by thebee64** [Security-Onion-Solutions/securityonion#8004] [Unsupported Versions] [answered]
I'm trying to cut some of the really noisy alarms that are coming in.  I've watched the YT videos, read the docs and found some similar discussions, but I'm still struggling.  We have a distributed deployment consisting of sensor nodes, a mgmt node and a search node.  One of our noisy offenders is a LDAP rule and below is an example of what I've done to try and quiet it.
 
```
nids:
  bpf:
    - not(host 1.1.1.1 and tcp and port 389)
zeek:
  bpf:
    - not(host 1.1.1.1 and tcp and port 389)
steno:
  bpf:
    - not(host 1.1.1.1 and tcp and port 389)
thresholding:
  sids:
    2034812:  ### LDAP for mail
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 1.1.1.1
```
Adding the bpf rules doesn't seem to make a difference.  In SOC -> Alarms they are still showing.  Using thresholding, I get a global.sls error when trying to push it down via salt.  I've double checked my white spacing and I'm not sure what I seem to be misconfiguring there.  Any help would be greatly appreciated.

**Comment by mnasec** [comment, marked as answer]
I am using the bpf and thresholding the same way, but with two differences:
```
thresholding:
  sids:
    2013028:
      #Meraki curl User-Agent Outbound - Cloud Access
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 209.206.48.0/20
steno:
  bpf:
    - not port 443
nids:
  bpf:
    - not udp port 161
```

The comment in my config is in a separate line and i first define the thresholding and then the bpf configs.
I think the first one could be the problem. Would you please be so kind and post the error message.
