### DISCUSSION TITLE
Error modifying gobal.sls

### DISCUSSION THREAD

**Discussion by emurray91** [Security-Onion-Solutions/securityonion#8048] [Unsupported Versions] [answered]
I am new to Security Onion and I was trying to follow up on this video https://www.youtube.com/watch?v=1jEkFIEUCuI for tunning the NIDS.

I wanted to suppress a notification if the traffic comes from a specific IP address but show an alert if it comes from another IP.

I edited the document as shown in the picture

```
thresholding:
  sids:
    2033264
      - supress:
        gen_id: 1
        track: by_dst
        ip: xxx.xxx.xxx.xxx

```

But it is not working, when I restart the services they are getting stuck in wanting. If I remove the part I added it would work, but I want to filter the alerts. 

Thanks in advance for the help. 

<img width="188" alt="image" src="https://user-images.githubusercontent.com/94640555/171263598-fd138238-1f8f-456d-9533-3eb23d71dad9.png">

**Comment by xfaith** [comment]
I would check your spacing on the document.  It should be 2 spaces.  Looks like your sids line starts on line 3, not two.

example from docs: 
```
thresholding:
  sids:
    8675309:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 10.10.3.71
```




Reference doc:  https://docs.securityonion.net/en/2.3/managing-alerts.html?highlight=threshold#threshold   

(Spacing might not show)

**Comment by mnasec** [comment]
there is a colon missing after the sid number :-)

Von meinem iPhone gesendet

**Reply by emurray91** [reply]
> there is a colon missing after the sid number :-) Von meinem iPhone gesendet
> […](#)
> Am 31.05.2022 um 20:51 schrieb emurray91 ***@***.***>: ﻿ I am new to Security Onion and I was trying to follow up on this video https://www.youtube.com/watch?v=1jEkFIEUCuI for tunning the NIDS. I wanted to suppress a notification if the traffic comes from a specific IP address but show an alert if it comes from another IP. I edited the document as shown in the picture thresholding: sids: 2033264 - supress: gen_id: 1 track: by_dst ip: xxx.xxx.xxx.xxx But it is not working, when I restart the services they are getting stuck in wanting. If I remove the part I added it would work, but I want to filter the alerts. Thanks in advance for the help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Wow, I missed that. I think that solved the problem. I will let all the services get back up and report

**Comment by dougburks** [comment, marked as answer]
In addition to what others have mentioned, I'll also point out that `- supress:` should be `- suppress:` (it should have 2 `p`'s instead of 1).

**Reply by emurray91** [reply]
Thanks all for the help. 

I have edited the document and I managed to get it working with one suppression, but once I added more suppressions it won't take it. 



<img width="185" alt="image" src="https://user-images.githubusercontent.com/94640555/171671500-1b8275c1-52a1-4f64-87bb-eeec2ba1b3de.png">

**Reply by mnasec** [reply]
for me additional suppressing works:
```
thresholding:
  sids:
    2013028:
      #Meraki curl User-Agent Outbound - Cloud Access
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 209.206.48.0/20
    2013031:
      #Python-urllib/ Suspicious User Agent 
      - suppress:
          gen_id: 1
          track: by_src
          ip: 1.2.3.4,5.6.7.8,10.11.12.13
    2029421:
      - suppress:
          gen_id: 1
          track: by_either
          ip: 217.17.30.74
```

Keep in mind, that the file is in yaml format, NO tabs, just two spaces ;-)
