### DISCUSSION TITLE
Google Workspace Logs Configuration

### DISCUSSION THREAD

**Discussion by j0zza** [Security-Onion-Solutions/securityonion#8185] [Unsupported Versions]
Hey we're currently testing google workspace log ingestion In a distributed environment. We referred to this documentation: https://docs.securityonion.net/en/2.3/filebeat.html?highlight=filebeat

and were able to edit the /opt/so/saltstack/local/pillar/minions/$managernode.sls

and append the following: 
```
filebeat:
  third_party_filebeat:
    modules:
      google_workspace:
        admin:
           enabled: true
           var.jwt_file: "/usr/share/filebeat/modules.d/credentials_file.json"
           var.delegated_account: "adminuser@yourdomain.com"
        user_accounts:
           enabled: true
           var.jwt_file: "/usr/share/filebeat/modules.d/credentials_file.json"
           var.delegated_account: "adminuser@yourdomain.com"
```
with the correct parameters. However no log seems to be coming in. Now we enabled Debug logging and are checking: /opt/so/log/filebeat/ and sudo docker logs so-filebeat for clues on what we are missing. Did anyone encounter the such issue and how did you make it work?
