### DISCUSSION TITLE
Suricata rule thresholding

### DISCUSSION THREAD

**Discussion by ben-sec** [Security-Onion-Solutions/securityonion#8224] [Unsupported Versions] [answered]
Hello!

I have the following thresholding defined in `/opt/so/saltstack/local/pillar/minions/my-forward-node.sls`:

```
thresholding:
  sids:
    2001581:
        - suppress:
              gen_id: 1
              track: by_src
              ip: xxx.xxx.xxx.xxx
```

I don't know why, but I still get alarms for this rule in Suricata. Ideas?

Cheers, Ben

**Comment by mnasec** [comment]
i am not shure but it seem that there are additional 2 spaces, in the line before '- suppress:' and before the line with 'gen_id:' 4 additional spaces:

This works for me: 
```
thresholding:
  sids:
    2013028:
      #Meraki curl User-Agent Outbound - Cloud Access
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 209.206.48.0/20
```

Please remember ... sls files are yml files .... NO TABs, only two spaces ... ;-)

**Reply by ben-sec** [reply]
The extra spaces sneaked in in this online form here . Please find below the 1:1 copy from my sls-file. It matches your example and the [SO documentation](https://docs.securityonion.net/en/2.3/managing-alerts.html#threshold), but it's not working as expected. I still get alarms for 2001581 and the source IP.

```
thresholding:
  sids:
    2001581:
      - suppress:
          gen_id: 1
          track: by_src
          ip: xxx.xxx.xxx.xxx 
```
