### DISCUSSION TITLE
Trying to get hostname for cisco module beat

### DISCUSSION THREAD

**Discussion by danychouinard** [Security-Onion-Solutions/securityonion#8477] [General] [answered]
I'm trying to send all my Cisco's switch syslog to Security Onion.  The problem that I have is that I want to easily identify from wich switch an entry is comming from.  The log.source.address is a good candidate but it weirdly contain the port number.
At some point I would like to extract the host number from "event.original" but I'm nowhere close to do that.
I've seen someone use the dissect directive to extract the switch IP.  So this is where I started.  Here's my latest minion's pillar:

```
[...]
filebeat:
  third_party_filebeat:
    modules:
      cisco:
        ios:
          enabled: true
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9002
          processors:
            - dissect:
                tokenizer: "%{address}:%{}"
                field: "log.source.address"
                target_prefix: "host"
                overwrite_keys: true
```
Syslog entries are now fed to elasticsearch but I could not write any working preprocessor directives.

If my question is too specific to elasticsearch, can I at least know how to find error log for filebeat ?  My /opt/so/log/filebeat/filebeat.log file is quit empty and "docker logs so-filebeat" returns nothing.  I also tried "docker attach so-filebeat" but I get no prompt.

**Comment by dougburks** [comment]
> Syslog entries are now fed to elasticsearch but I could not write any working preprocessor directives.

One option might be to use Elasticsearch ingest parsing to pull out the information you're looking for:
https://docs.securityonion.net/en/2.3/elasticsearch.html#parsing

> If my question is too specific to elasticsearch, can I at least know how to find error log for filebeat ? My /opt/so/log/filebeat/filebeat.log file is quit empty and "docker logs so-filebeat" returns nothing. I also tried "docker attach so-filebeat" but I get no prompt.

That should be correct as shown at https://docs.securityonion.net/en/2.3/filebeat.html#diagnostic-logging. 

If you have a distributed deployment, make sure you're checking the right node.

**Reply by danychouinard** [reply]
Thank you for the pointer.  I'll be reading about the ingest parser and post something if I figure it out.

**Reply by danychouinard** [reply]
This is so overwhelming and I feel pretty stupid.  Whenever I try something and it doesn't work I have no idea if I failed to relaod the proper docker, if I failed to configure the proper salstack pillar, failed to configure the proper yml file or simply tried something stupid.

I'm at the level where I can adjust existing config, not write my own.  Working hard on that but I don't try to set my hope too high.  I was pretty darn proud to tell saltsack to put an actual config that I wrote at the proper place,  I really wished it would have work,

Anyway, I realise that I'm nowhere close to be able to write an ingest parsing rule.

Since I dont want to bother M. Burk himeself, I'm really just wondering how someone might have solve the hostname problem in the past.

**Comment by danychouinard** [comment, marked as answer]
I've been able to find a solution but I fail to implement it in Security Onion.

I've installed a plain instance of elastistack and made the following adjustement to the modules/cisco.yml

```
 ios:
    enabled: true
    var.input: syslog
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9002
    input:
      processors:
        - drop_fields:
            fields: ["agent.ephemeral_id","agent.hostname","agent.id","agent.type","agent.version","host.name"]
        - dissect:
            tokenizer: "%{address}:%{}"
            field: "log.source.address"
            target_prefix: "host"
        - dissect:
            tokenizer: "%{?key1}: %{name}:"
            field: "log.original"
            target_prefix: "host"
```

This allow me to have an host.address and host.name properly populated.  This was exciting.

I've then adjust my minion salt file 


```
filebeat:
  third_party_filebeat:
    modules:
      cisco:
        ios:
          enabled: true
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9002
          input:
            processors:
              - drop_fields:
                  fields: ["agent.ephemeral_id","agent.hostname","agent.id","agent.type","agent.version","host.name"]
              - dissect:
                  tokenizer: "%{address}:%{}"
                  field: "log.source.address"
                  target_prefix: "host"
              - dissect:
                  tokenizer: "%{?key1}: %{name}:"
                  field: "log.original"
                  target_prefix: "host"
```


This looks fine to me.  I've even logged in the docker container to make sure that the config file gets updated.  Fr some reason the fileds are missing whenever I hunt or look for it in kibana.

Is there a process of some automation magic that prevent me to add those field in SO2 ?
