### DISCUSSION TITLE
Filebeat panw module, no enabled filesets?

### DISCUSSION THREAD

**Discussion by endpointsec** [Security-Onion-Solutions/securityonion#8526] [Unsupported Versions]
Version: 2.3.140
On-Prem, standalone installation
Installed from ISO

### Issue: 
Following the filebeat Netflow example to permit Palo Alto logs, Building the logstash pipeline produces an error.

`docker exec -i so-filebeat filebeat setup modules -pipelines -modules panw -c /usr/share/filebeat/module-setup.yml`
`Exiting: module panw is configured but has no enabled filesets`

### Enable 3rd Party Module:
/opt/so/saltstack/local/pillar/minions/*.sls
```
filebeat:
  third_party_filebeat:
    modules:
      panw:
        panos:
          enabled: true
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9002
```

### Update firewall configuration:
so-firewall addhostgroup palo
so-firewall addportgroup palo
so-firewall includehost palo INTERNALSUBNET/24
so-firewall addport palo udp 9002

/opt/so/saltstack/local/pillar/minions/*.sls
```
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          palo:
            portgroups:
              - portgroups.palo
```

### Troubleshooting:
- salt-call state.highstate: No errors
- so-status: All services OK.
- tcpdump shows traffic coming to SO on port 9002
- Debugged filebeat logging and palo logs are evident at /opt/so/log/filebeat
- so-filebeat-restart: Succeeded: 140 (changed=6) Failed:      0
- salt-call state.apply common: Succeeded: 37 (changed=1) Failed:     0
- so-filebeat-module-setup: panw.panos Loaded Ingest pipelines
- so-elasticsearch-pipelines-list | grep panw

```
  "filebeat-7.17.4-panw-panos-globalprotect",
  "filebeat-7.17.4-panw-panos-hipmatch",
  "filebeat-7.17.4-panw-panos-pipeline",
  "filebeat-7.17.4-panw-panos-threat",
  "filebeat-7.17.4-panw-panos-traffic",
  "filebeat-7.17.4-panw-panos-userid",
  "filebeat-8.3.2-panw-panos-globalprotect",
  "filebeat-8.3.2-panw-panos-hipmatch",
  "filebeat-8.3.2-panw-panos-pipeline",
  "filebeat-8.3.2-panw-panos-threat",
  "filebeat-8.3.2-panw-panos-traffic",
  "filebeat-8.3.2-panw-panos-userid",
```

- iptables --list -n | grep 9002
`ACCEPT     udp  --  INTERNALSUBNET/24        0.0.0.0/0            udp dpt:9002`
- docker ps | grep 9002
` "/usr/local/bin/dock…"   0.0.0.0:514->514/tcp, 0.0.0.0:5066->5066/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:9002->9002/tcp, 0.0.0.0:9002->9002/udp so-filebeat`

Related topics:
https://github.com/Security-Onion-Solutions/securityonion/discussions/8481
https://github.com/Security-Onion-Solutions/securityonion/discussions/8392

Any suggestions on what to try next? I can't seem to build the pipeline for the data to show in Elastic.
