### DISCUSSION TITLE
global.sls thresholding limit?

### DISCUSSION THREAD

**Discussion by rscurley** [Security-Onion-Solutions/securityonion#8530] [Unsupported Versions] [answered]
Is there a limit of entries you can make in the global.sls file.  Seems like it works great until I add my eleventh rule, then it gives me a "failed to compile...rendering SLS global failed" error when I run so-suricata-restart.  Here's an example of how I have the rules entered, and everything works fine until I enter the 11th SID and then it breaks.  If I remove the 11th item, it starts fine.  I've checked the syntax many times and there appears to be nothing wrong with it.
```
thresholding:
  sids:
    2009699:
      - suppress:
          gen_id: 1
          track: by_dst
          ip: 10.x.x.x
    1100012:
      - suppress:
          gen_id: 1
          track: by_src
          ip: 10.x.x.x
```
