### DISCUSSION TITLE
Tuning using CIDR IP Range not working in global.sls

### DISCUSSION THREAD

**Discussion by ahezza** [Security-Onion-Solutions/securityonion#8576] [Unsupported Versions] [answered]
Hello, I tuned the Suricata Alert "ET POLICY HTTP traffic on port 443 (POST)" using CIDR notation to exclude the entire Sky IP Range for this alert:

```
     2013926:
       - suppress:
           gen_id: 1
           track: by_dest
           ip: 176.248.0.0/13
```
However, this is still triggering alerts.. is there an issue using CIDR ranges in /opt/so/saltstack/local/pillar/global.sls ?

Example alert from this morning:

2022-08-23 09:20:44.484 +01:00 | ET POLICY HTTP traffic on port 443 (POST) | medium | 10.0.0.6 | 58579 | 176.255.176.108 | 443 | 1 | 2013926
