### DISCUSSION TITLE
Filebeat/Netflow error "Exiting: module netflow is configured but has no enabled filesets"

### DISCUSSION THREAD

**Discussion by kingtriumph** [Security-Onion-Solutions/securityonion#9099] [Unsupported Versions] [answered]
I'm trying to get netflow (or more specifically sFlow, as I'm using HP/Aruba gear) to ingest in Security Onion version 2.3.180. When trying to enable the ingestion pipeline, I get the dreaded error "Exiting: module netflow is configured but has no enabled filesets"

I have been using the following documentation to configure netflow:
https://www.youtube.com/watch?v=ew5gtVjAs7g
https://docs.securityonion.net/en/2.3/filebeat.html

And I've looked at various forum posts about the error referenced above, including a recent one from this forum:
https://github.com/Security-Onion-Solutions/securityonion/discussions/8745

So far I am unable to get the pipeline enabled. I am running a distributed server setup. I have tried running the following command on both the manager node and the search node:

docker exec -i so-filebeat filebeat setup modules -pipelines -modules netflow -c /usr/share/filebeat/module-setup.yml

I get the same error on both the manager and search nodes.

Here is the relevant (sanitized) config of the manager pillar .sls file:

```
filebeat:
  third_party_filebeat:
    modules:
      okta:
        system:
          enabled: true
          var.url: https://oktaurl.here/stuff
          var.api_key: '####'
      fortinet:
        firewall:
          enabled: true
          var.input: udp
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9004
      o365:
        audit:
          enabled: true
          var.application_id: '####'
          var.tenants:
            - id: '####'
              name: 'faketenant.onmicrosoft.com'
          var.certificate: '/usr/share/filebeat/keynamehere.pem'
          var.key: '/usr/share/filebeat/keynamehere2.key'
      netflow:
        log:
          enabled: true
          var.netflow_host: 0.0.0.0
          var.netflow_port: 2055

firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          fortigate:
            portgroups:
              - portgroups.fortigate-syslog
          netflow:
            portgroups:
              - portgroups.netflow
      INPUT:
        hostgroups:
          fortigate:
            portgroups:
              - portgroups.fortigate-syslog
          netflow:
            portgroups:
              - portgroups.netflow
```

init.sls relevant port binding:

`        - 0.0.0.0:2055:2055/udp`

I can provide other information if necessary. There are devices on the allowed networks that are configured to send sFlow traffic to the Manager node on udp/2055. (Aruba defaults to port udp/6343 for sFlow, but it has been configured to use udp/2055).

Any assistance is very much appreciated. Thanks.
