### DISCUSSION TITLE
Problem with using sensor as hostgroup.

### DISCUSSION THREAD

**Discussion by piolug93** [Security-Onion-Solutions/securityonion#9690] [Unsupported Versions]
Hello i try add custom firewall rule on `/opt/so/saltstack/local/salt/firewall/assigned_hostgroups.local.map.yaml` by adding 
```
 role:
  eval:
  fleet:
  heavynode:
  helixsensor:
  idh:
  import:
  managersearch:
  receiver:
  standalone:
  searchnode:
  sensor:
    chain:
      DOCKER-USER:
        hostgroups:
          manager:
            portgroups:
              - {{ portgroups.wazuh_cluster }}
  manager:
    chain:
      DOCKER-USER:
        hostgroups:
          sensor:
            portgroups:
              - {{ portgroups.wazuh_cluster  }}
```

That configuration rule for manager doesn't was applied. When i change source from sensor to my own hostgroup "wazuh_cluster" or change chain to INPUT all i fine. Next experiment what i try is try bad entry as:
```
  manager:
    chain:
      DOCKER-USER:
        hostgroups:
          sensor:
              - {{ portgroups.wazuh_cluster  }}
  ```
To my suprise when i call `so-firewall apply` i don't receiv error.
