### DISCUSSION TITLE
Run Curator on playbook alerts indices

### DISCUSSION THREAD

**Discussion by 3isenHeiM** [Security-Onion-Solutions/securityonion#9739] [Unsupported Versions] [answered]
In our distributed SO infrastructure, playbook alerts are stored in the ES instance of the manager, on a daily rolling basis.
We have thus an (open) index per day. The problem is that we have **5 month-old indices that are still open**, and that fills up our `/nsm` partition on the manager.

I'm perfecly aware that deletin these indices is a loss of information, but I don't need to keep 5 month old of data answering the question "which playbook triggered on that day?".

Is is possible to add the indices `so-playbook` to curator ? Of yes, where can I configure this ? I don't think that the `global.sls` file is suited for this.

Maybe adding a similar section to the `<mamanger>.sls` elasticsearch secion ?

```
index_settings:
     so-playbook-alerts:
       index_template:
         template:
           settings:
             index:
               number_of_shards: 1
       warm: 7
       close: 30
       delete: 365
```

Thanks for the feedback!
