### DISCUSSION TITLE
Importing Windows DNS-Logs

### DISCUSSION THREAD

**Discussion by ben-sec** [Security-Onion-Solutions/securityonion#9843] [Unsupported Versions]
Hello!

I plan to import and parse Windows DNS logs into Elasticsearch. Now I found the Logstash config `/opt/so/saltstack/default/salt/logstash/pipelines/config/so/6301_dns_windows.conf` and I'm wondering how I can "enable" this? Just put it in `/opt/so/saltstack/local/salt/logstash/pipelines/config/custom/` and edit my manager.sls like

```
logstash:
   pipelines:
     manager:
       config:
       - so/0009_input_beats.conf
       - so/0010_input_hhbeats.conf
       - custom/dns-import.conf
       - custom/6301_dns_windows.conf
       - so/9999_output_redis.conf.jinja
```
(custom/dns-import.conf is a configuration to read the logs from a mounted share that is already working fine)

Additionally I have to make sure that my DNS import contains a type that matches "dns".

Anything else or any experiences with this Logstash configuration? Thanks in advance!

Cheers, Ben
