### ISSUE TITLE
FIX: Influx reporting No Results for Zeek Capture Loss

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#10956]
Influx Capture Loss shows `No Results`:
![Image](https://user-images.githubusercontent.com/1659467/257285231-caa15c21-7e0e-412a-a26d-c09c261e73da.png)

However, Zeek is actually logging Capture Loss:
![Image](https://user-images.githubusercontent.com/1659467/257285351-f4ee892b-dce6-4872-809b-a875fa9ef82a.png)

**Comment by jertel** [comment]
Pillar data appears to have been moved a few months ago but not all affected scripts/files were updated to match.

```
zeek:
  enabled: False
  config:
    node:
      lb_procs: 0
      pins_enabled: False
      pins: []
      buffer: 128*1024*1024
```
