### ISSUE TITLE
FIX: Exclude Zeek console log ingestion

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#11082]

**Comment by weslambert** [comment]
`salt/elasticfleet/defaults.yaml`:

```
logging:
  zeek:
    excluded:
      - console
```
