### ISSUE TITLE
Speed up wazuh checkin

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1236]
Wazuh is trying to register each time causing highstate to take longer

**Comment by weslambert** [comment]
This should be avoided here: https://github.com/Security-Onion-Solutions/securityonion/blob/dev/salt/wazuh/files/agent/wazuh-register-agent#L164.  Will need to ensure this is still the case.

**Comment by m0duspwnens** [comment]
Confirmed this is already in place as @weslambert mentioned. I actually tested the current code versus using salt to only run the script of the file didn't exists and the script is faster.

state output of current code:
```
----------
          ID: registertheagent
    Function: cmd.run
        Name: /usr/sbin/wazuh-register-agent
      Result: True
     Comment: Command "/usr/sbin/wazuh-register-agent" run
     Started: 21:22:30.270154
    Duration: 23.671 ms
     Changes:
              ----------
              pid:
                  409
              retcode:
                  0
              stderr:
              stdout:
                  Agent 001 already registered!
```

modified state:
```
# Register the agent
registertheagent:
  cmd.run:
    - name: /usr/sbin/wazuh-register-agent
    - cwd: /
    - unless: ls /opt/so/conf/wazuh/initial_agent_registration.log
```

modified state output. I ran this several times and time was about the same:
```
          ID: registertheagent
    Function: cmd.run
        Name: /usr/sbin/wazuh-register-agent
      Result: True
     Comment: unless condition is true
     Started: 21:26:25.008570
    Duration: 1190.354 ms
     Changes:
```
