### ISSUE TITLE
YARA update runs every minute between 7:00 and 8:00(UTC)

### ISSUE THREAD

**Issue by Masaya-A** [Security-Onion-Solutions/securityonion#1252]
_securityonion/salt/strelka/init.sls_ 
```
strelka_yara_update:
  cron.present:
    - user: root
    - name: '[ -d /opt/so/saltstack/default/salt/strelka/rules/ ] && /usr/sbin/so-yara-update > /dev/null 2>&1'
    - hour: '7'
```
I think it's enough to update once an hour or once a day.
