### ISSUE TITLE
FIX: Remove errant max_age setting from Elastic SOC config

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#12851]
The following setting is not applicable to any configuration and should be removed.

```
elasticsearch:
  index_settings:
    global_overrides:
      policy:
        phases:
          hot:
            max_age:
```
