### ISSUE TITLE
FIX: Elasticsearch index templates not loading

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#13161]
Phases for global_overrides was originally placed in the wrong location under index_template instead of policy. If a user customized this via the SOC UI,  then it would be saved as the following and create issues for templates trying to load.

```
    index_settings:
        global_overrides:
            index_template:
                phases:
                    delete:
                        min_age: 90
```

We need to remove the phases from under index_template as they are causing issues and are unused.
