### ISSUE TITLE
FIX: Custom defined template causes SLS rendering error in base:elasticsearch.enabled

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#13328]
This issue started in 2.4.80.

If a user has defined a custom index such as the following:

```
elasticsearch:
  index_settings:
    so-logs-mycustom1_x_log:
      index_sorting: false
      index_template:
        composed_of:
        - logs-mycustom1.log@package
        - logs-mycustom1.log@custom
        - so-fleet_globals-1
        - so-fleet_agent_id_verification-1
        data_stream:
          allow_custom_routing: false
          hidden: false
        index_patterns:
        - logs-mycustom1.log-*
        priority: 501
        template:
          settings:
            index:
              lifecycle:
                name: so-logs-mycustom1.log-logs
              number_of_replicas: 0
```

The elasticsearch state will fill to render:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:elasticsearch.enabled' failed: Jinja variable 'dict object' has no attribute 'so-logs-mycustomindex_x_log'
/var/cache/salt/minion/files/base/elasticsearch/template.map.jinja(22):
---
[...]
{% set ES_INDEX_SETTINGS = {} %}
{% do ES_INDEX_SETTINGS_GLOBAL_OVERRIDES.update(salt['defaults.merge'](ES_INDEX_SETTINGS_GLOBAL_OVERRIDES, ES_INDEX_PILLAR, in_place=False)) %}
{% for index, settings in ES_INDEX_SETTINGS_GLOBAL_OVERRIDES.items() %}
{#   if policy isn't defined in the original index settings, then dont merge policy from the global_overrides #}
{#   this will prevent so-elasticsearch-ilm-policy-load from trying to load policy on non ILM manged indices #}
{%   if not ES_INDEX_SETTINGS_ORIG[index].policy is defined and ES_INDEX_SETTINGS_GLOBAL_OVERRIDES[index].policy is defined %}    <======================
{%     do ES_INDEX_SETTINGS_GLOBAL_OVERRIDES[index].pop('policy') %}
{%   endif %}

{%   if settings.index_template is defined %}
{%     if not settings.get('index_sorting', False) | to_bool and settings.index_template.template.settings.index.sort is defined %}
```
