### ISSUE TITLE
Make sure soctopus.conf is not overwritten when state is applied

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#1412]

**Comment by weslambert** [comment]
Added initial implementation for SOCtopus pillar.  Can specify additional rulesets for Playbook in `global.sls`:

Ex.
```
soctopus:
  playbook:
    rulesets:
      - windows
      - ruleset2
      - ruleset3
```
