### ISSUE TITLE
file.managed is not enforcing file ownership

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1665]
A 2.3.2 standalone VM restarted but SO did not come online. I found that salt-minon was active for 15+ minutes but not logging anything. Only acng and registry containers existed. Salt logs showed issues with state.show_top() returning unexpected results, something we've seen in the past but hadn't had an opportunity to troubleshoot. I ran `salt-call state.highstate` and it failed, stating that a state.highstate operation was already in progress. After waiting for 15 minutes and the same PID claiming to still be running a highstate, yet no containers running except the two mentioned earlier, I killed the salt-minion process. 

I then applied highstate again and found that several containers went green but about 6 were left in an ERROR state. Those 6 appeared to have permission issues with files or dirs being mounted into their containers. For example, the filebeat.yml file is owned by socore when it's supposed to be owned by root, per the defined state below:
```
filebeatconfsync:
  file.managed:
    - name: /opt/so/conf/filebeat/etc/filebeat.yml
    - source: salt://filebeat/etc/filebeat.yml
    - user: 0
    - group: 0
    - template: jinja
    - defaults:
        INPUTS: {{ salt['pillar.get']('filebeat:config:inputs', {}) }}
        OUTPUT: {{ salt['pillar.get']('filebeat:config:output', {}) }}
```
Notice the output when running `state-call state.apply filebeat`:
```
----------
          ID: filebeatconfsync
    Function: file.managed
        Name: /opt/so/conf/filebeat/etc/filebeat.yml
      Result: True
     Comment: File /opt/so/conf/filebeat/etc/filebeat.yml is in the correct state
     Started: 17:40:33.527431
    Duration: 53.989 ms
     Changes:
----------
          ID: so-filebeat
    Function: docker_container.running
      Result: True
     Comment: Container 'so-filebeat' is already configured as specified. State changed from 'stopped' to 'running'.
     Started: 17:40:33.664138
    Duration: 3270.034 ms
     Changes:
              ----------
              state:
                  ----------
                  new:
                      running
                  old:
                      stopped
Summary for local
------------
Succeeded: 6 (changed=1)
Failed:    0
------------
Total states run:     6
Total run time:   3.340 s
[root@standalone ~]# ls -altr /opt/so/conf/filebeat/etc/
total 44
drwxr-xr-x. 2 socore socore    65 Oct 26 01:00 pki
drwxr-xr-x. 4 socore socore    33 Oct 26 01:13 ..
-rw-r--r--. 1 socore socore 41536 Oct 26 16:15 filebeat.yml
drwxr-xr-x. 3 socore socore    37 Oct 26 16:15 .
```
Notice that the salt claims the file was already in a matching state, yet the `ls` command afterward shows the file is not owned by root.
