### ISSUE TITLE
FIX: Firewall rules added via pillar only applies last hostgroup

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#3709]
For the following pillar values, only the syslogtosensor2 is applied and syslogtosensor1 is not

```
firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          syslogtosensor1:
            portgroups:
              - portgroups.syslog1
          syslogtosensor2:
            portgroups:
              - portgroups.syslog2
```

```
----------
          ID: insert_DOCKER-USER_analyst_xx.xx.xx.xx/24_443_tcp_70
    Function: iptables.insert
      Result: True
     Comment: iptables rule for insert_DOCKER-USER_analyst_xx.xx.xx.xx/24_443_tcp_70 already set for ipv4 (/sbin/iptables --wait -t filter -I DOCKER-USER 1 -p tcp --dport 443 --source xx.xx.xx.xx/24 --jump ACCEPT)
     Started: 13:37:20.095903
    Duration: 22.165 ms
     Changes:
----------
          ID: insert_DOCKER-USER_syslogtosensor2_11.11.11.11_22222_tcp_71
    Function: iptables.insert
      Result: True
     Comment: Set iptables rule for insert_DOCKER-USER_syslogtosensor2_11.11.11.11_22222_tcp_71 to: /sbin/iptables --wait -t filter -I DOCKER-USER 1 -p tcp --dport 22222 --source 11.11.11.11 --jump ACCEPT for ipv4
     Started: 13:37:20.118770
    Duration: 44.908 ms
     Changes:
              ----------
              locale:
                  insert_DOCKER-USER_syslogtosensor2_11.11.11.11_22222_tcp_71
----------
          ID: insert_INPUT_anywhere_0.0.0.0/0_22_tcp_72
    Function: iptables.insert
      Result: True
     Comment: iptables rule for insert_INPUT_anywhere_0.0.0.0/0_22_tcp_72 already set for ipv4 (/sbin/iptables --wait -t filter -I INPUT 1 -p tcp --dport 22 --source 0.0.0.0/0 --jump ACCEPT)
     Started: 13:37:20.164224
    Duration: 20.39 ms
     Changes:
----------
```
