### ISSUE TITLE
FIX: Salt does not generate a fleet.crt file with CUSTOM_FLEET_HOSTNAME

### ISSUE THREAD

**Issue by kimobu** [Security-Onion-Solutions/securityonion#4319]
When should this subjectAltName on line 376 be applied vs the one on line 512? I have a standalone server that is hosting all services, so it's role should include so-fleet. However, `salt-call state.apply ssl` hits line 376 and generates a fleet.crt file that does not include a fleet_custom_hostname specified in global.sls. Adding the CUSTOM_FLEET_HOSTNAME condition to line 376 generates a correct fleet.crt

https://github.com/Security-Onion-Solutions/securityonion/blob/ba7b34a8ceeb5a4d957a669d7014d067bd2207b7/salt/ssl/init.sls#L376

**Comment by defensivedepth** [comment]
Thanks for bringing this up, will look into it further

**Comment by Stephen-Ridgway** [comment]
For clarity, if line 376 is changed from:

subjectAltName: DNS:{{ manager }},IP:{{ managerip }}

to:

subjectAltName: DNS:{{ manager }},IP:{{ managerip }} {% if CUSTOM_FLEET_HOSTNAME != None %},DNS:{{ CUSTOM_FLEET_HOSTNAME }} {% endif %}

should that work?

**Comment by cm-ops** [comment]
@Stephen-Ridgway 
Yes, change the pillar to show the below:
```
/etc/pki/fleet.crt:
  x509.certificate_managed:
    - signing_private_key: /etc/pki/fleet.key
    - CN: {{ manager }}
    - subjectAltName: DNS:{{ manager }},IP:{{ managerip }} {% if CUSTOM_FLEET_HOSTNAME != None %},DNS:{{ CUSTOM_FLEET_HOSTNAME }} {% endif %}
    - days_remaining: 0
    - days_valid: 820
    - backup: True
    - unless:
      # https://github.com/saltstack/salt/issues/52167
      # Will trigger 5 days (432000 sec) from cert expiration
      - 'enddate=$(date -d "$(openssl x509 -in /etc/pki/fleet.crt -enddate -noout | cut -d= -f2)" +%s) ; now=$(date +%s) ; expire_date=$(( now + 432000)); [ $enddate -gt $expire_da
te ]'
```
This will generate the fleet.crt with a fleet_custom_hostname specified in global.sls.
