### ISSUE TITLE
FEATURE: Allow setting Filebeat Docker filesystem and Docker binds via pillar

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#5236]
Similar to how we are doing this for Logstash, we should allow for custom Docker binds for Filebeat.

Ex:

In pillar:

```
filebeat:
  docker_options:
    filesystem_bindings:
      - /myfile1onhost:/myfile1incontainer:ro
      - /myfile2onhost:/myfile2incontainer:ro
```

In `init.sls`:

```
{% set DOCKER_OPTIONS = salt['pillar.get']('filebeat:docker_options', {}) %}

{% for BINDING in DOCKER_OPTIONS.filesystem_bindings %}
      - {{ BINDING }}
{% endfor %}
```
