### ISSUE TITLE
FIX: filebeat netflow module not listening

### ISSUE THREAD

**Issue by gomipa6565** [Security-Onion-Solutions/securityonion#6057]
Filebeat netflow module activated but not listening.
I followed the documentations ,and here is what I did:
1. **Enabled netflow module** in _`/opt/so/saltstack/local/pillar/minions/$(manager)_manager.sls`_.
2. Added new ports group and called it _`netflowports`_ and added the defaul port `2055` to it.+
3. Added new hosts group and called it _`netflowhosts`_ and added the cidr range `0.0.0.0/0` to it.
4. **Added the firewall configuration** into  _`/opt/so/saltstack/local/pillar/minions/$(manager)_manager.sls`_.
5. Did `so-filebeat-restart` and `so-firewall-apply`, and even a `reboot`.

Now my manager sls file contains what I believe is a proper configurations:

```
filebeat:
  third_party_filebeat:
    modules:
      netflow:
        log:
          enabled: true

firewall:
  assigned_hostgroups:
    chain:
      DOCKER-USER:
        hostgroups:
          netflowhosts:
            portgroups:
              - portgroups.netflowports
```
**Expected behaviour:**
The module will be added with the rest of default configurations _"listening on 0.0.0.0 port 2055 udp"_, but found out it will not be listening to this port.

docker ps only gives:
```
CONTAINER ID   IMAGE                                                                COMMAND                  CREATED          STATUS                    PORTS                                                                                                      NAMES
e30bafef479c   nsm-manager:5000/security-onion-solutions/so-filebeat:2.3.80         "/usr/local/bin/dock…"   13 seconds ago   Up 11 seconds             0.0.0.0:514->514/udp, 0.0.0.0:514->514/tcp, 0.0.0.0:5066->5066/tcp                so-filebeat
```

**Real Issue:**
I found out that the init.sls for filebeat only looking for the **_var.syslog_host_**, and **_var.syslog_port_**, where the default netflow module template have **_var.netflow_host_**, and **_var_netflow_port_**, which need to be included in init.sls or changed in the default netflow module.

**My efforts:**
I did try some dirty workaround by appending both **var.syslog_hosts**, and **var.syslog_port** under the module conf, the **port opened** and **tcpdump shows data coming** from my netflow devices (one pfsense firewal and a mikrotik router) for testing, I **tried sending all versions**, **data arrive on the port** **but nothing shows up in kiabna nor any new index added to elasticsearch** even after running so-filebeat-module-setup. So I'm opening separate issue for this.
