### ISSUE TITLE
FIX: Random passwords generated at setup contain character combinations that cause problems with some containers

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#7233]
Filebeat Example. Notice how the generated password contains two consecutive dollar signs, but the actual password sent by filebeat contains a single dollar sign:

filebeat.yml:
```
output.elasticsearch:
  enabled: true
  hosts: ["http://import:9200"]
  username: "so_elastic"
  password: "kJt@vK]gATBWM]-f)qVg0L:6Xs^=1ksD.My5V,D$$>c|@Gr^JF@PwNJ)tUs,dlPk7Sl?688d"
```

tcpdump:
```
GET / HTTP/1.1
Host: import:9200
User-Agent: Elastic-Filebeat/7.17.0 (linux; amd64; 93708bd74e909e57ed5d9bea3cf2065f4cc43af3; 2022-01-28 09:53:30 +0000 UTC)
Accept: application/json
Accept-Encoding: identity;q=1.0, gzip;q=0.0
Authorization: Basic c29fZWxhc3RpYzprSnRAdktdZ0FUQldNXS1mKXFWZzBMOjZYc149MWtzRC5NeTVWLEQkPmN8QEdyXkpGQFB3TkopdFVzLGRsUGs3U2w/Njg4ZA==
X-Elastic-Product-Origin: beats
```

Base64 decoding of the auth header:
```
root@elasticsearch:/usr/share/elasticsearch# echo "c29fZWxhc3RpYzprSnRAdktdZ0FUQldNXS1mKXFWZzBMOjZYc149MWtzRC5NeTVWLEQkPmN8QEdyXkpGQFB3TkopdFVzLGRsUGs3U2w/Njg4ZA==" | base64 -d
so_elastic:kJt@vK]gATBWM]-f)qVg0L:6Xs^=1ksD.My5V,D$>c|@Gr^JF@PwNJ)tUs,dlPk7Sl?688droot@elasticsearch:/usr/share/elasticsearch#
```

The password in this issue was randomly generated by an automated test. It's left intact due to the importance of illustrating the issue. It is not a production password.
